### ISSUE TITLE
ImportError: No module named scrap on Windows 7 x64

### ISSUE THREAD

**Issue by illume** [pygame/pygame#105]
Originally reported by: **Mahmoud Hossam (Bitbucket: [mahmoudhossam](https://bitbucket.org/mahmoudhossam), GitHub: [mahmoudhossam](https://github.com/mahmoudhossam))**

----------------------------------------

I have installed Python 3.2 (32-bit) and pygame 1.9.2 on windows 7 using the installers on the website, but I get an ImportError when trying to access pygame's help inside the interpreter

    
    #!python
    
    Python 3.2.2 (default, Sep  4 2011, 09:51:08) [MSC v.1500 32 bit (Intel)] on win32
    Type "copyright", "credits" or "license()" for more information.
    >>> import pygame
    >>> pygame.init()
    (6, 0)
    >>> help(pygame)
    
    Warning (from warnings module):
      File "C:\Python32\lib\inspect.py", line 103
        return (hasattr(object, "__get__")
    RuntimeWarning: use scrap: No module named scrap
    (ImportError: No module named scrap)
    Traceback (most recent call last):
      File "<pyshell#2>", line 1, in <module>
        help(pygame)
      File "C:\Python32\lib\site.py", line 457, in __call__
        return pydoc.help(*args, **kwds)
      File "C:\Python32\lib\pydoc.py", line 1754, in __call__
        self.help(request)
      File "C:\Python32\lib\pydoc.py", line 1804, in help
        else: doc(request, 'Help on %s:', output=self._output)
      File "C:\Python32\lib\pydoc.py", line 1540, in doc
        pager(render_doc(thing, title, forceload))
      File "C:\Python32\lib\pydoc.py", line 1533, in render_doc
        return title % desc + '\n\n' + renderer.document(object, name)
      File "C:\Python32\lib\pydoc.py", line 338, in document
        if inspect.ismodule(object): return self.docmodule(*args)
      File "C:\Python32\lib\pydoc.py", line 1064, in docmodule
        for key, value in inspect.getmembers(object, inspect.isroutine):
      File "C:\Python32\lib\inspect.py", line 263, in getmembers
        if not predicate or predicate(value):
      File "C:\Python32\lib\inspect.py", line 248, in isroutine
        or ismethoddescriptor(object))
      File "C:\Python32\lib\inspect.py", line 103, in ismethoddescriptor
        return (hasattr(object, "__get__")
      File "C:\Python32\lib\site-packages\pygame\__init__.py", line 70, in __getattr__
        raise NotImplementedError(MissingPygameModule)
    NotImplementedError: scrap module not available
    (ImportError: No module named scrap)
    

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/105

**Comment by MyreMylar** [comment]
This crash doesn't happen in python 3 builds on windows anymore.

Tested original reproduction on 3.4 (pygame 1.9.6) & 3.7 (pygame 2.0-dev6) on windows.

Though even Python 3.4 is EOL now.

Recommend close.
