### ISSUE TITLE
code quality: LGTM alerts

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1133]
See here:
https://lgtm.com/projects/g/pygame/pygame/alerts/?mode=list

It finds various C and python issues.

**Comment by charlesej** [comment]
LGTM can also be setup to automatically review code in pull requests:

- https://lgtm.com/projects/g/pygame/pygame/ci/
- https://lgtm.com/help/lgtm/about-automated-code-review

**Comment by illume** [comment]
I've enabled the LGTM app on github... so it should be enabled on PRs now.

**Comment by illume** [comment]
LGTM started throwing errors in the PRs. So I had to disable it. The logs didn't show anything. Probably needs a support request to be logged.

**Comment by charlesej** [comment]
Found this in one of the [logs](https://lgtm.com/projects/g/pygame/pygame/logs/rev/pr-5db83ee99287bda27473158467112461113b4fb2/lang:python/stage:Build%20merge_32497f2cac2695ba9942c484f5e4851afad204bc) (under the Extraction tab).

```
[2019-10-08 21:25:58] [build] Configuration file:
[2019-10-08 21:25:59] [build] prepare:
[2019-10-08 21:25:59] [build] python_setup:
[2019-10-08 21:26:00] [build] Source root appears to be the real root.
[2019-10-08 21:26:00] [build] /opt/dist/tools/pybuild.zip/version.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
[2019-10-08 21:26:04] [build] New python executable in /opt/out/snapshot/workspace/venv/bin/python2
[2019-10-08 21:26:04] [build] Also creating executable in /opt/out/snapshot/workspace/venv/bin/python
[2019-10-08 21:26:04] [build] Installing setuptools, pip, wheel...
[2019-10-08 21:26:06] [build] done.
[2019-10-08 21:26:06] [build] WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
[2019-10-08 21:26:06] [build] Using UNIX configuration...
[2019-10-08 21:26:06] [build] sh: 1: sdl2-config: not found
[2019-10-08 21:26:06] [build] sh: 1: sdl2-config: not found
[2019-10-08 21:26:06] [build] sh: 1: sdl2-config: not found
[2019-10-08 21:26:06] [build] Hunting dependencies...
[2019-10-08 21:26:07] [build] WARNING: "sdl2-config" failed!
[2019-10-08 21:26:07] [build] ---
[2019-10-08 21:26:07] [build] For help with compilation see:
[2019-10-08 21:26:07] [build]     https://www.pygame.org/wiki/CompileUbuntu
[2019-10-08 21:26:07] [build] To contribute to pygame development see:
[2019-10-08 21:26:07] [build]     https://www.pygame.org/contribute.html
[2019-10-08 21:26:07] [build] ---
[2019-10-08 21:26:07] [build] Running /opt/src/setup.py failed.
[2019-10-08 21:26:07] [build] Traceback (most recent call last):
[2019-10-08 21:26:07] [build]   File "/opt/dist/tools/convert_setup.py", line 109, in convert_setup_to_requirements
[2019-10-08 21:26:07] [build]     imp.load_source("__main__", setup_file_path)
[2019-10-08 21:26:07] [build]   File "/opt/src/setup.py", line 258, in <module>
[2019-10-08 21:26:07] [build]     buildconfig.config.main(AUTO_CONFIG)
[2019-10-08 21:26:07] [build]   File "/opt/src/buildconfig/config.py", line 222, in main
[2019-10-08 21:26:07] [build]     deps = CFG.main(**kwds)
[2019-10-08 21:26:07] [build]   File "/opt/src/buildconfig/config_unix.py", line 237, in main
[2019-10-08 21:26:07] [build]     raise RuntimeError('Unable to run "sdl-config". Please make sure a development version of SDL is installed.')
[2019-10-08 21:26:07] [build] RuntimeError: Unable to run "sdl-config". Please make sure a development version of SDL is installed.
[2019-10-08 21:26:07] [build] /opt/src/setup.py failed, and a /opt/out/snapshot/workspace/setup_requirements.txt file does not exist. Exiting with error.
[2019-10-08 21:26:07] [build] ('version, root, requirement_files', 2, '/opt/src', ['', ''])
[2019-10-08 21:26:07] [build] ('Calling ', 'python2, -m, virtualenv, --never-download, /opt/out/snapshot/workspace/venv')
[2019-10-08 21:26:07] [build] Requirement files: ['', '']
[2019-10-08 21:26:07] [build] Requirements:
[2019-10-08 21:26:07] [build] ('Unable to guess Python version with Travis file due to:', KeyError('python',))
[2019-10-08 21:26:07] [build] Calling python2 /opt/dist/tools/pybuild.zip 2 /opt/src  
[2019-10-08 21:26:07] [build] index:
[2019-10-08 21:26:07] [build] Source root appears to be the real root.
[2019-10-08 21:26:07] [build] /opt/dist/tools/pybuild.zip/version.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
[2019-10-08 21:26:07] [build] [INFO] Python extractor version 5.7[0m
[2019-10-08 21:26:07] [build] [INFO] [1] Extracted file /opt/src/test/run_tests__tests/infinite_loop/__init__.py in 9ms[0m
...
```

**Comment by illume** [comment]
I turned LGTM on the PRs the other day. Not sure what happed... it just started working again.

**Comment by MyreMylar** [comment]
Only about ten more alerts to go!

I'll make a list when we hit 5.

**Comment by MyreMylar** [comment]
We are currently at 0 LGTM alerts, so closing this.
