### ISSUE TITLE
Midi test_conversions() test failing with Python 2.7

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1276]
The midi `test_conversions()` test is failing with Python 2.7.10. Passes with Python 3.7.2.

```
>py -2 -Wd -m pygame.tests.midi_test -v

pygame 2.0.0.dev3 (SDL 2.0.10, python 2.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
test_Input (__main__.MidiInputTest)
|tags: interactive| ... ok
test_close (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_poll (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_read (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_MidiException (__main__.MidiModuleTest) ... ok
test_conversions (__main__.MidiModuleTest)
of frequencies to midi note numbers and ansi note names. ... ERROR
test_get_count (__main__.MidiModuleTest) ... ok
test_get_default_input_id (__main__.MidiModuleTest) ... ok
test_get_default_output_id (__main__.MidiModuleTest) ... ok
test_get_device_info (__main__.MidiModuleTest) ... ok
test_get_init (__main__.MidiModuleTest) ... ok
test_init (__main__.MidiModuleTest) ... ok
test_midis2events (__main__.MidiModuleTest) ... ok
test_quit (__main__.MidiModuleTest) ... ok
test_time (__main__.MidiModuleTest) ... ok
test_Output (__main__.MidiOutputTest)
|tags: interactive| ... ok
test_abort (__main__.MidiOutputTest) ... ok
test_close (__main__.MidiOutputTest) ... ok
test_note_off (__main__.MidiOutputTest)
|tags: interactive| ... ok
test_note_on (__main__.MidiOutputTest)
|tags: interactive| ... ok
test_pitch_bend (__main__.MidiOutputTest) ... ok
test_set_instrument (__main__.MidiOutputTest) ... ok
test_write (__main__.MidiOutputTest) ... ok
test_write_short (__main__.MidiOutputTest)
|tags: interactive| ... ok
test_write_sys_ex (__main__.MidiOutputTest) ... ok

======================================================================
ERROR: test_conversions (__main__.MidiModuleTest)
of frequencies to midi note numbers and ansi note names.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python27\Lib\site-packages\pygame-2.0.0.dev3-py2.7-win-amd64.egg\pygame\tests\midi_test.py", line 374, in test_conversions
    self.assertEqual(frequency_to_midi(27.5), 21)
  File "pygame\midi.py", line 693, in frequency_to_midi
    12 * math.log(freqency / 440.0)
AttributeError: 'module' object has no attribute 'log'

----------------------------------------------------------------------
Ran 25 tests in 16.284s

FAILED (errors=1, skipped=3)
```

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.10) at 0fb2d37b00131c3286ccc33f0f2a0a177017983e

**Comment by illume** [comment]
Hrmm. My python 2.7.16 has math.log.

**Comment by charlesej** [comment]
The problem seems to be the `pygame.math` module is being used in Python 2.7.10, but not in Python 3.7.4. All the midi tests are marked as interactive via the midi_tags.py file, so these tests do not get run very often.

This issue seems to be consistent with Python 2.7.10. I ran the following script with several pip installed pygame versions (1.9.5, 1.9.6, and 2.0.0.dev3) with Python 2.7.10. I also tested my current development build of pygame with Python 2.7.10 and Python 3.7.4.

```python
import pygame
import pygame.midi
import math

print(math)
print(pygame.midi.math)
pygame.midi.frequency_to_midi(1)
```

---

python: 2.7.10
pygame: 1.9.5 (pip installed)
```
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'math' (built-in)>
<module 'pygame.math' from 'C:\Program Files\Python27\lib\site-packages\pygame\math.pyd'>
Traceback (most recent call last):
  File "midi_test_fail.py", line 8, in <module>
    pygame.midi.frequency_to_midi(1)
  File "C:\Program Files\Python27\lib\site-packages\pygame\midi.py", line 693, in frequency_to_midi
    12 * math.log(freqency / 440.0)
AttributeError: 'module' object has no attribute 'log'
```

---

python: 2.7.10
pygame: 1.9.6 (pip installed)
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'math' (built-in)>
<module 'pygame.math' from 'C:\Program Files\Python27\lib\site-packages\pygame\math.pyd'>
Traceback (most recent call last):
  File "midi_test_fail.py", line 8, in <module>
    pygame.midi.frequency_to_midi(1)
  File "C:\Program Files\Python27\lib\site-packages\pygame\midi.py", line 693, in frequency_to_midi
    12 * math.log(freqency / 440.0)
AttributeError: 'module' object has no attribute 'log'
```

---

python: 2.7.10
pygame: 2.0.0.dev3 (pip installed)
```
pygame 2.0.0.dev3 (SDL 2.0.9, python 2.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'math' (built-in)>
<module 'pygame.math' from 'C:\Program Files\Python27\lib\site-packages\pygame\math.pyd'>
Traceback (most recent call last):
  File "midi_test_fail.py", line 8, in <module>
    pygame.midi.frequency_to_midi(1)
  File "C:\Program Files\Python27\lib\site-packages\pygame\midi.py", line 693, in frequency_to_midi
    12 * math.log(freqency / 440.0)
AttributeError: 'module' object has no attribute 'log'
```

---

python: 2.7.10
pygame: 2.0.0.dev3 at 5a8dbfe1297501ba82af09dd3919e9f10e6d7f93
```
pygame 2.0.0.dev3 (SDL 2.0.10, python 2.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'math' (built-in)>
<module 'pygame.math' from 'C:\Program Files\Python27\lib\site-packages\pygame-2.0.0.dev3-py2.7-win-amd64.egg\pygame\math.pyd'>
Traceback (most recent call last):
  File "midi_test_fail.py", line 8, in <module>
    pygame.midi.frequency_to_midi(1)
  File "C:\Program Files\Python27\lib\site-packages\pygame-2.0.0.dev3-py2.7-win-amd64.egg\pygame\midi.py", line 693, in frequency_to_midi
    12 * math.log(freqency / 440.0)
AttributeError: 'module' object has no attribute 'log'
```

---

python: 3.7.4
pygame: 2.0.0.dev3 at 5a8dbfe1297501ba82af09dd3919e9f10e6d7f93
```
pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
<module 'math' (built-in)>
<module 'math' (built-in)>
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.4 (64bit) (recently upgraded from 3.7.2) and 2.7.10 (64bit)
- pygame: various - see above

**Comment by illume** [comment]
Aaaaah ok! I remember that `pygame.math` is shadowing the stdlib math module in python 2.x now.

I ruled out the test runner introducing the problem.

```python
>>> import pygame.midi
>>> pygame.midi.math.__file__
'/usr/local/lib/python2.7/site-packages/pygame-2.0.0.dev2-py2.7-macosx-10.13-x86_64.egg/pygame/math.so'
```

After suring the World Wide Web, I did stumble across this one weird trick...

```python
def import_non_local(name, custom_name=None):
    import imp, sys
    custom_name = custom_name or name
    f, pathname, desc = imp.find_module(name, sys.path[1:])
    module = imp.load_module(custom_name, f, pathname, desc)
    f.close()
    return module

std_math = import_non_local('math', 'std_math')
```

So we could put in a horrible hack for python 2 there. The good thing is this won't be a problem if python 2 disappears.

**Comment by charlesej** [comment]
There is also this way of handling it (ref: https://stackoverflow.com/a/8280677).

```python
from __future__ import absolute_import
import math
```

**Comment by illume** [comment]
I tried `from __future__ import absolute_import` and it doesn't seem to work.

```python
# bla.py
from __future__ import absolute_import
import math
```

```python
# math.py
a=1
```

```
$ python2 -c "import bla;print(bla.math.__file__)"
math.pyc
```

**Comment by charlesej** [comment]
Does the following work for you?

Create a directory `test_imports` with the following files.
```
test_imports
     __init__.py
    math.py
    test_absolute_import.py
    test_relative_import.py
```

```python
# __init__.py
```

```python
# math.py
print('importing local math.py')
```

```python
# test_absolute_import.py
from __future__ import absolute_import
import math
print('imported math module: {}'.format(math))
```

```python
# test_relative_import.py
import math
print('imported math module: {}'.format(math))
```


From the parent directory of `test_imports` execute these two cmds.
```
python2 -m test_imports.test_relative_import
python2 -m test_imports.test_absolute_import
```


Expected result:
```
>python2 -m test_imports.test_relative_import
importing local math.py
imported math module: <module 'test_imports.math' from 'test_imports\math.pyc'>

>python2 -m test_imports.test_absolute_import
imported math module: <module 'math' (built-in)>
```

**Comment by illume** [comment]
Cool, that does work :)

So the fix is to put at the top of midi.py

```python
from __future__ import absolute_import # otherwise pygame.math is imported rather than math builtin.
```
