### ISSUE TITLE
Building reST with sphinx-build got a keyerror

### ISSUE THREAD

**Issue by noisnemid** [pygame/pygame#1278]
when i tried to build html doc from reST folder by cli command:
sphinx-build -b html ./reST/ ./pygame_doc_sphinx/
under the docs/ path in MacOS, it got error,
the log is here.

**Comment by noisnemid** [comment]
[sphinx-err-z__yixpx.log](https://github.com/pygame/pygame/files/3562789/sphinx-err-z__yixpx.log)

**Comment by noisnemid** [comment]
# Sphinx version: 2.2.0
# Python version: 3.7.4 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 11%] c_api/freetype
#   reading sources... [ 13%] c_api/mixer
#   reading sources... [ 14%] c_api/rect
#   reading sources... [ 16%] c_api/rwobject
#   reading sources... [ 17%] c_api/surface
#   reading sources... [ 19%] c_api/surflock
#   reading sources... [ 20%] c_api/version
#   reading sources... [ 22%] filepaths
#   reading sources... [ 23%] index
#   reading sources... [ 25%] ref/bufferproxy
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.coverage (2.2.0) from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   ext.indexer (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/indexer.py
#   ext.headers (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/headers.py
#   ext.boilerplate (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/boilerplate.py
#   ext.customversion (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/customversion.py
#   ext.edit_on_github (unknown version) from /Users/ptr/xfolder/on-reading/pygame-master/docs/reST/ext/edit_on_github.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/io.py", line 114, in read
    self.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/domains/__init__.py", line 265, in run
    return super().run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/directives/__init__.py", line 195, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2346, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2376, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2649, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sphinx/domains/changeset.py", line 84, in run
    classes = ['versionmodified', versionlabel_classes[self.name]]
KeyError: 'versionextended'

**Comment by charlesej** [comment]
I edited your output to enclose it in a code fence (```) to make it more readable.

To generate the docs execute `python setup.py docs` in the python base directory. See [Generating docs](https://www.pygame.org/wiki/Hacking#Generating%20docs).

I currently use Sphinx v1.8.5 (I had some formatting issues when using Sphinx version 2 to generate the pygame docs).

**Comment by noisnemid** [comment]
Thank you very much for telling me the right way to generate the docs, which helps so much.
You could close this issue then.
Thank you!!!

**Comment by dlon** [comment]
It looks like there may be an incompatibility between ext.customversion and newer versions of Sphinx.

**Comment by charlesej** [comment]
To get this working with the newer versions of Sphinx some minor changes need to be made to `docs/reST/ext/customversion.py`.

`versionlabel_classes` needs to be imported (added to current import statement).
```python
from sphinx.domains.changeset import versionlabels, versionlabel_classes, VersionChange
```

`versionlabel_classes` also needs to be set in the `setup()` function (where `versionlabels` is being set).
```python
versionlabel_classes['versionextended'] = 'extended'
```

---

Note: Using the newer versions of Sphinx (v2+) to build the pygame docs results in strange formatting for bulleted lists (The text appears on the line after the bullet indicator).
