### ISSUE TITLE
ARM, and Big endian testing

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1291]
We don't do testing on PRs for Big endian or ARM CPUs.

There's some docker images which use qemu emulation, which (hopefully) make this fairly easy. See this comment: https://github.com/travis-ci/travis-ci/issues/8869#issuecomment-528986808

**Comment by illume** [comment]
armv8 is building on travis CI as part of this PR: https://github.com/pygame/pygame/pull/1717

**Comment by illume** [comment]
Apparently the s390x architecture on travis CI is big endian: 
- https://docs.travis-ci.com/user/multi-cpu-architectures/ 
- https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by illume** [comment]
The travis ci s390x has been added now too. 

These ones are failing:

- [ ] aapolygon(surface, points, color): return None ... FAIL
- [ ] test_frombuffer_BGR (pygame.tests.image_test.ImageModuleTest) ... FAIL
- [ ] test_frombuffer_RGB (pygame.tests.image_test.ImageModuleTest) ... FAIL

```
FAIL: test_aapolygon (pygame.tests.gfxdraw_test.GfxdrawDefaultTest)
aapolygon(surface, points, color): return None
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pygame-2.0.0.dev11-py3.7-linux-s390x.egg/pygame/tests/gfxdraw_test.py", line 723, in test_aapolygon
    self.check_at(surf, posn, fg_adjusted)
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pygame-2.0.0.dev11-py3.7-linux-s390x.egg/pygame/tests/gfxdraw_test.py", line 57, in check_at
    self.assertEqual(sc, color, fail_msg)
AssertionError: (8, 64, 128, 255) != (128, 64, 8, 255) : (8, 64, 128, 255) != (128, 64, 8, 255) at (10, 15), bitsize: 24, flags: 0, masks: (255, 65280, 16711680, 0)
```


```
FAIL: test_frombuffer_BGR (pygame.tests.image_test.ImageModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pygame-2.0.0.dev11-py3.7-linux-s390x.egg/pygame/tests/image_test.py", line 608, in test_frombuffer_BGR
    self.assertEqual(bgr_surf.get_at((0, 0)), pygame.Color(255, 10, 20))
AssertionError: (20, 10, 255, 255) != (255, 10, 20, 255)

======================================================================
FAIL: test_frombuffer_RGB (pygame.tests.image_test.ImageModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pygame-2.0.0.dev11-py3.7-linux-s390x.egg/pygame/tests/image_test.py", line 581, in test_frombuffer_RGB
    self.assertEqual(rgb_surf.get_at((0, 0)), pygame.Color(255, 10, 20))
AssertionError: (20, 10, 255, 255) != (255, 10, 20, 255)
```

**Comment by mgorny** [comment]
What a coincidence, I just wanted to report big endian failures ;-).

**Comment by MyreMylar** [comment]
I think the frombuffer one should be fairly easy to fix, if I recall there was some commented out code in there relating to endianness.

**Comment by mgorny** [comment]
I'll submit a PR in 2 minutes ;-).
