### ISSUE TITLE
Build from source fails if you don't have requests installed on windows

### ISSUE THREAD

**Issue by MightyJosip** [pygame/pygame#1391]
If you try to install pygame from source and you don't have [requests](https://pypi.org/project/requests/) package installed you get following error:

> Traceback (most recent call last):
  File "C:\pygame\setup.py", line 258, in <module>
    buildconfig.config.main(AUTO_CONFIG)
  File "C:\pygame\buildconfig\config.py", line 222, in main
    deps = CFG.main(**kwds)
  File "C:\pygame\buildconfig\config_win.py", line 575, in main
    and download_win_prebuilt.ask(**download_kwargs):
  File "C:\pygame\buildconfig\download_win_prebuilt.py", line 275, in ask
    update(x86=x86, x64=x64, sdl2=sdl2)
  File "C:\pygame\buildconfig\download_win_prebuilt.py", line 257, in update
    download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
  File "C:\pygame\buildconfig\download_win_prebuilt.py", line 106, in download_prebuilts
    download_sha1_unzip(url, checksum, temp_dir, 1)
  File "C:\pygame\buildconfig\download_win_prebuilt.py", line 22, in download_sha1_unzip
    import requests
ModuleNotFoundError: No module named 'requests'

Once I installed requests the program worked normally

OS: Windows 10
Python: Python 3.7.4
Pygame: pygame 2.0.0.dev4 (SDL 2.0.10)

**Comment by s0lst1ce** [comment]
Should `requests` be added to `requirements.txt` then? Newb here, just asking to learn if the issue is superficial or deeper.

**Comment by illume** [comment]
Hi @s0lst1ce . Usually that's what you'd do yes.

However, we probably want people to set things up without having to install requests. Since that makes things slightly easier to get started for people.
