### ISSUE TITLE
test_aapolygon fails on s390x (big-endian)

### ISSUE THREAD

**Issue by stefanor** [pygame/pygame#1548]
In pygame master (47f8d169bb6ca076f63c43393e1e96709f334bf1), under SDL2, we see this test failure on s390x:

```
======================================================================
FAIL: test_aapolygon (pygame.tests.gfxdraw_test.GfxdrawDefaultTest)
aapolygon(surface, points, color): return None
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefanor/pygame-1.9.6+dfsg/.pybuild/cpython2_2.7_pygame/build/pygame/tests/gfxdraw_test.py", line 672, in test_aapolygon
    self.check_at(surf, posn, fg_adjusted)
  File "/home/stefanor/pygame-1.9.6+dfsg/.pybuild/cpython2_2.7_pygame/build/pygame/tests/gfxdraw_test.py", line 49, in check_at
    self.assertEqual(sc, color, fail_msg)
AssertionError: (8, 64, 128, 255) != (128, 64, 8, 255) at (10, 15), bitsize: 24, flags: 0, masks: (255, 65280, 16711680, 0)
```

I can't see any obvious casting mistakes (the usual big endian issue), the aapolygoncolor function looks much like the other functions around it, that aren't causing test failures. So this could be an SDL bug, or I could be missing something obvious...

Let me know if you want me to test anything.

**Comment by illume** [comment]
This is for pygame 1.9.6. That's not supported using SDL2.
