### ISSUE TITLE
Compilation fails in Windows 10 and with Visual Studio 2019

### ISSUE THREAD

**Issue by jtiai** [pygame/pygame#1582]
When trying to compile with VS 2019 in Windows following error is generated:

```
Traceback (most recent call last):
  File "C:\Users\jtiai\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jtiai\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jtiai\projects\pygame\buildconfig\__main__.py", line 2, in <module>
    main()
  File "C:\Users\jtiai\projects\pygame\buildconfig\config.py", line 208, in main
    deps = CFG.main(**kwds)
  File "C:\Users\jtiai\projects\pygame\buildconfig\config_win.py", line 574, in main
    return setup_prebuilt_sdl2(prebuilt_dir)
  File "C:\Users\jtiai\projects\pygame\buildconfig\config_win.py", line 499, in setup_prebuilt_sdl2
    DEPS.configure()
  File "C:\Users\jtiai\projects\pygame\buildconfig\config_win.py", line 336, in configure
    from . import vstools
  File "C:\Users\jtiai\projects\pygame\buildconfig\vstools.py", line 11, in <module>
    compiler.initialize()
  File "C:\Users\jtiai\AppData\Local\Programs\Python\Python38-32\lib\distutils\msvc9compiler.py", line 372, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Users\jtiai\AppData\Local\Programs\Python\Python38-32\lib\distutils\msvc9compiler.py", line 261, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
```

Note that Microsoft has changed libraries being independent from VS version.

I can compile other C-language modules for Python just fine.

**Comment by jtiai** [comment]
I was using Python 3.8.0
Upgrade to Python 3.8.1 fixed this issue.
