### ISSUE TITLE
Pygame unable to set hw parameters when using bluealsa

### ISSUE THREAD

**Issue by TROFER** [pygame/pygame#1620]
I am encountering an issue when trying to initalise pygame.mixer when connected to a bluetooth device using bluealsa apon which it will normaly throw the following error:

```pygame.error: Couldn't set hardware audio parameters: Success``` 

This error wont always appear however and the program will just lockup.
Folowing this any other applications such as aplay or mpd no longer work and the device has to be restarted to fix, other applications work fine.

Thanks in advance.

**Comment by hackercyclops12** [comment]
Check if your Bluetooth frequency is 
Suitible for what you require your hardware to do?

**Comment by hackercyclops12** [comment]
If yes does your Bluetooth device have the correct driver?

**Comment by TROFER** [comment]
Thanks for your reply

Where would I find such information? I'm using the Pi's buletoorh module.

**Comment by TROFER** [comment]
I have just tested out some diffrent parameters in the init() on first try the program will freeze and ctl+c doesnt have any effect, On the seccond try it will produce the hw parameters error, I have tried frequency values between 20,000 - 44,000 which has had no effect.

**Comment by robertpfeiffer** [comment]
Can you tell us which version of python, pygame, and SDL your are using?

**Comment by TROFER** [comment]
Thanks for your response.

I am using python version 3.8.1 and pygame version 1.9.6
I'm not quite sure what an SDL is but I am using bluealsa + alsa for bluetooth comunication if thats what you need.

Thanks

**Comment by hackercyclops12** [comment]
Is Bluealsa up to date? And or suitable with said Bluetooth device?

**Comment by TROFER** [comment]
Yes, I only installed it yesterday and its on the latest version. I have
tested the problem on two different speakers and it hasn't had any effect

**Comment by hackercyclops12** [comment]
That's very interesting @TROFER I will look even more deeply into this, but please give me some time To develop an answer to your query.

Thanks in advance :)

**Comment by TROFER** [comment]
OK, thanks

**Comment by MightyJosip** [comment]
Can you try to install pygame2 with `pip install pygame==2.0.0.dev6` and then run your program

**Comment by TROFER** [comment]
OK I will give it a try, should I use pip3 as pip installs to python 2?

**Comment by hackercyclops12** [comment]
In case you were wondering this is an 
SDL ( I would recommend looking into this )

**Comment by hackercyclops12** [comment]
https://en.m.wikipedia.org/wiki/Simple_DirectMedia_Layer

**Comment by hackercyclops12** [comment]
I would recommend pip3 due to better compatability

**Comment by hackercyclops12** [comment]
I did some quick research I believe your program / project requires the hardware paramaters specified in some way shape or form but that's when it becomes complicated

**Comment by hackercyclops12** [comment]
This means it needs to be specified within the program*

**Comment by TROFER** [comment]
Ok, I just tested it again running pygame 2 and it no longer crashes and no longer produces an error ending the script instantly.

It might need some parameters but im not sure what they could be.

**Comment by hackercyclops12** [comment]
I will continue to look into said parameters and will notify you when I discover something meaningful.

**Comment by TROFER** [comment]
Ok, thats great. Now that trying out new parameters doesnt require a restart every time I will experement some more.

**Comment by TROFER** [comment]
I managed to find the SDL version you asked for:
```SDL 2.0.9```

**Comment by hackercyclops12** [comment]
The newest version of SDL is 2.0.12

**Comment by TROFER** [comment]
Is it able to be updated via apt or is there some other method?

**Comment by hackercyclops12** [comment]
Oh that's fine then that means SDL must be the correct version for you hardware

**Comment by TROFER** [comment]
Is there any news?

**Comment by hackercyclops12** [comment]
No nothing really, but the answer my investigation is pointing towards is that it is either 

1. hardware incompatibility e.g Bluetooth Receiver/transmitter different frequency ( = communication failure such as unable to set HW parameters)
2. some form of software incompatibility? ( 2 different versions of program/application installed?)
3. physical environment manipulation of correct signal such as:

- high amounts of metal object in the area

- distance to far?

**Comment by illume** [comment]
Building from source is probably your best chance. http://www.pygame.org/wiki/CompileUbuntu

**Comment by TROFER** [comment]
Thanks again for your responses, I will try to build it from source and let your know of the results

**Comment by hackercyclops12** [comment]
No problem, Hope it goes well!

**Comment by hackercyclops12** [comment]
Any news?

**Comment by TROFER** [comment]
Not yet I unfortunately haven't had a lot of spare time to test it out but
I plan to get it done this evening.

**Comment by hackercyclops12** [comment]
No worries take your time, stay home, stay safe, stay healthy.👍

**Comment by TROFER** [comment]
Ive just finished building pygame from source and unfortunatly it hasnt had any effect. Althought the error has changed a little:
`` pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "blt.py", line 4, in <module>
    pygame.mixer.init(28000, 16, 1, allowedchanges=0)
pygame.error: Couldn't set hardware audio parameters: Operation not permitted
``

**Comment by TROFER** [comment]
Ok so theres more, when running as user, it will provide more information 
```pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib bluealsa-pcm.c:763:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA PCM: Rejected send message, 1 matched rules; type="method_call", sender=":1.20" (uid=1000 pid=1388 comm="python3.8 blt.py ") interface="org.bluealsa.Manager1" member="GetPCMs" error name="(unset)" requested_reply="0" destination="org.bluealsa" (uid=0 pid=554 comm="/usr/bin/bluealsa ")
```

**Comment by hackercyclops12** [comment]
Sadly I believe that change has made us take a step backwards


**first comment showing first error message**

```
Pygame.error: couldn't set hardware audio paramaters: success 
```

It's this part at the end here....

```
: success
```

Which is a difference from

```
:Operation not permitted
```

Any permissions setting on you device that could be changed to our advantage?

**if not**

We need a command to help us permit this specified operation

**Comment by TROFER** [comment]
I don't really think so I've always been running the test scripts from root
so permissions shouldn't be a problem.

Is it possible this issue could be related to pygame needing to access some
other file?

**Comment by hackercyclops12** [comment]
Possibly I didn't think of it from that pespective I'll look into this

**Comment by hackercyclops12** [comment]
**Using Bluealsa have you set default volume and hardware paramaters **



_**helpful links **_

[https://www.raspberrypi.org/forums/viewtopic.php?t=247334]()

[https://www.raspberrypi.org/forums/viewtopic.php?t=169353]()

**Comment by hackercyclops12** [comment]
Do you have the correct version of bluealsa associated with your hardware?
**this could be the answer why it's changing that specific error mentioned in the past**

However if you believe your version of bluealsa associated is correct with you're hardware you should try reinstalling bluealsa?

**Comment by TROFER** [comment]
Sorry for the late reply,

I will check that bluealsa is initialised properly, that might be
effecting something because I don't remember setting the frequency etc.
I will also check the bluealsa version to see if its correct, I should be
able to give you an answer by this evening.

Thanks, Tristan

**Comment by TROFER** [comment]
Ok, So Ive taken a look at the Raspbery Pi forums post you sent as such I reconfigured ``asound.conf`` in line with the suggestions and it now looks like this:

```pcm.bluetooth {
    type plug
    slave.pcm {
        type bluealsa
        device "00:11:67:11:14:7A"
        profile "a2dp"
    }
    hint {
        show on
        description "Bluetooth Module"
    }
}

pcm.!default {
    type plug
    slave.pcm "bluetooth"
}
```
The good news is aplay still works meaning the configuration is valid, however Pi Game still ends the test script producing an error or most of the time nothing at all.

```
import pygame

pygame.mixer.init()
pygame.mixer.get_init()
pygame.mixer.music.load('test.wav')
pygame.mixer.music.play()
pygame.mixer.quit()
```
The error:
```
pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "blt.py", line 3, in <module>
    pygame.mixer.init()
pygame.error: Couldn't set hardware audio parameters: Operation not permitted
```
Test Example, aplay will play the track fine whilst pygame finishes instantly
```
root@traspi:/home# aplay test.wav
Playing WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
^CAborted by signal Interrupt...
aplay: pcm_write:2053: write error: Interrupted system call
root@traspi:/home# python3.8 blt.py
pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
root@traspi:/home# python3.8 blt.py
pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
root@traspi:/home# python3.8 blt.py
pygame 2.0.0.dev7 (SDL 2.0.9, python 3.8.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
root@traspi:/home# aplay test.wav
Playing WAVE 'test.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
^CAborted by signal Interrupt...
aplay: pcm_write:2053: write error: Interrupted system call
```
I have also checked the bluealsa version installed which is ``1.4`` apt says this is the current version and I cant find another version it should be online

**Comment by hackercyclops12** [comment]
Sorry for a horrifying late reply I think we need to work on asound.conf file 
Take a look at the errors is there a way you could modify the file to fix that error

For example to permit requested operation?

I'll come back to you with more info in a short while :)
