### ISSUE TITLE
Error no "MIDIIN" attribute when running `test`.

### ISSUE THREAD

**Issue by BenchHPZ** [pygame/pygame#2043]
Since pip where cause a lot of problems with dependencies, I install __pygame__ using 
> apt-get install python3-pygame

and then I try to run the `test` module to verify that everything went well, Since `test` is not in the apt package, I used the one from the Github repository and I get the following _output_

```Linux Kernel Module
user@ubuntu:/usr/lib/python3/dist-packages/pygame$ python3 -m pygame.test
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
skipping test.cdrom_test (tag 'interactive')Error runing 'test' 
skipping test.touch_test (tag 'SDL1_ignore')
loading test.base_test
loading test.blit_test
loading test.bufferproxy_test
loading test.camera_test
loading test.color_test
loading test.compat_test
loading test.constants_test
loading test.cursors_test
loading test.display_testError runing 'test' 
loading test.draw_test
loading test.event_test
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pygame/test/__main__.py", line 144, in <module>
    run_and_exit(*args, **kwds)
  File "/usr/lib/python3/dist-packages/pygame/test/test_utils/run_tests.py", line 352, in run_and_exit
    total, fails = run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pygame/test/test_utils/run_tests.py", line 228, in run
    results.update(run_test(module, **options))
  File "/usr/lib/python3/dist-packages/pygame/test/test_utils/test_runner.py", line 285, in run_test
    suite.addTest(loader.loadTestsFromName(module))
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/usr/lib/python3/dist-packages/pygame/test/event_test.py", line 53, in <module>
    ("MidiIn", pygame.MIDIIN),
AttributeError: module 'pygame' has no attribute 'MIDIIN'
```

I checked in the [documentation](https://www.pygame.org/docs/ref/event.html) that the `MIDIIN` attribute should be declared in the _midi_ module and its there, at the `midi.py` file.

```python
import pygame
import pygame.locals

#
MIDIIN = pygame.locals.USEREVENT + 10
MIDIOUT = pygame.locals.USEREVENT + 11

_init = False
_pypm = None
```

**Comment by MightyJosip** [comment]
You are using pygame 1.9.6 with the tests for pygame2. The version you are using was published 15 months ago, and midi events were added 11 months ago in https://github.com/pygame/pygame/pull/1295. If you want this tests to pass you should install one of the pygame 2 versions either with pip (`pip install pygame==2.0.0.dev10`) or by building from source (https://www.pygame.org/wiki/GettingStarted#Installing%20From%20Source)
