### ISSUE TITLE
timedelta failing on VMs like used on mac Travis release build

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2109]
time delta based tests in time_test.py are failing on VMs like Travis CI Mac.

- [x] skip tests on Travis Mac builds
- [x] look at skipping on all CI builds, and reducing the time delta to acceptable ranges for user interactive systems.

Here are the failures: https://travis-ci.org/github/pygame/pygame/builds/728629710#L18075
```
======================================================================
FAIL: test_get_fps (pygame.tests.time_test.ClockTypeTest)
test_get_fps tests pygame.time.get_fps()
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 25, in test_get_fps
    self._fps_test(c, 100, delta)
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 36, in _fps_test
    self.assertAlmostEqual(clock.get_fps(), fps, delta=fps*delta)

AssertionError: 12.195121765136719 != 100 within 30.0 delta

======================================================================
FAIL: test_get_rawtime (pygame.tests.time_test.ClockTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 55, in test_get_rawtime
    self.assertAlmostEqual(delay_miliseconds, c1, delta=delta)

AssertionError: 100.0 != 163 within 50 delta

======================================================================
FAIL: test_get_time (pygame.tests.time_test.ClockTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 82, in test_get_time
    self.assertAlmostEqual(delay_miliseconds, c1, delta=delta)
AssertionError: 100.0 != 250 within 50 delta

======================================================================
FAIL: test_tick (pygame.tests.time_test.ClockTypeTest)
Tests time.Clock.tick()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 130, in test_tick
    self.assertAlmostEqual(average_time, milliseconds, delta=epsilon)
AssertionError: 39.97959183673469 != 5.0 within 1.5 delta

======================================================================
FAIL: test_wait (pygame.tests.time_test.TimeModuleTest)
Tests time.wait() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 293, in test_wait
    self._wait_delay_check(pygame.time.wait, millis, iterations, delta)
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2ayzmg3d/lib/python2.7/site-packages/pygame/tests/time_test.py", line 310, in _wait_delay_check
    self.assertAlmostEqual(wait_time, millis, delta=delta)
AssertionError: 220 != 100 within 50 delta
```

**Comment by illume** [comment]
Kind of think we should mark these tests as 'ok to fail' somehow on CI. They've been tweaked to pass on appveyor and travisci... but they fail on the mac build (because that's only run at release at the moment).

If we keep raising the numbers then, are the tests even testing anything? I guess they are sort of lose meaning. To make those functions acceptable on a real game, they should be fairly accurate. So the tests are not good tests for this. They do provide some value, in that the functions 'work', and they work at this fairly bad accuracy.

- adjust values down so they are useful on game systems, then skip on all CI
- just skip on Mac CI. (need to tag all these functions as 'timing' or something).
- allow failure of these functions somehow.

I think tagging them, and skipping them is the best course of action.

**Comment by ankith26** [comment]
#2188 probably fixes this, but that PR is a draft
