### ISSUE TITLE
Unable to build Pygame 2 on Windows with Python 3.9

### ISSUE THREAD

**Issue by jtiai** [pygame/pygame#2144]
Python 3.9 was released on 5th October.

Attempt to build fails with unable to find build tools. Few other C-extensions do compile without issues with Python 3.9 and build tools installed.

```
python -m buildconfig -sdl2
Using WINDOWS configuration...

WARNING:root:Using the SDL libraries in "prebuilt-x64".
Path for SDL: prebuilt-x64\SDL2-2.0.12
...Library directory for SDL: prebuilt-x64/SDL2-2.0.12/lib/x64
...Include directory for SDL: prebuilt-x64/SDL2-2.0.12/include
Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
Path for PORTMIDI: prebuilt-x64
...Library directory for PORTMIDI: prebuilt-x64/lib
...Include directory for PORTMIDI: prebuilt-x64/include
DLL for SDL2: prebuilt-x64/SDL2-2.0.12/lib/x64/SDL2.dll
DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
DLL for portmidi: prebuilt-x64/lib/portmidi.dll
Path for FREETYPE not found.
...Found include dir but no library dir in prebuilt-x64.
Path for PNG not found.
...Found include dir but no library dir in prebuilt-x64.
Path for JPEG not found.
...Found include dir but no library dir in prebuilt-x64.
DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll
Traceback (most recent call last):
  File "c:\users\jani\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jani\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jani\projects\pygame-clean\buildconfig\__main__.py", line 2, in <module>
    main()
  File "C:\Users\jani\projects\pygame-clean\buildconfig\config.py", line 221, in main
    deps = CFG.main(**kwds)
  File "C:\Users\jani\projects\pygame-clean\buildconfig\config_win.py", line 574, in main
    return setup_prebuilt_sdl2(prebuilt_dir)
  File "C:\Users\jani\projects\pygame-clean\buildconfig\config_win.py", line 499, in setup_prebuilt_sdl2
    DEPS.configure()
  File "C:\Users\jani\projects\pygame-clean\buildconfig\config_win.py", line 336, in configure
    from . import vstools
  File "C:\Users\jani\projects\pygame-clean\buildconfig\vstools.py", line 11, in <module>
    compiler.initialize()
  File "c:\users\jani\appdata\local\programs\python\python39\lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "c:\users\jani\appdata\local\programs\python\python39\lib\distutils\msvc9compiler.py", line 260, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
```

**Comment by ankith26** [comment]
I don’t know much of C compiler stuff. But all I know is that in this case, the installer is not finding a particular binary called vcvarsall.bat

It looks like you aldready have the sdl related dependencies installed, but make sure that you have Microsoft visual studio installed too.

**Comment by jtiai** [comment]
I do have C compiler installed and `vcvarsall.bat` and it's located. I've installed it as instructed in 
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build
````

Looks like it's mainly issue with distutils not finding them since I have other setuptools based C-extensions that do work without problems.

Also looks like actual build finds msvc but buildconfig doesn't.

**Comment by MyreMylar** [comment]
Yes, distutils is not always up to date with the latest location of the BuildTools. I believe you can probably figure out how to modify distutils to locate the latest location of the directory by following the link above and reading the last section - if you just want to get pygame compiling.

**Comment by jtiai** [comment]
Doing the following helps: open up proper developer command prompt from VS 2019, normal for 32bit Python and x64 for 64bit Python. 

```
set DISTUTILS_USE_SDK=1
set MSSdk=1
```

After setting those setuptools/distutils trusts that user know better and doesn't try to do any autodetection. Now config and build will work.

**Comment by MyreMylar** [comment]
I've also successfully rebuilt python with the addition of `set MSSdk=1` so I think this is safe to close.
