### ISSUE TITLE
python -m pygame.tests.__main__ fails on OSX 10.10.0

### ISSUE THREAD

**Issue by illume** [pygame/pygame#219]
Originally reported by: **Kenn Sebesta (Bitbucket: [kubark42](https://bitbucket.org/kubark42), GitHub: [kubark42](https://github.com/kubark42))**

----------------------------------------

Installed with ```brew install pygame```. 

Latest (v2.7.7) X11 from XQuartz.

```
======================================================================
FAIL: FontModuleTest.test_get_fonts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pygame/tests/font_test.py", line 67, in test_get_fonts
    self.failUnless(name.islower(), name)
AssertionError

======================================================================
FAIL: FontTypeTest.test_set_bold
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pygame/tests/font_test.py", line 254, in test_set_bold
    self.failIf(f.get_bold())
AssertionError: None

======================================================================
FAIL: FontTypeTest.test_set_italic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pygame/tests/font_test.py", line 266, in test_set_italic
    self.failIf(f.get_bold())
AssertionError: None

======================================================================
ERROR: SurfarrayModuleTest.test_make_surface
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pygame/tests/surfarray_test.py", line 488, in test_make_surface
    surf = pygame.surfarray.make_surface(self._make_src_array3d(dtype))
  File "/usr/local/lib/python2.7/site-packages/pygame/surfarray.py", line 243, in make_surface
    return numpysf.make_surface (array)
  File "/usr/local/lib/python2.7/site-packages/pygame/_numpysurfarray.py", line 368, in make_surface
    blit_array (surface, array)
  File "/usr/local/lib/python2.7/site-packages/pygame/_numpysurfarray.py", line 437, in blit_array
    surface.get_buffer ().write (data, 0)
IndexError: bytes to write exceed buffer size

----------------------------------------------------------------------
Ran 408 tests in 17.627s

FAILED (failures=3, errors=1)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/219

**Comment by MyreMylar** [comment]
This is referring to a six year old release of OSX - if these test aren't passing by now then they never will.

Recommend close.

**Comment by illume** [comment]
Indeed. Thanks.
