### ISSUE TITLE
Docs fail to build with Sphinx 3

### ISSUE THREAD

**Issue by stefanor** [pygame/pygame#2202]
First reported [in Debian with 3.1.1](https://bugs.debian.org/963639)

Reproduced on `master` today with 3.2.1:

```
$ python3 setup.py build_sphinx -v


WARNING, "buildconfig/Setup.SDL1.in" newer than "Setup",you might need to modify "Setup".
running build_sphinx
Running Sphinx v3.2.1
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 86 source files that are out of date
updating environment: [new config] 86 added, 0 changed, 0 removed
reading sources... [  1%] c_api
reading sources... [  2%] c_api/base
reading sources... [  3%] c_api/bufferproxy
reading sources... [  4%] c_api/cdrom
reading sources... [  5%] c_api/color
reading sources... [  6%] c_api/display
reading sources... [  8%] c_api/event
reading sources... [  9%] c_api/freetype
reading sources... [ 10%] c_api/mixer
reading sources... [ 11%] c_api/rect
reading sources... [ 12%] c_api/rwobject
reading sources... [ 13%] c_api/slots
reading sources... [ 15%] c_api/surface
reading sources... [ 16%] c_api/surflock
reading sources... [ 17%] c_api/version
reading sources... [ 18%] filepaths
reading sources... [ 19%] index
reading sources... [ 20%] ref/bufferproxy
/home/stefanor/git/pygame/docs/reST/c_api/base.rst:113: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 9]
  PyObject \*pgExc_BufferError
  ---------^
/home/stefanor/git/pygame/docs/reST/c_api/event.rst:25: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 12]
  pgEvent_Type
  ------------^
/home/stefanor/git/pygame/docs/reST/c_api/mixer.rst:31: WARNING: Error in declarator or parameters
Invalid C declaration: Expecting "," or ")" in parameters, got "\". [error at 27]
  int pgSound_Check(PyObject \*obj)
  ---------------------------^
/home/stefanor/git/pygame/docs/reST/c_api/mixer.rst:57: WARNING: Error in declarator or parameters
Invalid C declaration: Expecting "," or ")" in parameters, got "\". [error at 29]
  int pgChannel_Check(PyObject \*obj)
  -----------------------------^
/home/stefanor/git/pygame/docs/reST/c_api/mixer.rst:63: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 10]
  Mix_Chunk \*pgChannel_AsInt(PyObject \*x)
  ----------^
/home/stefanor/git/pygame/docs/reST/c_api/version.rst:24: WARNING: Error in declarator
If declarator-id with parameters (e.g., 'void f(int arg)'):
  Invalid C declaration: Expected identifier in nested name. [error at 13]
    PG_VERSIONNUM(MAJOR, MINOR, PATCH)
    -------------^
If parenthesis in noptr-declarator (e.g., 'void (*f(int arg))(double)'):
  Error in declarator or parameters
  Invalid C declaration: Expecting "(" in parameters. [error at 19]
    PG_VERSIONNUM(MAJOR, MINOR, PATCH)
    -------------------^

/home/stefanor/git/pygame/docs/reST/c_api/version.rst:28: WARNING: Error in declarator
If declarator-id with parameters (e.g., 'void f(int arg)'):
  Invalid C declaration: Expected identifier in nested name. [error at 18]
    PG_VERSION_ATLEAST(MAJOR, MINOR, PATCH)
    ------------------^
If parenthesis in noptr-declarator (e.g., 'void (*f(int arg))(double)'):
  Error in declarator or parameters
  Invalid C declaration: Expecting "(" in parameters. [error at 24]
    PG_VERSION_ATLEAST(MAJOR, MINOR, PATCH)
    ------------------------^


Traceback (most recent call last):
  File "/home/stefanor/git/pygame/docs/reST/ext/utils.py", line 28, in get_descname
    return names[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/stefanor/git/pygame/docs/reST/ext/indexer.py", line 67, in collect_document_info
    doctree.walkabout(CollectInfo(app, doctree))
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3/dist-packages/docutils/nodes.py", line 2008, in dispatch_departure
    return method(node)
  File "/home/stefanor/git/pygame/docs/reST/ext/indexer.py", line 140, in depart_desc
    self._add_descinfo(node, *self._pop())
  File "/home/stefanor/git/pygame/docs/reST/ext/indexer.py", line 159, in _add_descinfo
    entry = {'fullname': get_fullname(node),
  File "/home/stefanor/git/pygame/docs/reST/ext/utils.py", line 14, in get_fullname
    return get_descname(node)
  File "/home/stefanor/git/pygame/docs/reST/ext/utils.py", line 30, in get_descname
    raise GetError("No fullname: desc's child has empty names list")
ext.utils.GetError: No fullname: desc's child has empty names list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/setup_command.py", line 195, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 342, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3/dist-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3/dist-packages/sphinx/transforms/__init__.py", line 87, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3/dist-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3/dist-packages/sphinx/transforms/__init__.py", line 383, in apply
    self.app.emit('doctree-read', self.document)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 117, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function collect_document_info at 0x7f4fb53058b0> for event 'doctree-read' threw an exception (exception: No fullname: desc's child has empty names list)

Extension error:
Handler <function collect_document_info at 0x7f4fb53058b0> for event 'doctree-read' threw an exception (exception: No fullname: desc's child has empty names list)

---
For help with compilation see:
    https://www.pygame.org/wiki/Compilation
To contribute to pygame development see:
    https://www.pygame.org/contribute.html
---
```

**Comment by Starbuck5** [comment]
Related to #1298.

I managed to solve this locally a while ago, but I didn't commit because the docs still build incorrectly with Sphinx 3. (It doesn't crash, but the formatting is off). It's in reST/ext/utils.py. (I'll find the fix on my other computer).

I just need to test whether fixing this impacts how it builds on Sphinx 1.x, because that's the only version where the docs build correctly right now.

**Comment by stefanor** [comment]
> I'll find the fix on my other computer

Thanks, we'll find a patch useful, even if you can't land it in master and the formatting isn't perfect. And it saves me from having to figure out what's going on :)
