### ISSUE TITLE
Numerous test failures in dev20, apparently due to SSE4.2 removal

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#2232]
```
======================================================================
ERROR: imageext_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: imageext_test
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/imageext_test.py", line 8, in <module>
    import pygame, pygame.image, pygame.pkgdata
ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42


======================================================================
ERROR: test_palette_colorkey (pygame.tests.surface_test.GeneralSurfaceTests)
test bug discovered by robertpfeiffer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 2032, in test_palette_colorkey
    surf = pygame.image.load(example_path(os.path.join("data", "alien2.png")))
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_palette_colorkey_fill (pygame.tests.surface_test.GeneralSurfaceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 2043, in test_palette_colorkey_fill
    surf = pygame.image.load(example_path(os.path.join("data", "alien2.png")))
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_palette_colorkey_set_px (pygame.tests.surface_test.GeneralSurfaceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 2037, in test_palette_colorkey_set_px
    surf = pygame.image.load(example_path(os.path.join("data", "alien2.png")))
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_set_alpha__set_colorkey_rle (pygame.tests.surface_test.SurfaceTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 419, in test_set_alpha__set_colorkey_rle
    image = pygame.image.load(example_path(os.path.join("data",
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_set_at__big_endian (pygame.tests.surface_test.SurfaceTypeTest)
png files are loaded in big endian format (BGR rather than RGB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 111, in test_set_at__big_endian
    image = pygame.image.load(example_path(os.path.join("data", "BGR.png")))
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_solarwolf_rle_usage (pygame.tests.surface_test.SurfaceTypeTest)
Test for error/crash when calling set_colorkey() followed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 330, in test_solarwolf_rle_usage
    image = pygame.image.load(example_path(os.path.join("data",
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_solarwolf_rle_usage_2 (pygame.tests.surface_test.SurfaceTypeTest)
Test for RLE status after setting alpha
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/surface_test.py", line 352, in test_solarwolf_rle_usage_2
    image = pygame.image.load(example_path(os.path.join("data",
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_flip (pygame.tests.transform_test.TransformDisplayModuleTest)
honors the set_color key on the returned surface from flip.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/transform_test.py", line 1228, in test_flip
    image_loaded = pygame.image.load(fullname)
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_flip_alpha (pygame.tests.transform_test.TransformDisplayModuleTest)
returns a surface with the same properties as the input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/transform_test.py", line 1275, in test_flip_alpha
    image_loaded = pygame.image.load(fullname)
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_average_surfaces__24_big_endian (pygame.tests.transform_test.TransformModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/transform_test.py", line 874, in test_average_surfaces__24_big_endian
    surf_1 = pygame.image.load(
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_laplacian__24_big_endian (pygame.tests.transform_test.TransformModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/transform_test.py", line 785, in test_laplacian__24_big_endian
    surf_1 = pygame.image.load(
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

======================================================================
ERROR: test_renderer_set_viewport (pygame.tests.video_test.VideoModuleTest)
works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/tests/video_test.py", line 16, in test_renderer_set_viewport
    window = video.Window(title=self.default_caption, size=(800, 600))
  File "src_c/cython/pygame/_sdl2/video.pyx", line 280, in pygame._sdl2.video.Window.__init__
    surf = pygame.image.load(pygame.pkgdata.getResource(
  File "/tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: image module not available (ImportError: /tmp/portage/dev-python/pygame-2.0.0_pre20/work/pygame-2.0.0.dev20-python3_6/install/lib/pygame/image.cpython-36m-x86_64-linux-gnu.so: undefined symbol: tostring_surf_32bpp_sse42)

----------------------------------------------------------------------
Ran 1524 tests in 34.241s

FAILED (errors=13)

```

**Comment by illume** [comment]
I wasn't able to reproduce the issue on any of the test machines I have access to. Hopefully the merged PR #2233 fixes it.

**Comment by illume** [comment]
I hope this is working now.

**Comment by mgorny** [comment]
Yes, dev22 is good. I'm sorry, I've forgot to leave a comment after testing.
