### ISSUE TITLE
FileNotFoundError: No such file or Directory when the file is there

### ISSUE THREAD

**Issue by SeagullisLearningToCode** [pygame/pygame#2320]
I have done this before and it worked fine previously with other files similar to this one.
but I don't understand why I am getting this error. I tried running it on my other scripts
and it works fine even though running code that looks like this results in the traceback
below but when I run it from my main.py file it runs fine. But now its giving me this error

Jellys_PC.py
```Python
import pygame
import os
imgdir = os.path.dirname(os.path.abspath(__file__))
join = os.path.join
load = pygame.image.load
# JF_J | Jurassic | PC
jf_j = [join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-0.png"),
        join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-1.png"),
        join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-2.png"),
        join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-3.png"),
        join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-4.png"),
        join(imgdir, "dataE/dataIMG/PC/Pre-Jelly/", "0-5.png")]
jf_j_i = [load(jf_j[0]),
          load(jf_j[1]),
          load(jf_j[2]),
          load(jf_j[3]),
          load(jf_j[4]),
          load(jf_j[5])]
jf_j_dict = {0: jf_j_i[0],
             1: jf_j_i[1],
             2: jf_j_i[2],
             3: jf_j_i[3],
             4: jf_j_i[4],
             5: jf_j_i[5]}
# END OF JF_J
# JF_AT | Atlandtis | PC
jf_at = [pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-0.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-1.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-2.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-3.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-4.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-5.png"))]
jf_at_dict = {0: jf_at[0],
              1: jf_at[1],
              2: jf_at[2],
              3: jf_at[3],
              4: jf_at[4],
              5: jf_at[5]}
# END OF JF_AT
# JF_AR | Artic | PC
jf_ar = [pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-0.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-1.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-2.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-3.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-4.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-5.png"))]
jf_ar_dict = {0: jf_ar[0],
              1: jf_ar[1],
              2: jf_ar[2],
              3: jf_ar[3],
              4: jf_ar[4],
              5: jf_ar[5]}
# END OF JF_AR
# JF_VO | Vortex | PC
jf_vo = [pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-0.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-1.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-2.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-3.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-4.png")),
         pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "4-5.png"))]
jf_vo_dict = {0: jf_vo[0],
              1: jf_vo[1],
              2: jf_vo[2],
              3: jf_vo[3],
              4: jf_vo[4],
              5: jf_vo[5]}
# END OF JF_VO
# JF_N | Normal | PC
jf_n = [pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-0.png")),
        pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-1.png")),
        pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-2.png")),
        pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-3.png")),
        pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-4.png")),
        pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "0-5.png"))]
jf_n_dict = {0: jf_n[0],
             1: jf_n[1],
             2: jf_n[2],
             3: jf_n[3],
             4: jf_n[4],
             5: jf_n[5]}
# JF_N_D | Normal Deep Colors | PC
jf_n_d = [pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-0.png")),
          pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-1.png")),
          pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-2.png")),
          pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-3.png")),
          pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-4.png")),
          pygame.image.load(join(imgdir, "dataE/dataIMG/PC/Jelly/", "2-5.png"))]
jf_n_d_dict = {0: jf_n_d[0],
               1: jf_n_d[1],
               2: jf_n_d[2],
               3: jf_n_d[3],
               4: jf_n_d[4],
               5: jf_n_d[5]}
# END OF JF_N, JF_N_D
```

```
pygame 2.0.0 (SDL 2.0.12, python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/<user>/PycharmProjects/testgame/main.py", line 47, in <module>
    from dataE.dataSCR.NPC.Jellyfish.Jelly import *
  File "/Users/l<users>/PycharmProjects/testgame/dataE/dataSCR/NPC/Jellyfish/Jelly.py", line 21, in <module>
    from dataE.dataSCR.NPC.Jellyfish.Jellys_PC import *
  File "/Users/l<users>/PycharmProjects/testgame/dataE/dataSCR/NPC/Jellyfish/Jellys_PC.py", line 13, in <module>
    jf_j_i = [load(jf_j[0]),
FileNotFoundError: No such file or directory.
```

**Comment by SeagullisLearningToCode** [comment]
I somehow figured it out
