### ISSUE TITLE
Failing mixer module tests

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2364]
When running the unit tests locally on windows (Python 3.9 64 bit)  I get three failures:

```
.........s......F...FF..u.............
======================================================================
FAIL: test_init__keyword_args (__main__.MixerModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dan\Programming\pygame\test\mixer_test.py", line 66, in test_init__keyword_args
    self.assertEqual(mixer_conf[2], CONFIG["channels"])
AssertionError: 6 != 2

======================================================================
FAIL: test_pre_init__keyword_args (__main__.MixerModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dan\Programming\pygame\test\mixer_test.py", line 78, in test_pre_init__keyword_args
    self.assertEqual(mixer_conf[2], CONFIG["channels"])
AssertionError: 6 != 2

======================================================================
FAIL: test_pre_init__zero_values (__main__.MixerModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dan\Programming\pygame\test\mixer_test.py", line 86, in test_pre_init__zero_values
    self.assertEqual(mixer.get_init(), (44100, -16, 2))
AssertionError: Tuples differ: (44100, -16, 6) != (44100, -16, 2)

First differing element 2:
6
2

- (44100, -16, 6)
?              ^

+ (44100, -16, 2)
?              ^


----------------------------------------------------------------------
Ran 38 tests in 3.374s

FAILED (failures=3, skipped=1, unexpected successes=1)
```

Looks like setting the number of channels to 2 isn't working?

**Comment by illume** [comment]
Setting channels is a request. You can ask for 2, but get 6.

**Comment by MyreMylar** [comment]
Ah, sounds like this test needs some altering to use `assertGreaterEqual()` then. I'll do a quick PR.
