### ISSUE TITLE
2 new test failures, in main branch

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2412]
Just testing out stuff today, and ran unit tests after compiling pygame from main branch, got 2 new failures

Raspberry Pi Os (Buster)
```
pygame 2.0.1.dev1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html

...

======================================================================
ERROR: test_gl_get_attribute (pygame.tests.display_test.DisplayModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pygame-2.0.1.dev1-py3.7-linux-armv7l.egg/pygame/tests/display_test.py", line 254, in test_gl_get_attribute
    original_values.append(pygame.display.gl_get_attribute(pygame.GL_STENCIL_SIZE))
pygame.error: OpenGL error: 00000502

======================================================================
FAIL: test_garbage_collection (pygame.tests.freetype_test.FreeTypeFontTest)
Check reference counting on returned new references
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pygame-2.0.1.dev1-py3.7-linux-armv7l.egg/pygame/tests/freetype_test.py", line 1655, in test_garbage_collection
    self.assertEqual(getrefcount(item), 2, "refcount fail for item %d" % i)
AssertionError: 4 != 2 : refcount fail for item 0
```

**Comment by ankith26** [comment]
Added critical label, because this could potentially be a show stopper for a pygame 2.0.1-dev2 release

**Comment by zoldalma999** [comment]
The refcounting one is also reported here: #859

**Comment by illume** [comment]
I'm going to skip the OpenGL test (for now), and bisect the font ref count one a bit.

**Comment by ankith26** [comment]
Either way, I don’t think these failures are so bad that they need the critical label, so we can’t probably remove that one off

**Comment by illume** [comment]
Closing this one for now, and will figure out the refcount issue in #859
