### ISSUE TITLE
mixer.init not honoring channels input for windows10 pro

### ISSUE THREAD

**Issue by spacether** [pygame/pygame#2417]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows10Pro
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.7 
- **SDL version** (e.g. SDL 2.0.12): 2.0.12
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.0
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): 64bit

**Current behavior:**
When initializing the audio mixer as mono and attempting to make a sound with it, the mixer used stereo channels (2) and fails

Describe how the bug manifests.
I get this error:
```
1
Traceback (most recent call last):
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\sndarray.py", line 94, in make_sound
    return numpysnd.make_sound(array)
AttributeError: 'NoneType' object has no attribute 'make_sound'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mixer_test.py", line 15, in <module>
    pg_sound = pygame.sndarray.make_sound(sound)
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\sndarray.py", line 97, in make_sound
    return numpysnd.make_sound(array)
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\_numpysndarray.py", line 74, in make_sound
    return mixer.Sound(array=array)
ValueError: Array must be 2-dimensional for stereo mixer
```
When I run this code with a mono wav file
```
import pygame
import librosa

sound, framerate_hz = librosa.load('piano_c4.wav')
sound_shape = sound.shape
if len(sound_shape) == 1:
    channels = 1
else:
    channels = sound_shape[1]
print(channels)

BITS_32BIT = 32
pygame.mixer.init(framerate_hz, BITS_32BIT, channels)
pg_sound = pygame.sndarray.make_sound(sound)
```

**Expected behavior:**

I expect to be able to make a sound with the mono input data

**Screenshots**

N/A

**Steps to reproduce:**

1. Download the attached wav file
2. Run my code sample on windows10 64-bit on python 3.8 with the wav file adjacent to the python program

**Test code**

```
import pygame
import librosa

sound, framerate_hz = librosa.load('piano_c4.wav')
sound_shape = sound.shape
if len(sound_shape) == 1:
    channels = 1
else:
    channels = sound_shape[1]
print(channels)

BITS_32BIT = 32
pygame.mixer.init(framerate_hz, BITS_32BIT, channels)
pg_sound = pygame.sndarray.make_sound(sound)
```

**Stack trace/error output/other error logs**

```
1
Traceback (most recent call last):
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\sndarray.py", line 94, in make_sound
    return numpysnd.make_sound(array)
AttributeError: 'NoneType' object has no attribute 'make_sound'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mixer_test.py", line 15, in <module>
    pg_sound = pygame.sndarray.make_sound(sound)
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\sndarray.py", line 97, in make_sound
    return numpysnd.make_sound(array)
  File "C:\Users\Justin\Documents\programming\pianoputer\venv\lib\site-packages\pygame\_numpysndarray.py", line 74, in make_sound
    return mixer.Sound(array=array)
ValueError: Array must be 2-dimensional for stereo mixer
```

[piano_c4.zip](https://github.com/pygame/pygame/files/5736581/piano_c4.zip)

**Comment by spacether** [comment]
With further investigation I got it working by passing in the allowedchanges argument:
```
# works with allowedchanges =
# 0 (hardware determined)
# AUDIO_ALLOW_FORMAT_CHANGE == 2
# AUDIO_ALLOW_FREQUENCY_CHANGE == 1
pygame.mixer.init(framerate_hz, BITS_32BIT, channels, allowedchanges=0)

```
