### ISSUE TITLE
Python 3.10 support (beta is out)

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2599]
There's already been some patches to get it compiling/passing tests: https://github.com/pygame/pygame/pull/2586

Remaining work:

- [ ] unit tests pass on each platform
- [ ] example apps work on each platform (examples/ and things like solarwolf)
- [ ] check the whatsnew/migration guide (Any new features we could use?) look at other projects
- [ ] tested in CI
- [ ] windows wheels
- [ ] mac wheel(s)
- [ ] manylinux wheels

**Comment by RayDawn** [comment]
Can't seem to get it to build properly locally in 3.10 beta 2 (on mac). Control checked by building locally with 3.9 and it has no problem, so it shouldn't be a hardware issue. I'm not technically apt enough myself to troubleshoot these issues, but it seems like pygame is still incompatible with the 3.10 betas.

**Comment by Starbuck5** [comment]
@RayDawn were you using the up to date version from Github?

Also, I'd appreciate the error message if it still fails to build.

**Comment by ankith26** [comment]
Oops, looks like I clicked some button on accident and I modified the original comment. But I have reverted my accidental change and it is back to how it was before now 😅

**Comment by Starbuck5** [comment]
It looks like github actions supports 3.10 (rc1), getting that set up would help with a lot of items on the list. https://github.com/actions/python-versions/releases

**Comment by dimaqq** [comment]
3.10 is out, chop-chop 😆

**Comment by dr-devpro** [comment]
How about MAC version

**Comment by Starbuck5** [comment]
@dimaqq @dr-devpro Now that pygame 2.0.2 is out, it's as simple as `pip install pygame`.

**Comment by ankith26** [comment]
The mac builds have been fixed, the latest pygame version 2.0.2 has wheels (binary distributions) that have self contained dependencies (like SDL) of latest versions. So installing the latest pygame version should not be a problem on mac at all, now (if it is, post a new issue with the full error message and any other debug info about your system!)

**Comment by illume** [comment]
We didn't actually make manylinux builds for python 3.10 in the end. Oops. Even though the new images should have python 3.10 in there, we didn't do it yet.

**Comment by gsilvers** [comment]
Mac pip still seems to be busted:

`ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/setup.py'"'"'; __file__='"'"'/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-pip-egg-info-rt95uglh
       cwd: /private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/
  Complete output (27 lines):
  
  
  WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
  Using Darwin configuration...
  
  /bin/sh: sdl2-config: command not found
  /bin/sh: sdl2-config: command not found
  /bin/sh: sdl2-config: command not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/setup.py", line 318, in <module>
      buildconfig.config.main(AUTO_CONFIG)
    File "/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/buildconfig/config.py", line 221, in main
      deps = CFG.main(**kwds)
    File "/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/buildconfig/config_darwin.py", line 131, in main
      [DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl'])],
    File "/private/var/folders/s3/bkw42qts7pxf74914g_nwqq80000gn/T/pip-install-ytrb8tsr/pygame_12c23ce582ac4438b27501df06a3ff30/buildconfig/config_unix.py", line 39, in __init__
      self.ver = config[0].strip()
  IndexError: list index out of range
  
  ---`

**Comment by gsilvers** [comment]
Yea something very wrong with the wheels still if I install sdl manually its found and install completes.

**Comment by ankith26** [comment]
Do you use an Apple M1 mac? We do not have wheels for those yet, so that would explain why pip is trying to build pygame from source for you. This will be fixed in a future pygame version, DW

**Comment by ankith26** [comment]
Well arm64 mac wheels are a separate issue unrelated to 3.10 support. Yes it's a build issue that we don't generate `universal2` binaries yet, but that is in the TODO! I am working on a draft PR for that
