### ISSUE TITLE
Segmentation Fault on display re-init using pygame.SCALED on KMSDRM

### ISSUE THREAD

**Issue by rtomasa** [pygame/pygame#2660]
**Environment:**

- **Operating system**: Raspbian Buster
- **Python version**: 3.7.3
- **SDL version**: 2.0.10
- **PyGame version**: 2.0.1
- **Relevant hardware**: Raspberry Pi4 (using KMSDRM driver)

**Current behavior:**

When using the SCALED flag in `pygame.display.set_mode` and later on you try to deinit the display and init the same again, a segmentation fault is raised.
Display Quit/Init is required when using KMSDRM driver and you need to launch any external application that also uses KMS.

**Expected behavior:**

You should be able to init the display again without issues when using SCALED flag.

**Steps to reproduce:**

You can use the code snippet below to reproduce the issue.

**Test code**

```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)
pygame.display.quit()
pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)
```

**Stack trace/error output/other error logs**

```
Fatal Python error: (pygame parachute) Segmentation Fault
Current thread 0xb6c95ad0 (most recent call first):
  File "test.py", line 7 in <module>
Aborted
```
gdb extra info:
```
Program received signal SIGSEGV, Segmentation fault.
0xafff0534 in ?? ()
(gdb) bt
#0  0xafff0534 in ?? ()
#1  0xb6658bb8 in ?? () from /lib/arm-linux-gnueabihf/libSDL2-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by robertpfeiffer** [comment]
Thank you for tracking this down. I never thought this would be a use case when I wrote this. I'll assign myself to this bug

**Comment by rtomasa** [comment]
Thanks sir, and do not hesitate to contact me if you need any additional test case from my side.

**Comment by Kyuchumimo** [comment]
How have you managed to run Pygame 2.0.1 on Raspberry Pi OS?

I have dependency problems, it tells me that it is missing this: JPEG jpeglib.h libjpeg

**Comment by ankith26** [comment]
This is unrelated to the issue,  but you have to install deps on raspberry pi with this command `sudo apt install libasyncns0 libflac8 libfluidsynth1 libice6 libjack0 libjbig0 libmad0 libmodplug1 libogg0 libportmidi0 libpulse0 libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libsm6 libsndfile1 libsndio6.1 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3 libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa libwebp6 libx11-xcb1 libxcursor1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2 libxrender1 libxss1 libxtst6 libxxf86vm1` (copied from https://www.piwheels.org/project/pygame/)

**Comment by robertpfeiffer** [comment]
> This is unrelated to the issue, but you have to install deps on raspberry pi with this command `sudo apt install libasyncns0 libflac8 libfluidsynth1 libice6 libjack0 libjbig0 libmad0 libmodplug1 libogg0 libportmidi0 libpulse0 libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libsm6 libsndfile1 libsndio6.1 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3 libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa libwebp6 libx11-xcb1 libxcursor1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2 libxrender1 libxss1 libxtst6 libxxf86vm1` (copied from https://www.piwheels.org/project/pygame/)

This might not be enough to get KMSDRM to work on the Pi. You also need udev and/or evdev and KMSDRM development headers to compile SDL2 to run on the console.

**Comment by robertpfeiffer** [comment]
@rtomasa 
what if you run
```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)

del screen
pygame.display.quit()

pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)
```

or
```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)

pygame.display.quit()
del screen

pygame.display.init()
screen = pygame.display.set_mode((640, 480), pygame.SCALED)
```

**Comment by rtomasa** [comment]
Tested both and still getting segmentation fault when reinit display

**Comment by robertpfeiffer** [comment]
I think I found an unrelated memory leak. Can you compile/test a pygame branch?

**Comment by rtomasa** [comment]
Tell me which one you want me to test/compile and I'll try the same this night.

**Comment by robertpfeiffer** [comment]
I tried a bunch of stuff to narrow it down, and I did not narrow it down much. Still, this is good news:

The same behaviour is triggered with KMSDRM on x86 with PyGame 2.1.0 and with rpi backend on raspberry pi 3. You don't need ARM or Pi4 to reproduce this.

Still trying to wrap my head around this bug, but getting there...

**Comment by rtomasa** [comment]
Thanks a lot for continuing looking into this issue because SCALED is the only option feasible when using RPi since standard soft render has a terrible issue with animations and scrolls shuttering a lot but SCALED runs very smooth, even better than software render in 1.9.6

**Comment by rtomasa** [comment]
Today v2.3.0 was released. Any progress on this issue?

**Comment by amir-kt** [comment]
> 

Might be slightly unrelated but I was having issues running Pygame on an M1 mac inside a docker container with Xquartz and installing those packages solved the issue I was having where I was getting `segmentation fault` when I ran the container.
