### ISSUE TITLE
Windows builds failing to download prebuilts.

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2669]
Something is going wrong with the pygame website download of some prebuilt files for the Windows build process.

Windows build process documented on this page: https://www.pygame.org/wiki/CompileWindows, but the site is down this second :/

It's a bizarre problem; Ankith and I already tried to figure it out. Maybe this prebuilt download can be a thing of the past and solve this issue?

When I download the folder from the URL manually, and check the certificate, it works fine. But the automated version from requests doesn't work, and there's an error on download for the urllib backend.

Oh, and it's also making all appveyor CI fail. See this documentation change run fully failing before being canceled: https://ci.appveyor.com/project/pygame/pygame/builds/40350964

```
C:\Users\Starbuck\Desktop\pygame_repo\pygame>python -m buildconfig -sdl2 --download
Using WINDOWS configuration...

Making dir :prebuilt_downloads:
Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip 48d5dcd4a445410301f5575219cffb6de654edb8
Unzipping :prebuilt_downloads\SDL2-devel-2.0.14-VC.zip:
Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
Downloading... https://www.ijg.org/files/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
Unzipping :prebuilt_downloads\jpegsr9d.zip:
Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
Traceback (most recent call last):
  File "C:\Users\Starbuck\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Starbuck\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\__main__.py", line 2, in <module>
    main()
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\config.py", line 221, in main
    deps = CFG.main(**kwds)
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\config_win.py", line 559, in main
    and download_win_prebuilt.ask(**download_kwargs):
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\download_win_prebuilt.py", line 292, in ask
    update(x86=x86, x64=x64, sdl2=sdl2)
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\download_win_prebuilt.py", line 275, in update
    download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\download_win_prebuilt.py", line 124, in download_prebuilts
    download_sha1_unzip(url, checksum, temp_dir, 1)
  File "C:\Users\Starbuck\Desktop\pygame_repo\pygame\buildconfig\download_win_prebuilt.py", line 58, in download_sha1_unzip
    raise ValueError(
ValueError: url:https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip should have checksum:3a5af3427b3aa13a0aaf5c4cb08daaed341613ed: Has:31c9ed8c888c1dc2bf20294f57af2fe22b70b998:
```

**Comment by ankith26** [comment]
Ahh, this seems to be fixed now.. This was likely caused due to a random server error that happened, but now it works fine 🥳
