### ISSUE TITLE
pygame wont install

### ISSUE THREAD

**Issue by Manhunter1920** [pygame/pygame#2748]
Every time i try and download pygame, this is what i get:

C:\Users\----->python3 -m pip install pygame==2.0.2.dev2
Collecting pygame==2.0.2.dev2
  Downloading pygame-2.0.2.dev2.tar.gz (5.7 MB)
     |████████████████████████████████| 5.7 MB 1.3 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\-----\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\-----\\AppData\\Local\\Temp\\pip-install-85ltizv2\\pygame_5aecdc50663342dfbd64a44c04743912\\setup.py'"'"'; __file__='"'"'C:\\Users\\-----\\AppData\\Local\\Temp\\pip-install-85ltizv2\\pygame_5aecdc50663342dfbd64a44c04743912\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\-----\AppData\Local\Temp\pip-pip-egg-info-10n8kp0k'
         cwd: C:\Users\-----\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\
    Complete output (79 lines):

    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\-----\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\setup.py", line 322, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\-----\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\buildconfig\config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "C:\Users\-----\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\buildconfig\config_win.py", line 574, in main
        return setup_prebuilt_sdl2(prebuilt_dir)
      File "C:\Users\Silas\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\buildconfig\config_win.py", line 499, in setup_prebuilt_sdl2
        DEPS.configure()
      File "C:\Users\Silas\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\buildconfig\config_win.py", line 336, in configure
        from . import vstools
      File "C:\Users\Silas\AppData\Local\Temp\pip-install-85ltizv2\pygame_5aecdc50663342dfbd64a44c04743912\buildconfig\vstools.py", line 11, in <module>
        compiler.initialize()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.194.0_x64__qbz5n2kfra8p0\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.194.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.194.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 1740, in return_env
        [self.VCIncludes,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.194.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes
        return [join(self.si.VCInstallDir, 'Include'),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.194.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    Making dir :prebuilt_downloads:
    Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip 13d952c333f3c2ebe9b7bc0075b4ad2f784e7584
    Unzipping :prebuilt_downloads\SDL2-devel-2.0.16-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
    Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
    Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
    Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
    Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
    Downloading... https://www.ijg.org/files/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
    Unzipping :prebuilt_downloads\jpegsr9d.zip:
    Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
    Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
    copying into .\prebuilt-x64
    Path for SDL: prebuilt-x64\SDL2-2.0.16
    ...Library directory for SDL: prebuilt-x64/SDL2-2.0.16/lib/x64
    ...Include directory for SDL: prebuilt-x64/SDL2-2.0.16/include
    Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
    ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
    ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
    Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
    ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
    ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
    Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
    ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
    ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
    Path for PORTMIDI: prebuilt-x64
    ...Library directory for PORTMIDI: prebuilt-x64/lib
    ...Include directory for PORTMIDI: prebuilt-x64/include
    DLL for SDL2: prebuilt-x64/SDL2-2.0.16/lib/x64/SDL2.dll
    DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
    DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
    DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
    DLL for portmidi: prebuilt-x64/lib/portmidi.dll
    Path for FREETYPE not found.
    ...Found include dir but no library dir in prebuilt-x64.
    Path for PNG not found.
    ...Found include dir but no library dir in prebuilt-x64.
    Path for JPEG not found.
    ...Found include dir but no library dir in prebuilt-x64.
    DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a9/7c/d6d95935e801cf83566ee34b2f597a8214e340466b0364b4db5a2f05bc16/pygame-2.0.2.dev2.tar.gz#sha256=8d5ffc089075b68ca948a88c0678a9d6bf5fed69676fee221fb562f4a788611b (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pygame==2.0.2.dev2 (from versions: 1.9.2rc1, 1.9.2, 1.9.3, 1.9.4.dev0, 1.9.4rc1, 1.9.4, 1.9.5rc1, 1.9.5rc2, 1.9.5, 1.9.6rc1, 1.9.6rc2, 1.9.6, 2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0.0.dev6, 2.0.0.dev8, 2.0.0.dev10, 2.0.0.dev12, 2.0.0.dev14, 2.0.0.dev16, 2.0.0.dev18, 2.0.0.dev20, 2.0.0.dev22, 2.0.0.dev24, 2.0.0, 2.0.1.dev1, 2.0.1, 2.0.2.dev2)
ERROR: No matching distribution found for pygame==2.0.2.dev2

i've tried different versions, commands, etc and nothing works.

i need help

**Comment by rethanon** [comment]
Looks like you're using Python 3.10 which was only released yesterday, pygame is in the process of being updated to support it.

**Comment by Starbuck5** [comment]
You can download this below and install directly from the .whl file to get python 3.10 support for pygame.

Pygame works on 3.10, it just doesn't have wheels out in the world for it yet.

[pygame-310-wheel.zip](https://github.com/pygame/pygame/files/7289451/pygame-310-wheel.zip)

**Comment by Starbuck5** [comment]
I'm going to close this in favor of keeping 3.10 discussion in #2599
