### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED when running setup.py

### ISSUE THREAD

**Issue by Rabbid76** [pygame/pygame#2976]
It tried [Building From Source](https://github.com/pygame/pygame#building-from-source). Unfortunately I got `CERTIFICATE_VERIFY_FAILED` when running _setup.py_.

I'm using Python 3.9.5 (maybe I should update) and checked out the last 'main'.

```lang-none
PS C:\source\python\pygame> python setup.py

No Arguments Given, Perform Default Install? [Y/n]Y


WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
Using WINDOWS configuration...

Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da

---
For help with compilation see:
    https://www.pygame.org/wiki/CompileWindows
To contribute to pygame development see:
    https://www.pygame.org/contribute.html
---

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "C:\Program Files\Python39\lib\http\client.py", line 948, in send
    self.connect()
  File "C:\Program Files\Python39\lib\http\client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\source\python\pygame\setup.py", line 359, in <module>
    buildconfig.config.main(AUTO_CONFIG)
  File "C:\source\python\pygame\buildconfig\config.py", line 225, in main
    deps = CFG.main(**kwds)
  File "C:\source\python\pygame\buildconfig\config_win.py", line 497, in main
    and download_win_prebuilt.ask(**download_kwargs):
  File "C:\source\python\pygame\buildconfig\download_win_prebuilt.py", line 290, in ask
    update(x86=x86, x64=x64)
  File "C:\source\python\pygame\buildconfig\download_win_prebuilt.py", line 273, in update
    download_prebuilts(download_dir, x86=x86, x64=x64)
  File "C:\source\python\pygame\buildconfig\download_win_prebuilt.py", line 124, in download_prebuilts
    download_sha1_unzip(url, checksum, temp_dir, 1)
  File "C:\source\python\pygame\buildconfig\download_win_prebuilt.py", line 54, in download_sha1_unzip
    response = urllib.urlopen(request).read()
  File "C:\Program Files\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
```

**Comment by Starbuck5** [comment]
Hello,

Occasionally we have issues with automated downloads like this. I just tried this on a new `pygame` on my system (Windows 10, Python 3.9.5) and it worked fine. It might work for you if you try again.

If it is still failing, download this and put the unzipped contents in the `pygame/` directory.
[prebuilt_downloads.zip](https://github.com/pygame/pygame/files/7832961/prebuilt_downloads.zip)
(I.e. the result would look like pygame/prebuilt_downloads/*.zip)

**Comment by Rabbid76** [comment]
Thank you. The download still fails (ongoing). However, after downloading the pre-build, the setup worked without any further problems.
