### ISSUE TITLE
glcube.py OpenGL.error.Error: Attempt to retrieve context when no valid context

### ISSUE THREAD

**Issue by brccabral** [pygame/pygame#3110]
Hi,
I am getting this error trying to run `examples/glcube.py`. Any ideas?

Ubuntu 20.04
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)

```
python glcube.py          
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html


Traceback (most recent call last):
  File "glcube.py", line 591, in <module>
    main()
  File "glcube.py", line 544, in main
    gpu, f_indices, o_indices = init_gl_modern(display_size)
  File "glcube.py", line 409, in init_gl_modern
    GL.glVertexAttribPointer(loc, 3, GL.GL_FLOAT, False, stride, offset)
  File "/media/Data/PythonProjects/Games/.venv/lib/python3.8/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/media/Data/PythonProjects/Games/.venv/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
    contextdata.setValue( key, array )
  File "/media/Data/PythonProjects/Games/.venv/lib/python3.8/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/media/Data/PythonProjects/Games/.venv/lib/python3.8/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
```

**Comment by MyreMylar** [comment]
Anything else odd about your setup? Are you running pygame remotely, in a container on a separate thread? Apparently this error crops up when GL can't access the main thread/display.

The example runs on main right now on windows:

![image](https://user-images.githubusercontent.com/13382426/161372183-1732227b-d08e-4ab0-bd30-1dfe5329d0a7.png)


This is pygame 2.1.3.dev5 (SDL 2.0.20, Python 3.9.0)

**Comment by SiddhantRanade** [comment]
I'm facing the exact same issue when running pygame on Ubuntu 20.04 (WSL2 fresh install) within WSL2 on Windows 11. I verified that glxgears works.

**Comment by brccabral** [comment]
Hi @MyreMylar , it is the same problem as #3114 , on Wayland I get the error, on Xorg it runs OK.

**Comment by thisistejaspandey** [comment]
Same issue! Please escalate!!!!

**Comment by anji993** [comment]
> I'm facing the exact same issue when running pygame on Ubuntu 20.04 (WSL2 fresh install) within WSL2 on Windows 11. I verified that glxgears works.

Hi @SiddhantRanade have you solved this problem? I meet the same problem as yours!

**Comment by miikkuu** [comment]
Same issue here!

**Comment by miikkuu** [comment]
@MyreMylar Please Maintainers have a look!

**Comment by DavidDomkar** [comment]
Having the same issue

**Comment by Mayitzin** [comment]
> Hi @MyreMylar , it is the same problem as #3114 , on Wayland I get the error, on Xorg it runs OK.

This was exactly my problem. I had to go back to Xorg and now it runs as it should.

**Comment by gerolfscherr** [comment]
I can reproduce this with: pygame 2.5.2, PyOpenGL 3.1.7 Ubuntu 22.04.3 LTS (XDG_SESSION_TYPE="wayland")
On my system the call ''platform.GetCurrentContext()" returns 0 which is considered invalid in this line:
https://github.com/mcfletch/pyopengl/blob/29b79e8966ba2930a5c44829b02dffc1ca600752/OpenGL/contextdata.py#L38
If you comment out that line, the example works. It seems that the error check is too strict/outdated/maybe not valid (0 vs None?).

(just for the sake of completeness: one can bypass the problem with the example if USE_MODERN_GL = False) but that doesn't help with my real world application.

**Comment by tstandley** [comment]
I have this issue too. Here is a minimal example:
```
import pygame
from pygame.locals import *
from OpenGL.GL import *
import numpy as np

# Initialization
pygame.init()
display = (800, 600)
pygame.display.set_mode(display, DOUBLEBUF | OPENGL)
glOrtho(-2, 2, -1.5, 1.5, -1, 1)

# Set clear color to black
glClearColor(0.0, 0.0, 0.0, 1.0)

# Set point size
glPointSize(10.0)

# Set color to white
glColor3f(1.0, 1.0, 1.0)

# Vertex data
points = np.array([
    -1.0, -1.0, 0.0,
     1.0, -1.0, 0.0,
     0.0,  1.0, 0.0
], dtype=np.float32)

# Main loop
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()

    # Renderg
    glClear(GL_COLOR_BUFFER_BIT)

    # Draw points using glDrawArrays
    glEnableClientState(GL_VERTEX_ARRAY)
    glVertexPointer(3, GL_FLOAT, 0, points)
    glDrawArrays(GL_POINTS, 0, len(points)//3)
    glDisableClientState(GL_VERTEX_ARRAY)

    pygame.display.flip()
    pygame.time.wait(10)
```

This runs fine on Windows, but gives:

```
Traceback (most recent call last):
  File "/home/tstand/Dropbox/ivan's programming/Conway's game of life/minimal_example.py", line 40, in <module>
    glVertexPointer(3, GL_FLOAT, 0, points)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 321, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/home/tstand/.local/lib/python3.10/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/home/tstand/.local/lib/python3.10/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/home/tstand/.local/lib/python3.10/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
```

on Ubuntu 22.04

**Comment by gerolfscherr** [comment]
>   File "/home/tstand/.local/lib/python3.10/site-packages/OpenGL/contextdata.py", line 40, in getContext
>     raise error.Error(
> OpenGL.error.Error: Attempt to retrieve context when no valid context

does it work if you remove the check for 0?

> ```
> 
> on Ubuntu 22.04

**Comment by whydoubt** [comment]
Regarding the check for `0`...
On Linux, the context will be from either GLX or EGL.
  - `glXGetCurrentContext` documentation: "If there is no current context, `NULL` is returned."
  - `eglGetCurrentContext` documentation: "If no context is current, `EGL_NO_CONTEXT` is returned."
  - To python, these both equate to `0`.

So the check really shouldn't be removed, as it is behaving correctly.

**Comment by whydoubt** [comment]
The problem seems to be due to a mis-match between Pygame and PyOpenGL.
PyOpenGL (since 3.1.6 AFICT) appears to prefer Wayland/EGL when available over X11/GLX.
Pygame depends on SDL2, which prefers X11/GLX over Wayland/EGL.
  - The preference will change to Wayland with SDL3 (whenever that will happen).
  - For now, one of these could be added to Pygame to alter this preference:
  - `SDL_SetHint(SDL_HINT_VIDEODRIVER, "wayland,x11");` - To prefer the wayland driver.
  - `SDL_SetHint(SDL_HINT_VIDEO_X11_FORCE_EGL, "1");` - To use EGL even within the X11 driver.

**Comment by ax-va** [comment]
The same problem:
`OpenGL.error.Error: Attempt to retrieve context when no valid context`
Ubuntu 22.04.3 LTS
Python 3.10
PyOpenGL 3.1.7
PyOpenGL-accelerate 3.1.7
numpy 1.26.2
pygame 2.5.2

**Comment by metal3d** [comment]
OK...

```python
import os
os.environ["SDL_VIDEO_X11_FORCE_EGL"] = "1"
```

**Comment by thabomoloi** [comment]
> OK...
> 
> ```python
> import os
> os.environ["SDL_VIDEO_X11_FORCE_EGL"] = "1"
> ```

This worked for me. Thank you.
