### ISSUE TITLE
pygame.font.SysFont takes a long time on macOS

### ISSUE THREAD

**Issue by derek1906** [pygame/pygame#344]
For details take a look at this [SO post](https://stackoverflow.com/q/45384814/283863).

Basically the problem is that `pygame.font.SysFont` takes a really long time to finish on macOS. It's reported that this problem cannot be reproduced on Linux, so I assume this is specific to macOS.

Pygame was installed through `pip install pygame`, version 1.9.3.

**Comment by takluyver** [comment]
The first time you use a SysFont, it will try to run a binary called `fc-list` to get a list of system fonts. You can see the code that does this [here](https://github.com/pygame/pygame/blob/703350f68182641fe72ef1f41d81998fb6d4b385/lib/sysfont.py#L141). Does it take a long time if you run that command directly?

**Comment by derek1906** [comment]
Running `/usr/X11/bin/fc-list` directly in the terminal takes 0.024s:

```
/usr/X11/bin: time fc-list
real	0m0.024s
user	0m0.014s
sys	0m0.004s
```

Also I don't know if this is useful, but it does show the stack if I send a sigterm while `font.SysFont` hangs:

```
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main()
  File "main.py", line 125, in main
    # some irrelevant code here
  File "/path/to/where/it/initialize/the/fonts.py", line 32, in __init__
    self.game_font = pygame.font.SysFont("Arial", 30)
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 280, in SysFont
    initsysfonts()
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 230, in initsysfonts
    fonts = initsysfonts_darwin()
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 146, in initsysfonts_darwin
    fonts = initsysfonts_unix("/usr/X11/bin/fc-list")
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 167, in initsysfonts_unix
    close_fds=True).communicate()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 479, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1100, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1201, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt
```

**Comment by takluyver** [comment]
That does look like it's getting stuck running the fc-list command. No idea why it would be so much slower run under Python than directly. :confused:

**Comment by derek1906** [comment]
Digging deeper apparently the issue was caused by `fc-cache` in XQuartz not able to cache fonts properly ([Bug 97546](https://bugs.freedesktop.org/show_bug.cgi?id=97546)). After updating XQuartz from 2.7.10 to 2.7.11 the speed is back to normal.
