### ISSUE TITLE
CPython 3.11 rc2: `pip install pygame` fails

### ISSUE THREAD

**Issue by veganaize** [pygame/pygame#3459]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
Windows 8.1 (64-bit)
- **Python version** (e.g. 3.7.9, 3.8.5) :
3.11 rc2
- **SDL version** (e.g. SDL 2.0.12):
2.0.18
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):
2.1.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):
x86-64

**Current behavior:**

When attempting to install `pygame` with `pip` version 22.2.2 and `python` version 3.11rc2 `pygame` fails to install at the Administrator command prompt (`cmd`).

**Expected behavior:**

Pygame should install system-wide just like it did with version 3.10 and earlier Python releases.

**Steps to reproduce:**

1. Install CPython version 3.11 rc2 with Pip version 22.2.2 on a Windows x86-64 system.
2. Attempt to run `pip install pygame` from the `CMD.EXE` prompt as Administrator.
3. Observe that the process fails with the error: 
```
Encountered error while generating package metadata.
```

**Stack trace/error output/other error logs**

```
C:\>pip install pygame
Collecting pygame
  Using cached pygame-2.1.2.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\buildconfig\config_win.py", line 511, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\buildconfig\config_win.py", line 471, in setup_
prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\buildconfig\config_win.py", line 336, in config
ure
          from . import vstools
        File "C:\Users\veganaize\AppData\Local\Temp\pip-install-p1ec3b31\pygame_
22272a0a06d5490eb66260590311215b\buildconfig\vstools.py", line 11, in <module>
          compiler.initialize()
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\_distutils
\msvc9compiler.py", line 393, in initialize
          vc_env = query_vcvarsall(VERSION, plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\msvc.py",
line 140, in msvc9_query_vcvarsall
          return EnvironmentInfo(arch, ver).return_env()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\msvc.py",
line 1740, in return_env
          [self.VCIncludes,
           ^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\msvc.py",
line 1282, in VCIncludes
          return [join(self.si.VCInstallDir, 'Include'),
                       ^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\site-packages\setuptools\msvc.py",
line 840, in VCInstallDir
          raise distutils.errors.DistutilsPlatformError(msg)
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.3 or grea
ter is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.m
icrosoft.com/visual-cpp-build-tools/
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed5
61079ec622b0bab5a9e02976f5d540b0622da
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.18-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_imag
e-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-de
vel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixe
r-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8
a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.z
ip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.0.18
      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by Starbuck5** [comment]
Oh no... it begins...
(Other people may open the same issue, especially once 3.11 is actually released)

Pygame is a C-extension, which means it needs to ship out on pypi as binaries, rather than as python code. So when you pip install pypi looks for a matching binary distribution, doesn't find one (because 3.11 is not released yer, we don't have a binary distribution for it). So instead it downloads pygame's source code and tries to build it from source, which fails because you don't have a pygame development environment set up.

Here's a fresh new pygame wheel (binary distribution) just for you! Built for python 3.11rc2.
[pygame-2.1.3.dev5-cp311-cp311-win_amd64.zip](https://github.com/pygame/pygame/files/9596307/pygame-2.1.3.dev5-cp311-cp311-win_amd64.zip)
Just unzip that and pip install the whl directly.

This issue is the same as #3307

**Comment by Starbuck5** [comment]
I see a thumbs up emoji, hopefully that means you were able to install the wheel successfully :)

This will be fixed when pygame updates its wheel generation and uploads new wheels.
