### ISSUE TITLE
SDL version RuntimeError on Mac (M1)

### ISSUE THREAD

**Issue by ZRunner** [pygame/pygame#3461]
**Environment:**

- **Operating system**: macOS 12.6
- **Python version**: 3.9.11
- **SDL version**: 2.24.0 (according to the Pygame debug print)
- **PyGame version**: 2.1.2
- **Relevant hardware**: running on a M1 Mac

**Current behavior:**

`pygame.init()` fails with the following error:
```
RuntimeError: SDL compiled with version 2.0.18, linked to 2.24.0
```

**Expected behavior:**

pygame should run fine.

**Steps to reproduce:**

Here's what I did to reproduce the issue on my computer, but I can't guarantee if that's reproductible on other installations:

1. Setup a new Python env (with python3 -m venv env)
2. Update pip, install wheel and pygame (it specifically installed the `pygame-2.1.2-cp39-cp39-macosx_11_0_arm64.whl`)
3. Run `pygame.init()` in the CLI or in a python script, and see the error

**Test code**

```py
import pygame
pygame.init()
print("Hello, world")
```

**Stack trace/error output/other error logs**

```
pygame 2.1.2 (SDL 2.24.0, Python 3.9.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/XXX/start.py", line 14, in <module>
    pygame.init()
RuntimeError: SDL compiled with version 2.0.18, linked to 2.24.
```

**Comment by ZRunner** [comment]
Update: I've tried installing pygame from GitHub directly, so I'm now with what I guess is the wheel version of the pre-release 5 (I installed with ` python3 -m pip install git+https://github.com/pygame/pygame.git`)

I'm now facing a totally different issue, a circular import in the font sub package. I'm not sure if it's due to the SDL error described above, or if it's totally unrelated. Here's the traceback nonetheless:
```py
  File "/Users/XXX/src/charts.py", line 11, in <module>
    from pygame.font import SysFont
  File "/Users/XXX/env/lib/python3.9/site-packages/pygame/font.py", line 17, in <module>
    from pygame.sysfont import match_font, get_fonts, SysFont as _SysFont
  File "/Users/XXX/env/lib/python3.9/site-packages/pygame/sysfont.py", line 27, in <module>
    from pygame.font import Font
ImportError: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/Users/XXX/env/lib/python3.9/site-packages/pygame/font.py)
```

**Comment by Starbuck5** [comment]
I believe that is what happens when you build pygame without SDL_ttf (the font backend)

Did you follow the directions here: https://www.pygame.org/wiki/MacCompile ?

**Comment by ZRunner** [comment]
I uninstalled and reinstalled some SDL packages with brew, it seems to have fixed the situation. I guess something went wrong during the installation. Thanks for the help!

If I'm right the SDL version check will be fixed in 2.1.3, so i'll close this ticket for now, as a workaround exists.
