### ISSUE TITLE
segfault with pygame.freetype.get_version

### ISSUE THREAD

**Issue by oddbookworm** [pygame/pygame#3564]
**Environment:**
- **Operating system** Windows 11
- **Python version** 3.11.0
- **SDL version** 2.0.20
- **PyGame version** 2.1.3dev8 and 2.1.4dev1
- **Relevant hardware** N/A

**Current behavior:**

Calling `pygame.freetype.get_version()` before initialization causes a segmentation fault

**Expected behavior:**

No segfault, should just raise an exception

**Test code**

```
import pygame
import pygame.freetype
pygame.freetype.get_version()
```

**Stack trace/error output/other error logs**

**WSL**
ignore that I didn't import freetype directly, that's a separate thing that I borked in my own branch
```
Python 3.11.0 (main, Oct 24 2022, 19:56:13) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
/home/andrew/venv/lib/python3.11/site-packages/pygame-2.1.4.dev1-py3.11-linux-x86_64.egg/pygame/pkgdata.py:25: UserWarning: Module pygame was already imported from /home/andrew/venv/lib/python3.11/site-packages/pygame-2.1.4.dev1-py3.11-linux-x86_64.egg/pygame/__init__.py, but /home/andrew/pygame is being added to sys.path
  from pkg_resources import resource_stream, resource_exists
pygame 2.1.4.dev1 (SDL 2.0.20, Python 3.11.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.freetype.get_version()
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00007f0f376a2000 (most recent call first):
  File "<stdin>", line 1 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, pygame._freetype (total: 25)
[1]    12946 IOT instruction  python
```
**WSL gdb backtrace**
```
>>> pygame.freetype.get_version()

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4ebada9 in _ft_get_version (self=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at src_c/_freetype.c:2050
2050            FT_Library_Version(inst->library, &major, &minor, &patch);
(gdb) bt
#0  0x00007ffff4ebada9 in _ft_get_version (self=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at src_c/_freetype.c:2050
#1  _ft_get_version (self=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at src_c/_freetype.c:2039
#2  0x000000000055262b in  ()
#3  0x000000000052de6c in _PyObject_MakeTpCall ()
#4  0x000000000053b811 in _PyEval_EvalFrameDefault ()
#5  0x000000000060d614 in  ()
#6  0x000000000060cbb7 in PyEval_EvalCode ()
#7  0x00000000006306fb in  ()
#8  0x000000000062c844 in  ()
#9  0x00000000004f1d02 in  ()
#10 0x00000000004f1e04 in _PyRun_InteractiveLoopObject ()
#11 0x000000000046d5e6 in  ()
#12 0x00000000004f1a59 in PyRun_AnyFileExFlags ()
#13 0x0000000000467940 in  ()
#14 0x00000000005fcb1d in Py_BytesMain ()
#15 0x00007ffff7c7fd90 in __libc_start_call_main (main=main@entry=0x5fca70, argc=argc@entry=1, argv=argv@entry=0x7fffffffdb78) at ../sysdeps/nptl/libc_start_call_main.h:58
#16 0x00007ffff7c7fe40 in __libc_start_main_impl (main=0x5fca70, argc=1, argv=0x7fffffffdb78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdb68)
    at ../csu/libc-start.c:392
#17 0x00000000005fc9a5 in _start ()
```
Windows is identical

**Comment by ankith26** [comment]
Thanks for the fix! This issue can be closed now
