### ISSUE TITLE
LayeredDirty does not support class_getitem for type annotations

### ISSUE THREAD

**Issue by CoolCat467** [pygame/pygame#3584]
**Environment:**
- **Operating system** : Linux(Ubuntu)
- **Python version** : 3.11.0
- **SDL version** : SDL 2.0.22
- **PyGame version** : 2.1.3.dev8

**Current behavior:**

Mypy says that LayeredDirty requires the type of sprite class that it will be handling, tell it that type results in error:
`TypeError: type 'LayeredDirty' is not subscriptable`

**Expected behavior:**

Expected to be able to tell LayeredDirty what type of sprite it is handling without errors.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Import pygame
2. Make subclass of LayeredDirty defining type of sprite LayeredDirty is handling (ex `class Group(LayeredDirty[Sprite])`)
3. `TypeError: type 'LayeredDirty' is not subscriptable`

**Test code**

If possible add a simple test program that shows the problem described in this report.
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Crash example - TypeError: type 'LayeredDirty' is not subscriptable

"""This is a modified excerpt from a game I am programming"""

# Programmed by CoolCat467

from typing import Any
from pygame.rect import Rect
from pygame.surface import Surface
from pygame.sprite import DirtySprite, LayeredDirty

class Component:
    "Base Component"
    def __init__(self, name: str) -> None:
        ...

class ComponentManager(Component):
    "Group of Components"
    def __init__(self, name: str) -> None:
        super().__init__(name)
        ...

class Sprite(DirtySprite, ComponentManager):
    "Both Dirty Sprite and Component Manager"
    def __init__(self, name: str) -> None:
        DirtySprite.__init__(self)
        ComponentManager.__init__(self, name)
        
        self.rect = Rect(0, 0, 0, 0)
        self.image = Surface((0, 0))
    ...




class Group(LayeredDirty[Sprite], ComponentManager):
    "Group of Layered Dirty Sprites"
    __slots__ = ()
    def __init__(self,
                 name: str,
                 *sprites: Sprite,
                 **kwargs: Any) -> None:
        LayeredDirty.__init__(self, *sprites, **kwargs)
        ComponentManager.__init__(self, name)
    ...

```

**Stack trace/error output/other error logs**

```
pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.11.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/lib/python3.11/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "<path/to/file>", line 38, in <module>
    class Group(LayeredDirty[Sprite], ComponentManager):
                ~~~~~~~~~~~~^^^^^^^^
TypeError: type 'LayeredDirty' is not subscriptable
```

How to fix:
```python
# Monkey-patch LayeredDirty to properly support __class_getitem__
LayeredDirty.__class_getitem__ = lambda x: LayeredDirty  # type: ignore[attr-defined]
```

**Comment by Starbuck5** [comment]
On my end changing `class Group(LayeredDirty[Sprite], ComponentManager):` to `class Group(LayeredDirty, ComponentManager):` works fine with typing and at runtime.

**Comment by CoolCat467** [comment]
I am using `mypy --disallow-untyped-defs --disallow-untyped-calls --strict`
