### ISSUE TITLE
Trouble with pip installing pygame. Please help.

### ISSUE THREAD

**Issue by CatUnderTheNameOfA** [pygame/pygame#3660]
I've been trying to pip install pygame (by using commands such as "pip install pygame" and "pip3 install -r requirements.txt", where "requirements.txt" just contains the word "pygame"), but it fails to install every time and gives back the same message* (please, see below). I've tried going to www.pygame.org, but it gives an Internal Server Error. 
Please advise how to fix this problem.

*Message:
"Defaulting to user installation because normal site-packages is not writeable
Collecting pygame
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 47.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      
      
      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...
      
      /bin/sh: 1: sdl2-config: not found
      /bin/sh: 1: sdl2-config: not found
      /bin/sh: 1: sdl2-config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ef765t_e/pygame_ec907c9aa9d848ffa273dc197f8f71c2/setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "/tmp/pip-install-ef765t_e/pygame_ec907c9aa9d848ffa273dc197f8f71c2/buildconfig/config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ef765t_e/pygame_ec907c9aa9d848ffa273dc197f8f71c2/buildconfig/config_unix.py", line 188, in main
          DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ef765t_e/pygame_ec907c9aa9d848ffa273dc197f8f71c2/buildconfig/config_unix.py", line 39, in __init__
          self.ver = config[0].strip()
                     ~~~~~~^^^
      IndexError: list index out of range
      
      Hunting dependencies...
      
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
 
× Encountered error while generating package metadata.
╰─> See above for output.
 
note: This is an issue with the package mentioned above, not pip.
hint: See above for details."

**Comment by oddbookworm** [comment]
`pip install pygame --pre`

**Comment by waireeee** [comment]
> `pip install pygame --pre`

I can't thank you enough.

**Comment by CatUnderTheNameOfA** [comment]
Thank you so much for recommending the command "pip install pygame --pre"! 
I have been able to download pygame using it. Once again, thank you.
