### ISSUE TITLE
Cannot install pygame

### ISSUE THREAD

**Issue by RayAsh37** [pygame/pygame#3673]
I have been trying to install pygame on my **Windows 11** machine and have been unsuccessful so far. This is the complete log from the console.
```
(venv) C:\Users\ashra\Documents\__softwareDev\Python\test>pip3 install pygame
Collecting pygame
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\setup.py", line 359, in <module>      
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\buildconfig\config_win.py", line 511, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\buildconfig\config_win.py", line 471, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\ashra\AppData\Local\Temp\pip-install-z85vqe2y\pygame_c6cb5ec149fa44be800e6a0341017667\buildconfig\vstools.py", line 11, in <module>
          compiler.initialize()
        File "C:\Users\ashra\Documents\__softwareDev\Python\test\venv\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 403, in initialize
          vc_env = query_vcvarsall(VERSION, plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ashra\Documents\__softwareDev\Python\test\venv\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 281, in query_vcvarsall
          raise DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.18-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b      
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc      
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.0.18
      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I have also tried
```
pip install pygame
```
no luck with that either.

**Comment by Starbuck5** [comment]
See #3522

**Comment by Mustafa2707** [comment]
PS C:\Users\ApriZon> pip install pygame
Collecting pygame
  Using cached pygame-2.6.1.tar.gz (14.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
      Skipping Cython compilation


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.28.4-VC.zip 25ef9d201ce3fd5f976c37dddedac36bd173975c
      Unzipping :prebuilt_downloads\SDL2-devel-2.28.4-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.28.4
      ...Library directory for SDL: prebuilt-x64/SDL2-2.28.4/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.28.4/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.28.4/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      Traceback (most recent call last):
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\vstools.py", line 4, in <module>
          from distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\vstools.py", line 6, in <module>
          from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\vstools.py", line 4, in <module>
          from distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\ApriZon\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Users\ApriZon\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ApriZon\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-build-env-01nd6a7j\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-build-env-01nd6a7j\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-build-env-01nd6a7j\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-build-env-01nd6a7j\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 432, in <module>
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\config.py", line 234, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\config_win.py", line 338, in configure
          from buildconfig import vstools
        File "C:\Users\ApriZon\AppData\Local\Temp\pip-install-acsj2rj7\pygame_13f30b23237a4dd8a9be18a92e0d0dbb\buildconfig\vstools.py", line 6, in <module>
          from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
      ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
