### ISSUE TITLE
some color-handling tests fail on ppc64el

### ISSUE THREAD

**Issue by Natureshadow** [pygame/pygame#370]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861252

```
  ======================================================================
  FAIL: test_save_colorkey (pygame.tests.image_test.ImageModuleTest)
  make sure the color key is not changed when saving.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/<<BUILDDIR>>/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/image_test.py", line 283, in test_save_colorkey
      self.assertEqual(p1, s2.get_at((0,0)))
  AssertionError: (23, 23, 23, 255) != (23, 23, 255, 23)
  
  ======================================================================
  FAIL: test_cross (pygame.tests.math_test.Vector2TypeTest)
  [as per #861249]
  
  ======================================================================
  FAIL: test_blanket_alpha (pygame.tests.surface_test.SurfaceSelfBlitTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/<<BUILDDIR>>/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/surface_test.py", line 2331, in test_blanket_alpha
      self._assert_same(surf, comp)
    File "/<<BUILDDIR>>/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/surface_test.py", line 2252, in _assert_same
      a.get_bitsize())))
  AssertionError: (255, 0, 0, 255) != (0, 255, 170, 255), bpp: 8
  
  ======================================================================
  FAIL: test_colorkey (pygame.tests.surface_test.SurfaceSelfBlitTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/<<BUILDDIR>>/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/surface_test.py", line 2311, in test_colorkey
      self._assert_same(surf, comp)
    File "/<<BUILDDIR>>/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/surface_test.py", line 2252, in _assert_same
      a.get_bitsize())))
  AssertionError: (255, 0, 0, 255) != (0, 255, 0, 255), bpp: 8
```

**Comment by illume** [comment]
Thanks @Natureshadow for all these PPC64el bug reports. Is there some way to get access to such a system that you know of? I found this URL: https://wiki.debian.org/ppc64el#Development_Machines on the world wide web, and requested access to their virtual machine. Fingers crossed!

**Comment by illume** [comment]
It looks like these fail inside SDL_BlitSurface.

Inside surface.c, this part...
```C
            src = SDL_ConvertSurface (src, &newfmt, SDL_SWSURFACE);
            if (src) {
                result = SDL_BlitSurface (src, srcrect, dst, dstrect);
                SDL_FreeSurface (src);
            }
```

If in the test, I add something like this:
```
            comp.blit(tmp.copy(), (0, 0))
```
It avoids the self blit error... but is still slightly wrong.

It's sort of a quite rare case, of needing to do a self blit using a palette. That combined with the very low chance of updates for PPC SDL1 updates, I think I'll skip this test on ppc64le.
