### ISSUE TITLE
Error while installing pygame 2.1.3 on linux

### ISSUE THREAD

**Issue by pankaj1707k** [pygame/pygame#3712]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Linux(Ubuntu) [WSL2]
- **Python version**: 3.10.6
- **SDL version**: 2.0.20
- **PyGame version**: 2.1.3

Pygame 2.1.3 fails to install (via pip) with the following output. However, version 2.1.2 installs absolutely fine.

**Stack trace/error output/other error logs**

```
Collecting pygame
  Using cached pygame-2.1.3.tar.gz (12.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...

      Package freetype2 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `freetype2.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'freetype2' found
      Package freetype2 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `freetype2.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'freetype2' found
      Package freetype2 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `freetype2.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'freetype2' found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_xasrv3q/pygame_8dd247c687994e10aa8f8c06d5032cbf/setup.py", line 400, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "/tmp/pip-install-_xasrv3q/pygame_8dd247c687994e10aa8f8c06d5032cbf/buildconfig/config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "/tmp/pip-install-_xasrv3q/pygame_8dd247c687994e10aa8f8c06d5032cbf/buildconfig/config_unix.py", line 238, in main
          DEPS.append(find_freetype())
        File "/tmp/pip-install-_xasrv3q/pygame_8dd247c687994e10aa8f8c06d5032cbf/buildconfig/config_unix.py", line 202, in find_freetype
          pkg_config = DependencyProg(
        File "/tmp/pip-install-_xasrv3q/pygame_8dd247c687994e10aa8f8c06d5032cbf/buildconfig/config_unix.py", line 43, in __init__
          self.ver = config[0].strip()
      IndexError: list index out of range

      Hunting dependencies...

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by forslundscott** [comment]
Thanks for your note in this issue about the 2.1.2 still working fine! Helped me to still utilize pygame while this issue is being resolved!

Note: Perhaps the issue may be connected to the recent Ubuntu 22.04 upgrade, which automatically installs python 3.10.6 during the upgrade.

**Comment by Lilafian** [comment]
also having this issue on linux mint

**Comment by DroidPvPMaster** [comment]
@pankaj1707k @Lilafian 
My issue has been resolved by running
`pip uninstall pygame` and then `pip install pygame-ce`

**Comment by illume** [comment]
This is working now.
