### ISSUE TITLE
Cannot init audio

### ISSUE THREAD

**Issue by markub3327** [pygame/pygame#3761]
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Ubuntu 22.04.2 LTS amd64
- **Python version** (e.g. 3.7.9, 3.8.5) :  3.10.6
- **SDL version** (e.g. SDL 2.0.12): 2.24.2
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.3.0
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): 
> [    3.475039] snd_hda_codec_realtek hdaudioC1D0: autoconfig for ALC257: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
> [    3.475049] snd_hda_codec_realtek hdaudioC1D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
> [    3.475052] snd_hda_codec_realtek hdaudioC1D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
> [    3.475055] snd_hda_codec_realtek hdaudioC1D0:    mono: mono_out=0x0
> [    3.475057] snd_hda_codec_realtek hdaudioC1D0:    inputs:
> [    3.475061] snd_hda_codec_realtek hdaudioC1D0:      Mic=0x19
> [    3.475063] snd_hda_codec_realtek hdaudioC1D0:      Internal Mic=0x12

**Current behavior:**

```python
from pygame import mixer as pyg_mixer
```
> Traceback (most recent call last):
>   File "/home/kai/.local/bin/flappy_bird_gymnasium", line 33, in <module>
>     sys.exit(load_entry_point('flappy-bird-gymnasium', 'console_scripts', 'flappy_bird_gymnasium')())
>   File "/home/kai/Desktop/flappy-bird-gymnasium/flappy_bird_gymnasium/cli.py", line 61, in main
>     human_agent_env()
>   File "/home/kai/Desktop/flappy-bird-gymnasium/tests/test_simple_env_human.py", line 45, in play
>     env.render()
>   File "/home/kai/.local/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 52, in render
>     return self.env.render(*args, **kwargs)
>   File "/home/kai/.local/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py", line 53, in render
>     return env_render_passive_checker(self.env, *args, **kwargs)
>   File "/home/kai/.local/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 384, in env_render_passive_checker
>     result = env.render()
>   File "/home/kai/Desktop/flappy-bird-gymnasium/flappy_bird_gymnasium/envs/flappy_bird_env_simple.py", line 186, in render
>     self._renderer = FlappyBirdRenderer(
>   File "/home/kai/Desktop/flappy-bird-gymnasium/flappy_bird_gymnasium/envs/renderer.py", line 82, in __init__
>     self.sounds = utils.load_sounds()
>   File "/home/kai/Desktop/flappy-bird-gymnasium/flappy_bird_gymnasium/envs/utils.py", line 140, in load_sounds
>     pyg_mixer.init()
> pygame.error: dsp: No such audio device

**Expected behavior:**

Correctly initialised audio mixer.

**Steps to reproduce:**

```shell
git clone https://github.com/markub3327/flappy-bird-gymnasium
pip3 install -e .
flappy_bird_gymnasium --mode human
```

OR

**utils.py**
```python
def load_sounds() -> Dict[str, pyg_mixer.Sound]:
    """Loads and returns the audio assets of the game."""
    pyg_mixer.init()
    sounds = {}

    if "win" in sys.platform:
        soundExt = ".wav"
    else:
        soundExt = ".ogg"

    try:
        sounds["die"] = pyg_mixer.Sound(AUDIO_PATH + "/die" + soundExt)
        sounds["hit"] = pyg_mixer.Sound(AUDIO_PATH + "/hit" + soundExt)
        sounds["point"] = pyg_mixer.Sound(AUDIO_PATH + "/point" + soundExt)
        sounds["swoosh"] = pyg_mixer.Sound(AUDIO_PATH + "/swoosh" + soundExt)
        sounds["wing"] = pyg_mixer.Sound(AUDIO_PATH + "/wing" + soundExt)
    except FileNotFoundError as ex:
        raise FileNotFoundError(
            "Can't find the audio folder! No such file or " f"directory: {AUDIO_PATH}"
        ) from ex

    return sounds
```

**test.py**
```python
from flappy_bird_gymnasium.envs import utils
utils.load_sounds()
```

If I tested it from console .... `pyg_mixer.init()` is working:
```shell
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import mixer as pyg_mixer
pygame 2.3.0 (SDL 2.24.2, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pyg_mixer.init()
>>> 
```

**Comment by illume** [comment]
I guess in your game the difference is that it is doing pygame.init() first. Could you try that in the interpreter too?

**Comment by markub3327** [comment]
@illume 

It's without the issue:

```shell
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import mixer as pyg_mixer
pygame 2.3.0 (SDL 2.24.2, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> import pygame
>>> pygame.init()
(5, 0)
>>> pyg_mixer.init()
>>> 
```

**Comment by SuhaniNarangu7745615** [comment]
for ubuntu ,You can install these packages using your package manager
sudo apt-get install libsdl2-mixer-2.0-0
or 
You can specify the audio device to be used by Pygame when initializing the mixer.
pyg_mixer.init(devicename="pygame.mixer.get_dev_info()")
hopefully this resolves the bug

**Comment by kaybeebee** [comment]
### Environment
Hardware: 
- Raspberry Pi Zero 2 W Rev 1.0
OS:
- Debian Bullseye 
Software:
- python 3.9.2
- pygame 1.9.6

Script (example): 
`import pygame`
`pygame.mixer.init()`
`...`

Using Thonny: No problem
Using Terminal: **Error**
Error code: 
`Hello from the pygame community. https://www.pygame.org/contribute.html
...
  File "/home/path/Test_run.py", line 13, in play_random_message
    pygame.mixer.init()
`

So, till now I have no clue to solve this. Already tried out to set up audio device with asound.conf, changed _pygame.mxer.init()_ inputs and put _pygame.mixer.quit()_ in front of the initilization. Nothing helped....

**Comment by kaybeebee** [comment]
> ### Environment
> 
> Hardware:
> 
>     * Raspberry Pi Zero 2 W Rev 1.0
> 
> 
> OS:
> 
>     * Debian Bullseye
> 
> 
> Software:
> 
>     * python 3.9.2
> 
>     * pygame 1.9.6
> 
> 
> Script (example): `import pygame` `pygame.mixer.init()` `...`
> 
> Using Thonny: No problem Using Terminal: **Error** Error code: `Hello from the pygame community. https://www.pygame.org/contribute.html ... File "/home/path/Test_run.py", line 13, in play_random_message pygame.mixer.init() `
> 
> So, till now I have no clue how to solve this. Already tried out to set up audio device with asound.conf, changed _pygame.mixer.init()_ inputs and put _pygame.mixer.quit()_ in front of the initilization. Nothing helped....

ok.... now it's working. I simply stopped putting sudo in front of my command to run the python script.
Does not work: `sudo python3 Test.py`
Does work: `sudo python3 Test.py`

Sorry for the spam!

**Comment by markub3327** [comment]
@kaybeebee There is not a diffrence between:

**Comment by kaybeebee** [comment]
Sorry, was late. Corrected it now.

**Comment by Fruit-GG** [comment]
> Sorry, was late. Corrected it now.

Dear,How do you correct this problem? I still meet it when I using flappy_bird_gymnasium in Linux

**Comment by alexzhuustc** [comment]
> > Sorry, was late. Corrected it now.
> 
> Dear,How do you correct this problem? I still meet it when I using flappy_bird_gymnasium in Linux

import pygame
pygame.init()                 # <---  got fixed by adding this line of code between pygame and gymnasium 
import gymnasium as gym

I use pulseaudio as sound device in container (SDL_AUDIODRIVER="pulseaudio" PULSE_SERVER="tcp:host.docker.internal"), and encounter the same issue "... pygame.error: dsp: No such audio device".

For me, I find a way to fix it (see above).  But I don't know why it can fixed.

**Comment by dannyh147** [comment]
Encountering the same issue when running the flappybird gymnasium on ubuntu 22.04.

flappy_bird_gymnasium/envs/utils.py", line 140, in load_sounds
    pyg_mixer.init()
pygame.error: dsp: No such audio device

**Comment by alexfrunza** [comment]
Not related with pygame, but to solve this for flappybird gymnasium you can modify [this line](https://github.com/markub3327/flappy-bird-gymnasium/blob/d1c16cff69b2058f92b6426ce3ca39415644803d/flappy_bird_gymnasium/tests/test_human.py#L40) with `audio_on=False`.
