### ISSUE TITLE
Hi I have an issue in installing pygame, it always pop out this following issue, anyone knows how to solve the issue? really appreciate. 

### ISSUE THREAD

**Issue by checkiiiii** [pygame/pygame#3791]
C:\python\pygame-2.3.0>pip install pygame --pre
Collecting pygame
  Using cached pygame-2.4.0.dev2.tar.gz (12.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\setup.py", line 400, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\buildconfig\config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\FENGLEI\AppData\Local\Temp\pip-install-3t90mxgf\pygame_c5e406cb4236435192da3920eb737497\buildconfig\vstools.py", line 8, in <module>
          compiler.initialize()
        File "C:\python\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 403, in initialize
          vc_env = query_vcvarsall(VERSION, plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\python\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 281, in query_vcvarsall
          raise DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.26.4-VC.zip 0dea77fd5ead8c1a2134af3fc256578327e25879
      Unzipping :prebuilt_downloads\SDL2-devel-2.26.4-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.26.4
      ...Library directory for SDL: prebuilt-x64/SDL2-2.26.4/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.26.4/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.26.4/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by illume** [comment]
Hi. I guess you’ve moved on. But if you’re still trying to figure it out…

 I wonder what python version you’re using? It looks like you’re on windows. What cpu are you using?

For some reason it was trying to compile from source instead of using a pre compiled binary. So, maybe the architecture or python version is the key to the problem.

There’s some new pygame releases, that might be worth a try.

cheers

**Comment by sdk451** [comment]
New releases (e.g. pygame 2.5.2) do work on windows, but that's of little help because a lot of key reinforcement learning packages (elegantrl, gym etc) still haven't updated their dependencies/requirements from pygame 2.1.0,  so those packages fail on installation via pip, blocking clean installs.

**Comment by amuuchan** [comment]
Hi I am having the same issue. Did anyone find a solution to this problem?
