### ISSUE TITLE
Error when install Pygame 2.4.0 on Windows

### ISSUE THREAD

**Issue by thaisonho** [pygame/pygame#3799]
I've tried both `pip install pygame` and `pip install pygame --pre` but it still show the same error all the time.

- Windows version: 10.0.19045 Build 19045
- Python version: Python 3.10.9
- pip version: pip 23.1
 ``` shell
Collecting pygame
  Using cached pygame-2.3.0.tar.gz (12.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
     
     
      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\setup.py", line 400, in 
<module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\buildconfig\config.py", 
line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\JamesHo\AppData\Local\Temp\pip-install-3_izvwsy\pygame_d1bf6162b4a745ef89e0ebe33e6a4e99\buildconfig\vstools.py", line 8, in <module>
          compiler.initialize()
        File "C:\msys64\mingw64\lib\python3.10\site-packages\setuptools\_distutils\msvccompiler.py", line 288, in initialize
          self.__paths = self.get_msvc_paths("path")
        File "C:\msys64\mingw64\lib\python3.10\site-packages\setuptools\_distutils\msvccompiler.py", line 647, in get_msvc_paths       
          r"\Win32 (%s)\Directories" % (self.__root, platform)
      AttributeError: 'MSVCCompiler' object has no attribute '_MSVCCompiler__root'. Did you mean: '_MSVCCompiler__arch'?
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.24.2-VC.zip 19b1e9f5bcf700a402bb924c0194c96596283c32
      Unzipping :prebuilt_downloads\SDL2-devel-2.24.2-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.24.2
      ...Library directory for SDL: prebuilt-x64/SDL2-2.24.2/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.24.2/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.24.2/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll
     
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by leestarb** [comment]
It tries to compile pygame. Maybe your python is broken, try other version

**Comment by illume** [comment]
@thaisonho what CPU are you using on windows?

**Comment by Avasam** [comment]
Seemingly the same issue (tracelog below).
Windows 10.0.19045 Build 19045
Processor AMD Ryzen 5 2600 Six-Core Processor, 3400 Mhz, 6 Core(s), 12 Logical Processor(s)
Python 3.9.13
setuptools 67.7.1
pip 23.1.2

```
pip install pygame
Collecting pygame
  Using cached pygame-2.4.0.tar.gz (13.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      
      
      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\setup.py", line 400, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\buildconfig\config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\Avasam\AppData\Local\Temp\pip-install-kp74niy4\pygame_d5050853477d4c63aea635f6919cb3bf\buildconfig\vstools.py", line 8, in <module>
          compiler.initialize()
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 403, in initialize
          vc_env = query_vcvarsall(VERSION, plat_spec)
        File "C:\Program Files\Python39\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 281, in query_vcvarsall
          raise DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.26.4-VC.zip 0dea77fd5ead8c1a2134af3fc256578327e25879
      Unzipping :prebuilt_downloads\SDL2-devel-2.26.4-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.26.4
      ...Library directory for SDL: prebuilt-x64/SDL2-2.26.4/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.26.4/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.26.4/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll
     
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by sdk451** [comment]
This issue also affects pygame 2.1.0 on windows, python 3.11.9.
Can directly install pygame 2.5.2 via pip, but packages with enforced dependencies on 2.1.0, 2.3.0 etc will fail (e.g. elegantrl). This really needs a fix.
