### ISSUE TITLE
Error when running code: No hardware accelerated renderers available

### ISSUE THREAD

**Issue by Jung-PS** [pygame/pygame#3835]
**Environment:**

- **Operating system** : MacOS Big Sur 11.1 running on VMware® Workstation 17 Pro Version : 17.0.0 build-20800274
- **Python version**  : 3.10.9
- **PyGame version**  : 2.4.0
- **Relevant hardware**  :  CPU : i7-3630qm RAM : DDR3 16.0GB GPU: NVIDIA GeForce GTX 660M
- **Code Editor** : Pycharm Community 2023.1.1 Build: 231.8770.66 28 April 2023

**Current behavior:**
When running the following sample code from https://www.pygame.org/docs/ :

```
# Example file showing a basic pygame "game loop"
import pygame

# pygame setup
pygame.init()
screen = pygame.display.set_mode((1280, 720))
clock = pygame.time.Clock()
running = True

while running:
    # poll for events
    # pygame.QUIT event means the user clicked X to close your window
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # fill the screen with a color to wipe away anything from last frame
    screen.fill("purple")

    # RENDER YOUR GAME HERE

    # flip() the display to put your work on screen
    pygame.display.flip()

    clock.tick(60)  # limits FPS to 60

pygame.quit()
```

Following Error :
```
pygame 2.4.0 (SDL 2.26.4, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/...............", line 7, in <module>
    screen = pygame.display.set_mode((1280, 720))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error: No hardware accelerated renderers available
```

**Screenshots**

![image](https://user-images.githubusercontent.com/103345620/236369755-2cef9e0e-23a3-47dc-8791-13ba68fa796f.png)

**Comment by Sahil481** [comment]
Do you have multiple or another screen(s) connected to the mac?

**Comment by Jung-PS** [comment]
> Do you have multiple or another screen(s) connected to the mac?

No Only one screen

**Comment by mmdmoa** [comment]
Use [pygame-ce](https://github.com/pygame-community/pygame-ce) and tell us if this issue persists

**Comment by illume** [comment]
Would you be able to try this?

```python
import os
os.environ["SDL_VIDEODRIVER"] = "cocoa"
os.environ["SDL_OPENGL_ACCELERATED_VISUAL"] = "1"
import pygame
```

**Comment by Jung-PS** [comment]
> Would you be able to try this?
> 
> ```python
> import os
> os.environ["SDL_VIDEODRIVER"] = "cocoa"
> os.environ["SDL_OPENGL_ACCELERATED_VISUAL"] = "1"
> import pygame
> ```

Ok I will try.

**Comment by Jung-PS** [comment]
> Would you be able to try this?
> 
> ```python
> import os
> os.environ["SDL_VIDEODRIVER"] = "cocoa"
> os.environ["SDL_OPENGL_ACCELERATED_VISUAL"] = "1"
> import pygame
> ```

Still not working.

**Comment by illume** [comment]
I wonder if you tried it with:

```
os.environ["SDL_OPENGL_ACCELERATED_VISUAL"] = "1"
```

**Comment by carlosperate** [comment]
I'm having the same issue in virtualized macOS 10.15 Catalina with VMware.

Similarly to https://github.com/pygame/pygame/issues/3941, pygame v2.5.0 down to v2.2.0 throw this error, then v2.1.3 fails with a different error (pasted below), and v2.1.2 works.

```
Hello from the pygame community. https://www.pygame.org/contribute.html
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/ptext.py:44: RuntimeWarning: use font: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/font.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libfreetype.6.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfreetype.6.dylib
  Reason: image not found
(ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/font.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libfreetype.6.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfreetype.6.dylib
  Reason: image not found)
  pygame.font.init()
Traceback (most recent call last):
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/__main__.py", line 1, in <module>
    from pgzero.runner import main
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/runner.py", line 12, in <module>
    from .game import PGZeroGame, DISPLAY_FLAGS
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/game.py", line 8, in <module>
    import pgzero.screen
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/screen.py", line 3, in <module>
    from . import ptext
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/ptext.py", line 44, in <module>
    pygame.font.init()
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: font module not available (ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/font.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libfreetype.6.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfreetype.6.dylib
  Reason: image not found)
```
But this one looks like it might be https://github.com/pygame/pygame/issues/3596, which is unrelated and fixed.

**Comment by dddddgz** [comment]
I have the same question. Are you solved?

**Comment by happyleibniz** [comment]
The error message "No hardware accelerated renderers available" suggests that Pygame is unable to find a hardware-accelerated graphics driver on your system. This is likely due to running your code in a virtual machine (VMware® Workstation 17 Pro), which may not have direct access to your GPU.

Here are a few potential solutions:

1. Enable 3D acceleration in VMware settings: Make sure that 3D acceleration is enabled in your VMware settings. This allows the VM to use the host's GPU for rendering.

2. Install appropriate graphics drivers in your VM: Ensure that the appropriate graphics drivers are installed within your VM. For MacOS, this might not be straightforward due to Apple's restrictions on third-party drivers.

3. Run your code on your host machine: If possible, try running your code directly on your host machine instead of inside a VM. This will give your code direct access to the GPU.

4. Use a software renderer: If none of the above solutions work, you can try using a software renderer instead of a hardware-accelerated one. This can be slower, but it should work on any system. You can enable this in Pygame by setting the SDL_VIDEODRIVER environment variable to 'dummy' before initializing Pygame:
import os
import pygame

os.environ['SDL_VIDEODRIVER'] = 'dummy'

pygame.init()
# rest of your code
Please note that the last solution is a workaround and might not provide the best performance.
