### ISSUE TITLE
DLL import error when installing PIL in custom directory and then importing

### ISSUE THREAD

**Issue by mai1x9** [pygame/pygame#3863]
**Environment:**

- **Operating system**  Windows 10.
- **Python version**  : 3.8.8
- **PyGame version** 2.1.2

I have installed **pygame** in custom directory named `contrib`, using
``` 
pip install pygame==2.1.2 -t ./contrib
```
And from `test.py` which is outside `contrib` directory, I have imported as shown below by adding `contrib` to sys path.
```python
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "contrib" ))

import pygame.camera
import pygame
import pygame.image
```
and it throws the error.
```
  File ".\libtest.py", line 86, in <module>
    import pygame.camera
  File "C:\Users\Mahidhar\Desktop\main\contrib\pygame\__init__.py", line 83, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
  File ".\contrib\pygame\__init__.py", line 83, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ImportError: DLL load failed while importing base: The parameter is incorrect.
PS C:\Users\Mahidhar\Desktop\main>
```

Even below import throws dll error,
```
import contrib.pygame.camera
import contrib.pygame
import contrib.pygame.image
```

However when installed in `lib` folder using `pip install lib`, it works perfectly fine. Why installing to custom directroy like `contrib` is throwing DLL import error. Am i missing some dll paths or something to be added in sys.paths ?

**Comment by illume** [comment]
Hello.

Oh, I've never seen that -t with pip install was possible.

I guess there's some path logic somewhere that would need updating (maybe in `src_py/__init__.py`). See the top of that file.

**Comment by mai1x9** [comment]
@illume, -t is target dir so the lib will be installed in specified directory when -t used. That's why I am getting dll error when I installed pygame in custom directory.

Looking at, `__init__.py`, the below code which adds path and dlls, 
```
import sys
import os

# Choose Windows display driver
if os.name == "nt":
    pygame_dir = os.path.split(__file__)[0]

    # pypy does not find the dlls, so we add package folder to PATH.
    os.environ["PATH"] = os.environ["PATH"] + ";" + pygame_dir

    # windows store python does not find the dlls, so we run this
    if sys.version_info > (3, 8):
        os.add_dll_directory(pygame_dir)  # only available in 3.8+

    # cleanup namespace
    del pygame_dir

# when running und
```
looking at code, I see no fault as it loads them correctly. is the issue while setting up the pygame. 

Had it been installed in lib, as usual using virtual environment, pygame dir would turn to be, `lib/site-packages/pygame`.

In my case, it would turn out to be, `contrib/pygame`. So I think there's nothing to do with `__init__.py` or I may be wrong.

**Comment by mai1x9** [comment]
I could see that the issue is really at `from pygame.base import *`. Since pygame is now installed in directroy `contrib`, it should be `from contrib.pygame.base import *` or it should be `from .base import  *`. 


Actually, `from .base import *` must work, but it is throwing error where `pyd` is imported. I have added `contrib` as well as `pygame` to syspath but none of them worked.

**Comment by mai1x9** [comment]
@illume the project structure as shown below,
```
Project/
     contrib/
              pygame/
                       __init__.py
                       ..... other pygame files.
     
    test.py
```
Basically, pygame is inside contrib folder and it is already build when installed via pip. I have updated `__init__.py` to fix DLL Error.

File: `__init__.py`
```

import sys
import os


pygame_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(pygame_dir)
sys.path.append(os.path.join(pygame_dir, "../../contrib"))

# pypy does not find the dlls, so we add package folder to PATH.
os.environ["PATH"] = os.environ["PATH"] + ";" + pygame_dir

# windows store python does not find the dlls, so we run this
if sys.version_info > (3, 8):
    os.add_dll_directory(pygame_dir)  # only available in 3.8+


from contrib.pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
from contrib.pygame.constants import *  # now has __all__ pylint: disable=wildcard-import; lgtm[py/polluting-import]
from contrib.pygame.version import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]

```

Now from, `tests.py`, below imports are working, 
```
import contrib.pygame.camera
import contrib.pygame
```

But error is thrown when importing image, rect as shown,
```
from contrib.pygame.rect import Rect
from contrib.pygame.image import tostring
```
Error:
```
Traceback (most recent call last):
  File ".\tests.py", line 101, in <module>
    from contrib.pygame.color import *
ImportError: DLL load failed while importing base: The parameter is incorrect.
```
The error is occuring when importing files like surface, image, color, bufferproxy etc... but working for some.

**Comment by illume** [comment]
Sorry, I don't have any ideas to help. That was the only thing I could think of off the top of my head.

Did you consider using virtual environments instead? That's probably a more well tested path.

**Comment by Nagib227** [comment]
Сделай сначала это `py -m pip uninstall pygame`, затем `pip install pygame==2.4.0`

**Comment by mai1x9** [comment]
> 

Are you suggesting updating to latest versions fixes the issue.
