### ISSUE TITLE
Pygame Mixer Module not working. Mixer Module not found??

### ISSUE THREAD

**Issue by ninjafingers1978** [pygame/pygame#3913]
**Environment:

- Operating system:  Mac 3.5 GHz Intel Core i7
- Python version: (SDL 2.26.4, Python 3.11.3)- **SDL version** (e.g. SDL 2.0.12):
- PyGame version: pygame 2.4.0 
- Issue: Pygame Mixer Module

**Current behavior:  Error message after trying to play a .wav or .mp3 file from mixer module. Mixer module is also not recognised. All other pygame modules work.
-------------------------------------------------------------------------------------------------------------
Warning (from warnings module):
  File "/Users/********Desktop/PG/CAR - SPRITE GROUPING AND COLLISION.py", line 6
    mixer.init()
RuntimeWarning: use mixer: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/mixer.cpython-311-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
(ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/mixer.cpython-311-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown))
Traceback (most recent call last):
  File "/Users/**********/Desktop/PG/CAR - SPRITE GROUPING AND COLLISION.py", line 6, in <module>
    mixer.init()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/mixer.cpython-311-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown))
--------------------------------------------------------------------------------------------------------------
This long error message occurs when i input the line : pygame.mixer.Sound('crash.wav').play()
Expected behavior: Play a .wav file.

After a collision between sprites a sound is meant to be played from line: pygame.mixer.Sound('crash.wav').play()

import pygame, sys
from pygame.locals import *
pygame.init()
 is established. I have tried import mixer and get the same long error message.

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Only trying to import mixer receives error, seems mixer module does not exist,
2. When i try to play a file : 
3.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
import sys
import mixer
-------------------------------------------------
ModuleNotFoundError: No module named 'mixer'
-------------------------------------------------

AREA OF CODE WHICH HAS THE .WAV FILE TO BE PLAYED FROM THE MIXER MODULE

if pygame.sprite.spritecollideany(P1, enemies):
          pygame.mixer.Sound('crash.wav').play()

          DISPLAYSURF.blit(background, (0,0))
          #DISPLAYSURF.fill(RED)
          scores = font_small.render(str(SCORE), True, YELLOW)
          DISPLAYSURF.blit(scores, (170, 500))
          #DISPLAYSURF.fill(RED)
          DISPLAYSURF.blit(game_over, (63,250))
          pygame.display.update()
          for entity in all_sprites:
                entity.kill() 
          time.sleep(3)
          pygame.quit()
          sys.exit()        
         
    pygame.display.update()
    FramePerSec.tick(FPS)

**Comment by SuhaniNarangu7745615** [comment]
You might need to install a library like "libmp3lame" or "libmp3lame-dev" using a package manager like brew (for macOS) or apt-get (for Linux).
or you can update your pygame version
