### ISSUE TITLE
Window won't open, pygame's sprite class is culprit(Fully FIXED!)

### ISSUE THREAD

**Issue by UrieW** [pygame/pygame#3932]
ALL FIXED, SEE POST BELOW!!!!!

- Windows 10
- Python 3.11.4
- SDL 2.26.4
- PyGame 2.4.0

Coded completely according to ShawCode's RPG tutorial(video 1&2), and the window wouldn't open,
with the terminal giving this error:

```PS C:\Users\Urie Wilson\Documents\UrieW\Projects\Game\Py\NAPy> & "C:/Program Files/Python311/python.exe" "c:/Users/Urie Wilson/Documents/UrieW/Projects/Game/Py/NAPy/src/main.py"
pygame 2.4.0 (SDL 2.26.4, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\Urie Wilson\Documents\UrieW\Projects\Game\Py\NAPy\src\main.py", line 71, in <module>
    g.new()
  File "c:\Users\Urie Wilson\Documents\UrieW\Projects\Game\Py\NAPy\src\main.py", line 34, in new  
    self.player = Player(self,1,2)
                  ^^^^^^^^^^^^^^^^
  File "c:\Users\Urie Wilson\Documents\UrieW\Projects\Game\Py\NAPy\src\scripts\entities\sprites.py", line 10, in __init__
    self.layer = PLAYER_LAYER
    ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pygame\sprite.py", line 239, in layer        
    if not self.alive():
           ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pygame\sprite.py", line 216, in alive        
    return bool(self.__g)
                ^^^^^^^^
AttributeError: 'Player' object has no attribute '_Sprite__g' 
```

I expected a custom window with a different icon, caption and a movable blue sprite on a black background.

The main class:
```
import pygame as pyg
from config import *
import sys
from dbs.colors import *
from scripts.entities.sprites import *

class Game:
    def __init__(self):
        pyg.init()
        self.screen = pyg.display.set_mode(WIN_SIZE)
        self.clock = pyg.time.Clock()
        self.icon = pyg.display.set_icon(pyg.image.load(APP_ICON))
        self.caption = pyg.display.set_caption('Nite Attack Demo')
        #self.font = pyg.font.Font("TW", 40)
        # make it run
        self.running = True

    def new(self):
        # is being played
        self.playing = True

        # init all sprite groups
        self.all_sprites = pyg.sprite.LayeredUpdates()
        self.heroes = pyg.sprite.LayeredUpdates()
        self.enemies = pyg.sprite.LayeredUpdates()
        self.items = pyg.sprite.LayeredUpdates()
        self.weps = pyg.sprite.LayeredUpdates()
        self.wepammo = pyg.sprite.LayeredUpdates()
        self.npcs = pyg.sprite.LayeredUpdates()
        self.bosses = pyg.sprite.LayeredUpdates()
        self.spfx = pyg.sprite.LayeredUpdates()
        
        # init player and create it
        self.player = Player(self,1,2)

    def events(self):
        # game event loop, stoppable by pyg.quit()
        for event in pyg.event.get():
            if event.type == pyg.QUIT:
                self.playing = False
                self.running = False

    def update(self):
        # game update screen
        self.all_sprites.update()
    
    def draw(self):
        # game loop draw
        self.screen.fill(BLACK)
        self.all_sprites.draw(self.screen)
        self.clock.tick(FPS)

        pyg.display.update()
    
    def main(self):
        # game loop, from start to finish
        while self.playing:
            self.events()
            self.update()
            self.draw()
        self.running = False
    
    def game_over(self):
        pass

    def intro_screen(self):
        pass

g = Game()
g.intro_screen()
g.new()

while g.running:
    g.main()
    g.game_over()

pyg.quit()
sys.exit()
```

The sprite class:
```
import pygame as pyg
from config import *
import math
import random
from dbs.colors import *

class Player(pyg.sprite.Sprite):
    def __init__(self, game, x, y):
        self.game = game
        self.layer = PLAYER_LAYER
        self.groups = self.game.all_sprites
        pyg.sprite.Sprite.__init__(self, self.groups)

        self.x = x * TILESIZE
        self.y = y * TILESIZE
        self.width = TILESIZE
        self.height = TILESIZE

        self.x_change = 0
        self.y_change = 0

        self.facing = 'down'

        self.image = pyg.Surface([self.width, self.height])
        self.image.fill(BLUE)

        self.rect = self.image.get_rect()
        self.rect.x = self.x
        self.rect.y = self.y

    def update(self):
        self.movement()

        self.rect.x += self.x_change
        self.rect.y += self.y_change
        self.x_change = 0
        self.y_change = 0

    def movement(self):
        keys = pyg.key.get_pressed()
        if keys == [pyg.K_LEFT]:
            self.x_change -= PLAYER_SPEED
            self.facing = 'left'
        if keys == [pyg.K_RIGHT]:
            self.x_change += PLAYER_SPEED
            self.facing = 'right'
        if keys == [pyg.K_UP]:
            self.y_change -= PLAYER_SPEED
            self.facing = 'up'
        if keys == [pyg.K_DOWN]:
            self.y_change += PLAYER_SPEED
            self.facing = 'down'

```

The config:
```
APP_ICON = 'src/BO Temp.png'

WIN_H = 600
WIN_W = 800

WIN_SIZE = (WIN_W, WIN_H)


FPS = 60

PLAYER_LAYER = 1
PLAYER_SPEED = 3
TILESIZE = 32

START_SCENE = 'debug'

ITEM_DB = 'items'
NITE_DB = 'bestiary'

LB_DB = 'leaderboards'
```

**Comment by UrieW** [comment]
Ignore this post, please, I forgot to add an underscore before "layer" in self.layer in sprites.py

Everything ran fine after I did that.

**Comment by UrieW** [comment]
A new problem arrived. Just as I fixed my game, either my keys didn't make the box move or it froze! The fixed version of sprites.py is in this.

**Comment by UrieW** [comment]
Fixed the problem, as I used keys ==[pyg.[insert key here]] before changing it to keys[pyg.[insertkeyhere]].

**Comment by Talvysh** [comment]
Close the thread since it's just coding issues on your side?

**Comment by UrieW** [comment]
Yes.
