### ISSUE TITLE
pygame v2.1.3 and newer cannot find `libmp3lame` or `libomp` in older macOS versions

### ISSUE THREAD

**Issue by carlosperate** [pygame/pygame#3941]
I can replicate the same issue with macOS 10.12 Sierra, 10.13 High sierra, and 10.14 Mojave (having a different issue testing 10.15 Catalina).

In a new virtual environment with Python 3.8 I install [pgzero](https://pypi.org/project/pgzero/) 1.2.1, which installs the latest pygame:
```
$ pip list
Package    Version
---------- -------
numpy      1.24.4
pgzero     1.2.1
pip        22.0.4
pygame     2.5.0
setuptools 56.0.0
```

pygamezero  might be invoking quite a lot of pygame code behind the scenes, but this was the simples way I was able to replicate:

```
$ touch empty_game.py 
$ python -m pgzero empty_game.py 
pygame 2.5.0 (SDL 2.28.0, Python 3.8.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/runner.py:2: RuntimeWarning: use mixer: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
(ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown))
  pygame.mixer.pre_init(frequency=22050, size=-16, channels=2)
Traceback (most recent call last):
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/__main__.py", line 1, in <module>
    from pgzero.runner import main
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/runner.py", line 2, in <module>
    pygame.mixer.pre_init(frequency=22050, size=-16, channels=2)
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libmp3lame.0.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libsndfile.1.0.34.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libmp3lame.0.dylib: cannot load 'libmp3lame.0.dylib' (load command 0x80000034 is unknown))
```
pygame cannot find `libmp3lame`.
And it's the same with pygame 2.40, 2.3.0 and 2.20.

But then with 2.1.3 it cannot find `libomp`:
```
$ pip install pygame==2.1.3
Collecting pygame==2.1.3
  Using cached pygame-2.1.3-cp38-cp38-macosx_10_9_x86_64.whl (12.8 MB)
Installing collected packages: pygame
  Attempting uninstall: pygame
    Found existing installation: pygame 2.2.0
    Uninstalling pygame-2.2.0:
      Successfully uninstalled pygame-2.2.0
Successfully installed pygame-2.1.3

$ pip list
Package    Version
---------- -------
numpy      1.24.4
pgzero     1.2.1
pip        22.0.4
pygame     2.1.3
setuptools 56.0.0

$ python -m pgzero empty_game.py 
pygame 2.1.3 (SDL 2.0.22, Python 3.8.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/runner.py:2: RuntimeWarning: use mixer: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libomp.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfluidsynth.3.1.1.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
(ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libomp.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfluidsynth.3.1.1.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown))
  pygame.mixer.pre_init(frequency=22050, size=-16, channels=2)
Traceback (most recent call last):
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/carlos/Downloads/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/__main__.py", line 1, in <module>
    from pgzero.runner import main
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pgzero/runner.py", line 2, in <module>
    pygame.mixer.pre_init(frequency=22050, size=-16, channels=2)
  File "/Users/carlos/.venv/lib/python3.8/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ImportError: dlopen(/Users/carlos/.venv/lib/python3.8/site-packages/pygame/mixer.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libomp.dylib
  Referenced from: /Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libfluidsynth.3.1.1.dylib
  Reason: no suitable image found.  Did find:
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown)
	/Users/carlos/.venv/lib/python3.8/site-packages/pygame/.dylibs/libomp.dylib: cannot load 'libomp.dylib' (load command 0x80000034 is unknown))
```

And with 2.1.2 it works:
```
$ pip install pygame==2.1.2
Collecting pygame==2.1.2
  Using cached pygame-2.1.2-cp38-cp38-macosx_10_9_x86_64.whl (8.9 MB)
Installing collected packages: pygame
  Attempting uninstall: pygame
    Found existing installation: pygame 2.1.3
    Uninstalling pygame-2.1.3:
      Successfully uninstalled pygame-2.1.3
Successfully installed pygame-2.1.2

$ pip list
Package    Version
---------- -------
numpy      1.24.4
pgzero     1.2.1
pip        22.0.4
pygame     2.1.2
setuptools 56.0.0

$ python -m pgzero empty_game.py
pygame 2.1.2 (SDL 2.0.18, Python 3.8.13)
Hello from the pygame community. https://www.pygame.org/contribute.html

$ 
```

**Comment by illume** [comment]
Should be fixed in pygame==2.5.1 (tested on 10.11, 10.12, and 10.13).
