### ISSUE TITLE
Failed assertion on exit: `python: Objects/typeobject.c:3818: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.`

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#4013]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Gentoo Linux amd64
- **Python version**: 3.11.5 (also reproduce with 3.10.13)
- **SDL version**: 2.28.3
- **PyGame version**: 94d6c94eae1df106909ca61c18224849cd1f042e
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

When Python is built with assertions enabled (`--with-assertions`), the test suite crashes on unsatisfied assertion:

```
$ python -m pygame.tests -v
<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.6.0.dev1 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
skipping pygame.tests.scrap_test (tag 'ignore')
skipping pygame.tests.sndarray_test (tag 'ignore')
skipping pygame.tests.surfarray_test (tag 'ignore')
loading pygame.tests.base_test
python: Objects/typeobject.c:3823: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.
Aborted (core dumped)
```

Interesting enough, the same seems to happen if the module is just imported, though the crash seems to happen just as the interpreter is about to exit:

```
$ python
Python 3.11.5 (main, Aug 29 2023, 06:14:32) [GCC 13.2.1 20230826] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.6.0.dev1 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> exit()
python: Objects/typeobject.c:3823: _PyType_Lookup: Assertion `!PyErr_Occurred()' failed.
Aborted (core dumped)
```

**Expected behavior:**

No crashes ;-).

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Configure CPython `--with-assertions` and build it.
2. Create a venv from the newly built Python.
3. `pip install .`
4. `python -c 'import pygame'

**Stack trace/error output/other error logs**

This is the from the "import pygame" interpreter:

```
Core was generated by `python -c import pygame'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fe4e92a2e2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fe4e9252cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe4e923b4ed in __GI_abort () at abort.c:79
#4  0x00007fe4e923b415 in __assert_fail_base (fmt=0x7fe4e93b8b98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fe4e984b2ea "!PyErr_Occurred()", file=file@entry=0x7fe4e9849f74 "Objects/typeobject.c", 
    line=line@entry=3823, function=function@entry=0x7fe4e984ed98 <__PRETTY_FUNCTION__.69> "_PyType_Lookup") at assert.c:92
#5  0x00007fe4e924b5e2 in __assert_fail (assertion=0x7fe4e984b2ea "!PyErr_Occurred()", file=0x7fe4e9849f74 "Objects/typeobject.c", 
    line=3823, function=0x7fe4e984ed98 <__PRETTY_FUNCTION__.69> "_PyType_Lookup") at assert.c:101
#6  0x00007fe4e9618842 in _PyType_Lookup (type=0x7fe4e9989aa0 <PyModule_Type>, name='quit') at Objects/typeobject.c:3823
#7  0x00007fe4e95f7a67 in _PyObject_GenericGetAttrWithDict (obj=<module at remote 0x7fe4e74eeca0>, name='quit', dict=0x0, suppress=0)
    at Objects/object.c:1271
#8  0x00007fe4e95f7e42 in PyObject_GenericGetAttr (obj=<module at remote 0x7fe4e74eeca0>, name='quit') at Objects/object.c:1368
#9  0x00007fe4e95f37a7 in module_getattro (m=0x7fe4e74eeca0, name='quit') at Objects/moduleobject.c:761
#10 0x00007fe4e95f6d8f in PyObject_GetAttr (v=<module at remote 0x7fe4e74eeca0>, name='quit') at Objects/object.c:916
#11 0x00007fe4e95f695d in PyObject_GetAttrString (v=<module at remote 0x7fe4e74eeca0>, name=0x7fe4e9b521cb "quit")
    at Objects/object.c:801
#12 0x00007fe4e9b4dc85 in pg_mod_autoquit (modname=0x7fe4e9b52236 "pygame.mixer") at src_c/base.c:314
#13 0x00007fe4e9b4e0d2 in _pg_quit () at src_c/base.c:481
#14 0x00007fe4e9b4e144 in pg_quit (self=<module at remote 0x7fe4e8525800>, _null=0x0) at src_c/base.c:503
#15 0x00007fe4e95f0fee in cfunction_vectorcall_NOARGS (func=<built-in method quit of module object at remote 0x7fe4e8525800>, 
    args=0x7fe4e9a8c690 <_PyRuntime+58928>, nargsf=0, kwnames=0x0) at Objects/methodobject.c:486
#16 0x00007fe4e9583e52 in _PyVectorcall_Call (tstate=0x7fe4e9aa6a18 <_PyRuntime+166328>, 
    func=0x7fe4e95f0ef5 <cfunction_vectorcall_NOARGS>, callable=<built-in method quit of module object at remote 0x7fe4e8525800>, 
    tuple=(), kwargs=0x0) at Objects/call.c:245
#17 0x00007fe4e958422a in _PyObject_Call (tstate=0x7fe4e9aa6a18 <_PyRuntime+166328>, 
    callable=<built-in method quit of module object at remote 0x7fe4e8525800>, args=(), kwargs=0x0) at Objects/call.c:328
#18 0x00007fe4e9584323 in PyObject_Call (callable=<built-in method quit of module object at remote 0x7fe4e8525800>, args=(), 
    kwargs=0x0) at Objects/call.c:355
#19 0x00007fe4e977cdb9 in atexit_callfuncs (state=0x7fe4e9a8d468 <_PyRuntime+62472>) at ./Modules/atexitmodule.c:98
#20 0x00007fe4e977ce6c in _PyAtExit_Call (interp=0x7fe4e9a8c698 <_PyRuntime+58936>) at ./Modules/atexitmodule.c:118
#21 0x00007fe4e973fd60 in Py_FinalizeEx () at Python/pylifecycle.c:1779
#22 0x00007fe4e9777c7c in Py_RunMain () at Modules/main.c:682
#23 0x00007fe4e9777d31 in pymain_main (args=0x7ffda6088fd0) at Modules/main.c:710
#24 0x00007fe4e9777df1 in Py_BytesMain (argc=3, argv=0x7ffda6089138) at Modules/main.c:734
#25 0x000055adca677185 in main (argc=3, argv=0x7ffda6089138) at ./Programs/python.c:15
(gdb) up 12
#12 0x00007fe4e9b4dc85 in pg_mod_autoquit (modname=0x7fe4e9b52236 "pygame.mixer") at src_c/base.c:314
314	        funcobj = PyObject_GetAttrString(module, "quit");
```

**Comment by illume** [comment]
Thanks @mgorny for the report. 
(It's fixed now, and will be in the next bugfix release.)

**Comment by mgorny** [comment]
Thank you. I'll retest when the next release is out, if you don't mind me doing so.

**Comment by mgorny** [comment]
Thanks, again. I've finally tested the changes and it seems that the original problem is fixed now. However, I'm getting another assertion failure; I've reported it as #4049.
