### ISSUE TITLE
pygame.tests.pixelcopy_test: `Fatal Python error: _Py_CheckSlotResult: Slot __delitem__ of type list succeeded with an exception set`

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#4049]
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Gentoo Linux amd64
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.11.6
- **SDL version** (e.g. SDL 2.0.12): 2.28.4
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 4065a11d5af91ec740b71f99d713e9f4f344a2ed
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

When running the test suite using Python built with `--with-assertions`, I'm getting the following crash. Note that it happens only if `numpy` is installed inside the environment.

```pytb
pygame 2.6.0.dev1 (SDL 2.28.4, Python 3.11.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
loading pygame.tests.pixelcopy_test
Fatal Python error: _Py_CheckSlotResult: Slot __delitem__ of type list succeeded with an exception set
Python runtime state: initialized

Current thread 0x00007fbf16609e40 (most recent call first):
  File "/usr/lib/python3.11/unittest/case.py", line 237 in handle
  File "/usr/lib/python3.11/unittest/case.py", line 766 in assertRaises
  File "/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_11/install/usr/lib/python3.11/site-packages/pygame/tests/pixelcopy_test.py", line 573 in test_map_array
  File "/usr/lib/python3.11/unittest/case.py", line 579 in _callTestMethod
  File "/usr/lib/python3.11/unittest/case.py", line 623 in run
  File "/usr/lib/python3.11/unittest/case.py", line 678 in __call__
  File "/usr/lib/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.11/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.11/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.11/unittest/runner.py", line 217 in run
  File "/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_11/install/usr/lib/python3.11/site-packages/pygame/tests/test_utils/test_runner.py", line 281 in run_test
  File "/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_11/install/usr/lib/python3.11/site-packages/pygame/tests/test_utils/run_tests.py", line 222 in run
  File "/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_11/install/usr/lib/python3.11/site-packages/pygame/tests/test_utils/run_tests.py", line 346 in run_and_exit
  File "/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_11/install/usr/lib/python3.11/site-packages/pygame/tests/__main__.py", line 143 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 37)
```

**Expected behavior:**

No crash ;-).

**Steps to reproduce:**

1. Build Python `--with-assertions`.
2. Create and enter a venv, e.g.: `python -m venv .venv; . .venv/bin/activate`
3. `pip install cython; python setup.py cython_only`
4. `pip install .`
5. `pip install numpy`
6. `python -m pygame.tests pixelcopy`

**Stack trace/error output/other error logs**

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f444e0a2e2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f444e052cc2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f444e03b4ed in __GI_abort () at abort.c:79
#4  0x00007f444e54253c in fatal_error_exit (status=-1) at Python/pylifecycle.c:2626
#5  0x00007f444e542a25 in fatal_error (fd=2, header=0, prefix=0x0, msg=0x0, status=-1) at Python/pylifecycle.c:2807
#6  0x00007f444e542c4f in _Py_FatalErrorFormat (func=0x7f444e62dcc0 <__func__.18> "_Py_CheckSlotResult", 
    format=0x7f444e62d9a0 "Slot %s of type %s succeeded with an exception set") at Python/pylifecycle.c:2857
#7  0x00007f444e384744 in _Py_CheckSlotResult (obj=[], slot_name=0x7f444e623ce1 "__delitem__", success=1) at Objects/call.c:96
#8  0x00007f444e36100d in PySequence_DelItem (s=[], i=0) at Objects/abstract.c:1979
#9  0x00007f444d1d5578 in pgSurface_UnlockBy ()
   from /tmp/pygame/.venv/lib/python3.11/site-packages/pygame/surflock.cpython-311-x86_64-linux-gnu.so
#10 0x00007f444d1d53b4 in pgSurface_Unlock ()
   from /tmp/pygame/.venv/lib/python3.11/site-packages/pygame/surflock.cpython-311-x86_64-linux-gnu.so
#11 0x00007f444c011c47 in map_array ()
   from /tmp/pygame/.venv/lib/python3.11/site-packages/pygame/pixelcopy.cpython-311-x86_64-linux-gnu.so
#12 0x00007f444e3f22f1 in cfunction_call (func=<built-in method map_array of module object at remote 0x7f444c363560>, 
    args=(<numpy.ndarray at remote 0x7f442c153b70>, <numpy.ndarray at remote 0x7f442c150630>, <pygame.surface.Surface at remote 0x7f442ce7c9b0>), kwargs={}) at Objects/methodobject.c:553
#13 0x00007f444e3852cc in _PyObject_Call (tstate=0x7f444e8a9218 <_PyRuntime+166328>, 
    callable=<built-in method map_array of module object at remote 0x7f444c363560>, 
    args=(<numpy.ndarray at remote 0x7f442c153b70>, <numpy.ndarray at remote 0x7f442c150630>, <pygame.surface.Surface at remote 0x7f442ce7c9b0>), kwargs={}) at Objects/call.c:343
#14 0x00007f444e38532c in PyObject_Call (callable=<built-in method map_array of module object at remote 0x7f444c363560>, 
    args=(<numpy.ndarray at remote 0x7f442c153b70>, <numpy.ndarray at remote 0x7f442c150630>, <pygame.surface.Surface at remote 0x7f442ce7c9b0>), kwargs={}) at Objects/call.c:355
#15 0x00007f444e4e40cc in do_call_core (tstate=0x7f444e8a9218 <_PyRuntime+166328>, 
    func=<built-in method map_array of module object at remote 0x7f444c363560>, 
    callargs=(<numpy.ndarray at remote 0x7f442c153b70>, <numpy.ndarray at remote 0x7f442c150630>, <pygame.surface.Surface at remote 0x7f442ce7c9b0>), kwdict={}, use_tracing=0) at Python/ceval.c:7315
#16 0x00007f444e4dc36e in _PyEval_EvalFrameDefault (tstate=0x7f444e8a9218 <_PyRuntime+166328>, frame=0x7f444e900df0, throwflag=0)
    at Python/ceval.c:5367
#17 0x00007f444e4bfa5a in _PyEval_EvalFrame (tstate=0x7f444e8a9218 <_PyRuntime+166328>, frame=0x7f444e900b28, throwflag=0)
    at ./Include/internal/pycore_ceval.h:73
--Type <RET> for more, q to quit, c to continue without paging--c
#18 0x00007f444e4e1162 in _PyEval_Vector (tstate=0x7f444e8a9218 <_PyRuntime+166328>, func=0x7f442c126c00, locals=0x0, 
    args=0x7fff9ceb85a0, argcount=2, kwnames=0x0) at Python/ceval.c:6425
#19 0x00007f444e385531 in _PyFunction_Vectorcall (func=<function at remote 0x7f442c126c00>, stack=0x7fff9ceb85a0, nargsf=2, 
    kwnames=0x0) at Objects/call.c:393
#20 0x00007f444e38893f in _PyObject_VectorcallTstate (tstate=0x7f444e8a9218 <_PyRuntime+166328>, 
    callable=<function at remote 0x7f442c126c00>, args=0x7fff9ceb85a0, nargsf=2, kwnames=0x0) at ./Include/internal/pycore_call.h:92
#21 0x00007f444e38914b in method_vectorcall (method=<method at remote 0x7f444925b7c0>, args=0x7f442c188d48, nargsf=1, kwnames=0x0)
    at Objects/classobject.c:89
#22 0x00007f444e384e5b in _PyVectorcall_Call (tstate=0x7f444e8a9218 <_PyRuntime+166328>, func=0x7f444e388ef7 <method_vectorcall>, 
    callable=<method at remote 0x7f444925b7c0>, 
    tuple=(<TextTestResult(failfast=False, failures=[], errors=[], testsRun=6, skipped=[], expectedFailures=[], unexpectedSuccesses=[], shouldStop=False, buffer=True, tb_locals=False, _stdout_buffer=<_io.StringIO at remote 0x7f442c12e7a0>, _stderr_buffer=<_io.StringIO at remote 0x7f442c12e710>, _original_stdout=<_io.TextIOWrapper at remote 0x7f444d31fed0>, _original_stderr=<_io.TextIOWrapper at remote 0x7f444d3fc040>, _mirrorOutput=False, stream=<_WritelnDecorator(stream=<_io.StringIO at remote 0x7f442c12e680>) at remote 0x7f442c15b510>, showAll=False, dots=True, descriptions=True, _newline=True, _testRunEntered=True, _moduleSetUpFailed=False, _previousTestClass=<type at remote 0x55d90a6fb000>) at remote 0x7f444c302c10>,), kwargs={}) at Objects/call.c:245
#23 0x00007f444e385233 in _PyObject_Call (tstate=0x7f444e8a9218 <_PyRuntime+166328>, callable=<method at remote 0x7f444925b7c0>, 
    args=(<TextTestResult(failfast=False, failures=[], errors=[], testsRun=6, skipped=[], expectedFailures=[], unexpectedSuccesses=[], shouldStop=False, buffer=True, tb_locals=False, _stdout_buffer=<_io.StringIO at remote 0x7f442c12e7a0>, _stderr_buffer=<_io.StringIO at remote 0x7f442c12e710>, _original_stdout=<_io.TextIOWrapper at remote 0x7f444d31fed0>, _original_stderr=<_io.TextIOWrapper at remote 0x7f444d3fc040>, _mirrorOutput=False, stream=<_WritelnDecorator(stream=<_io.StringIO at remote 0x7f442c12e680>) at remote 0x7f442c15b510>, showAll=False, dots=True, descriptions=True, _newline=True, _testRunEntered=True, _moduleSetUpFailed=False, _previousTestClass=<type at remote 0x55d90a6fb000>) at remote 0x7f444c302c10>,), kwargs={}) at Objects/call.c:328
[…]
```

**Comment by u7493339** [comment]
Hi, i would like to investigate this issue please
