### ISSUE TITLE
pygame pycamera fails on restarts

### ISSUE THREAD

**Issue by drmod3** [pygame/pygame#405]
#!/usr/bin/env python3 

        #by GitHub: drmod3
        #extremely easy and powerful webcam show & capture for RaspberryPi
        #once running, no issues

        #has issues on about 1 of 6 attempted restarts
        #no way to detect if already running or successful start

        #Application is remote and loses power frequently.
        #After issues, tested pyCamera for robustness.
        #From Python IDLE, click >run then >run module, repeatedly.
        #Halts running display.
        #Attempted restarts give various errors shown below.
        #After error, next attempt restarts and runs properly

        #Needs error recovery before start()

        #Raspberry Pi 3B
        #Raspbian Stretch
        #Python 3.5.3
        #PyGame

        # import the relevant libraries
import time
import pygame
import pygame.camera
from pygame.locals import *
import g                                                  #global variable module

pygScreen = pygame.display.set_mode([800,420])  #size of display
pygame.init()

pygame.camera.init()
cam = pygame.camera.Camera('/dev/video0',(640,480)) #default webcam location
cam.start()                                                  #start webcam
camRun = True                                          #normally set/cleared by call

while camRun:
    try:                                                          #error exception handling
        if cam.query_image():                         #is a new image available?
            g.image = cam.get_image()            #grab image
            pygScreen.blit(g.image, (0, 0))        #what to show where x,y
        #   pygame.image.save(g.image,'/home/pi/camera/101.bmp') #slows down some

            pygame.display.flip()                       #refresh pygScreen
            time.sleep(.04)                                 #about 25 FPS

    except Exception as e:                             #all exceptions
        print('loop= EXCEPT', e)

cam.stop()

#============= RESTART: /home/pi/mod/apps/camera movie 180218.py =============
#Traceback (most recent call last):
#  File "/home/pi/mod/apps/camera movie 180218.py", line 22, in <module>
#    cam.start()                                     #start webcam
#SystemError: Cannot open '/dev/video0': 16, Device or resource busy
#>>> 
#============= RESTART: /home/pi/mod/apps/camera movie 180218.py =============
#
#============= RESTART: /home/pi/mod/apps/camera movie 180218.py =============
#Traceback (most recent call last):
#  File "/home/pi/mod/apps/camera movie 180218.py", line 22, in <module>
#    cam.start()                                     #start webcam
#SystemError: ioctl(VIDIOC_S_FMT) failure: no supported formats
#>>> 
#============= RESTART: /home/pi/mod/apps/camera movie 180218.py =============

#Another captured error is loop= Except: 'str' object has no attribute 'query_image'.no supported formats.

#timing is a real problem
#for sure too fast loop causes errors
#normal refresh rate requires start outside loop and kept running 

#if power loss or interrupted, opens with error about 1 in 6 restarts.
#then next open is ok

#putting cam.start & stop in loop causes errors ++ no supported formats

**Comment by drmod3** [comment]
Resolved by using try/except inside a while loop.
while True:
    try:
        cam.start()
        break
    except Exception as e:
        print(start= Except', e)
        time.sleep(1)
