### ISSUE TITLE
PyGame completely broken on Raspberry Pi Bullseye Lite with official Raspberry Pi touch LCD

### ISSUE THREAD

**Issue by neuron-whisperer** [pygame/pygame#4135]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Raspberry Pi OS, Bullseye Lite
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.2
- **SDL version** (e.g. SDL 2.0.12): 2.0.14+dfsg2-3+deb11u1
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.5.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): Raspberry Pi 3B+; official Raspberry Pi touch LCD

**Current behavior:**

pygame cannot run in any Raspberry Pi OS with the official Raspberry Pi touch LCD. Pygame will fail with complaints about no video drivers being available, and also complaining that "/dev/dri cannot be opened or is not available."

Specifying a video driver (via os.putenv('SDL_VIDEODRIVER', 'some_value')) does not solve the problem, as no values work: not directfb, fbcon, svgalib, etc. Specifying any value (other than 'dummy') causes pygame to complaint that the specified video driver is not available. Some people have recommended os.putenv('SDL_FBDEV', '/dev/fb1'), but this has no effect.

As it stands, it is completely impossible to run pygame 2.x on Raspberry Pi with the official Raspberry Pi touch LCD.

**Expected behavior:**

pygame should find a video driver and run, just like it used to in pygame 1.9.x.

**Screenshots**

n/a

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Install Raspberry Pi OS Bullseye Lite.
2. Install sdl2 via apt.
3. Install pygame via pip.
4. Run pygame.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.init()
pygame.display.init()
```

**Stack trace/error output/other error logs**

```
<frozen importlib._bootstrap>:228: RuntimeWarning: Your system is neon capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.5.2 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
The path /dev/dri/ cannot be opened or is not available
The path /dev/dri/ cannot be opened or is not available
The path /dev/dri/ cannot be opened or is not available
The path /dev/dri/ cannot be opened or is not available
Traceback (most recent call last):
  File "/home/pi/Frame/frame.py", line 392, in <module>
    App.start()
  File "/home/pi/Frame/frame.py", line 20, in start
    app = App()
  File "/home/pi/Frame/frame.py", line 28, in __init__
    pygame.display.init()
pygame.error: No available video device
```

**Comment by d3vluqman** [comment]
@neuron-whisperer 
how were you able to resolve this?
just encountered an almost identical error on Ubuntu 24.04
`<frozen importlib._bootstrap>:488: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.5.2 (SDL 2.30.0, Python 3.12.3)`

**Comment by GordonZed** [comment]
I get the same warning, but it still runs, so the "Your system is avx2/neon capable but..." RuntimeWarning is probably unrelated to your display driver issue.

What display driver are you running (legacy? kms? fkms?). If you don't know, run `sudo raspi-config` and I believe it's Advanced Options, then GL Driver (or something to that effect; consult documentation for RasPi OS).

Do you have OpenGL development packages installed? Should be something like `libopengl-dev` although if that were the issue, I would suspect you to get an error like "Library not found" rather than the display driver error.

**Comment by neuron-whisperer** [comment]
Reporting that nearly a year later, pygame 2.x remains unusable on any version of Raspberry Pi OS Lite due to the general impossibility of installing, or even recompiling from source, a working version of SDL2.

I've tried this repeatedly on a variety of Raspberry Pi OS Lite distros (32-bit vs. 64-bit; Bullseye vs. Bookworm) and devices (Raspberry Pi Zero 2W and Raspberry Pi 5). All fail at the same point, and there is apparently no interest in fixing this problem.

The latest version of pygame that runs on any Raspberry Pi OS Lite device is 1.9.6 (last build in 2019, over five years ago). Also, that version of pygame can only be built using Python 3.8.19 - any Python version after that raises fatal build errors due to breaking syntax changes. If further changes cause either of those packages to be uninstallable - as will likely occur at some point - pygame will be rendered completely unusable on the Raspberry Pi OS Lite.

In essence - **Raspberry Pi OS Lite is a dead platform for pygame 2.x.** Caveat developer.

**Comment by SpudGunMan** [comment]
I think all pi is broken at this point I cant get any connected displays working on Pi3 or Pi4 bunch of OS they all crashed last night and that was that

**Comment by SpudGunMan** [comment]
figured out a work around!
find your display, likely fb0
`ls -l /dev/fb*`
allow all access
`sudo chmod a+rw /dev/fb0`
