### ISSUE TITLE
Unusual error (error: failed to create renderer) when using pygame.SCALED

### ISSUE THREAD

**Issue by jamespblloyd-uwa** [pygame/pygame#4144]
I am having issues getting `pygame.SCALED` flag to work in `pygame.display.set_mode()`. I keep getting an unexpected error that I cannot find anyone else having via a Google search. The error message is:
`pygame.error: failed to create renderer`
The code that I am calling is:
class Game:
   ```
 def __init__(self):
        self.screen = pygame.display.set_mode((WIN_WIDTH, WIN_HEIGHT), flags = pygame.SCALED) #Trying to scale up the screen. 
```
And it works fine if I have no flags in `pygame.display.set_mode()` or I have the `pygame.RESIZABLE` flag alone. Any thoughts?
More details:
I am running MacOS Sonoma 14.2.1 (M1 Pro chip). I have installed SDL2 etc via brew. When I check display modes I see these, which I understand to mean that SDL2 stuff is working (but I am new to all of this).
```
print(pygame.display.list_modes())
[(2560, 1440), (2048, 1152), (1920, 1200), (1920, 1080), (1680, 1050), (1600, 1200), (1600, 900), (1440, 900), (1344, 1008), (1344, 756), (1280, 1024), (1280, 960), (1280, 720), (1024, 768), (1024, 576), (960, 600), (960, 540), (840, 525), (800, 600)]
```
My version of Pygame and Python are:
```
>>> print(pygame.__version__)
2.5.2
python --version
Python 3.12.1
```

**Comment by semibran** [comment]
been getting a similar error on windows, seems to work fine with 2.4.0 but not 2.5.0 (though this may be a completely separate issue)

**Comment by Namitha-KS** [comment]
Have you tried manually scaling it with the `pygame._sdl2` (mentioned in the doc) or you could try something like this:

```python
import pygame
import pygame._sdl2 as sdl2
```
```python
flags = pygame.SCALED
```
```python
initial_scale_factor = 3 # <-- adjustable
window = sdl2.Window.from_display_module()
window.size = (WIN_WIDTH * initial_scale_factor, WIN_HEIGHT * initial_scale_factor)
window.position = sdl2.WINDOWPOS_CENTERED
window.show()
```
This works without the `pygame.RESIZABLE` module and should give a scaled window with whatever initial scale factor you want

If you encounter issues with `_sdl2` or need a more stable approach, try manual scaling within Pygame's core API using surface transformations or resizing techniques.

**Comment by jamespblloyd-uwa** [comment]
> been getting a similar error on windows, seems to work fine with 2.4.0 but not >=2.5.0 (though this may be a completely separate issue)

Thanks but when I try a new conda/mamba env with an older pygame version, it still does not work for me:
`pygame 2.4.0 (SDL 2.28.5, Python 3.8.18)`

**Comment by jamespblloyd-uwa** [comment]
> Have you tried manually scaling it with the `pygame._sdl2` (mentioned in the doc) or you could try something like this:
> 
> ```python
> import pygame
> import pygame._sdl2 as sdl2
> ```
> 
> ```python
> flags = pygame.SCALED
> ```
> 
> ```python
> initial_scale_factor = 3 # <-- adjustable
> window = sdl2.Window.from_display_module()
> window.size = (WIN_WIDTH * initial_scale_factor, WIN_HEIGHT * initial_scale_factor)
> window.position = sdl2.WINDOWPOS_CENTERED
> window.show()
> ```
> 
> This works without the `pygame.RESIZABLE` module and should give a scaled window with whatever initial scale factor you want
> 
> If you encounter issues with `_sdl2` or need a more stable approach, try manual scaling within Pygame's core API using surface transformations or resizing techniques.

Thanks for getting back to me. I can successfully `import pygame._sdl2 as sdl2` so that is a nice start. I do not know how to integrate this into my existing code:
```
initial_scale_factor = 3 # <-- adjustable
window = sdl2.Window.from_display_module()
window.size = (WIN_WIDTH * initial_scale_factor, WIN_HEIGHT * initial_scale_factor)
window.position = sdl2.WINDOWPOS_CENTERED
window.show()
```
Does this replace any of my existing code like:
```
self.screen = pygame.display.set_mode((WIN_WIDTH, WIN_HEIGHT), flags = pygame.SCALED)
    def draw(self):
        self.screen.fill(BLACK)
        self.all_sprites.draw(self.screen)
        self.clock.tick(FPS)
        pygame.display.update()
```
I am not sure how window interacts with screen and the calling of screen in my code (sorry new to pygame and any coding other than for simple bioinformatics).

**Comment by Namitha-KS** [comment]
Yes, you can replace the line where you set the display mode with the SDL2 code. Here's how you can integrate it into your existing code:

```python
import pygame
import pygame._sdl2 as sdl2

BLACK = (0, 0, 0)
WIN_WIDTH, WIN_HEIGHT = (256, 128)
FPS = 60

class Game:
    def __init__(self):
        pygame.init()

        flags = pygame.SCALED
        flags |= pygame.RESIZABLE  # optional

        pygame.display.set_mode((WIN_WIDTH, WIN_HEIGHT), flags | pygame.HIDDEN)

        initial_scale_factor = 3  # <-- adjustable
        window = sdl2.Window.from_display_module()
        window.size = (WIN_WIDTH * initial_scale_factor, WIN_HEIGHT * initial_scale_factor)
        window.position = sdl2.WINDOWPOS_CENTERED
        window.show()

        self.screen = pygame.Surface((WIN_WIDTH, WIN_HEIGHT))
        self.clock = pygame.time.Clock()  
        self.all_sprites = pygame.sprite.Group()  

    def draw(self):
        self.screen.fill(BLACK)
        self.all_sprites.draw(self.screen)

game = Game()

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    game.draw()
    pygame.display.flip()
    game.clock.tick(FPS)
pygame.quit()

```

I use VSCode as my IDE and this code works for me. Pygame is an amazing library to start with and it is fun. About the window interaction, try referring to youtube tutorials.

**Comment by jamespblloyd-uwa** [comment]
Thanks for getting back to me [Namitha-KS](https://github.com/Namitha-KS). 

I can run the above code without an error message and I get a small black window. But when I added the relevant code to my larger script, I get the same error:
`python main.py
pygame 2.5.2 (SDL 2.28.5, Python 3.12.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/jameslloyd/Documents/Main_Work_JPBL/Non_work/Hobbies/Game_dev/pygame/Building_RPG_Game_example/My_first_game_attempt/main.py", line 149, in <module>
    game = Game()
           ^^^^^^
  File "/Users/jameslloyd/Documents/Main_Work_JPBL/Non_work/Hobbies/Game_dev/pygame/Building_RPG_Game_example/My_first_game_attempt/main.py", line 43, in __init__
    pygame.display.set_mode((WIN_WIDTH, WIN_HEIGHT), flags | pygame.HIDDEN)
pygame.error: failed to create renderer`

I am not sure what `pygame.display.set_mode((WIN_WIDTH, WIN_HEIGHT), flags | pygame.HIDDEN)` is supposed to be doing here as it contains the `pygame.SCALED` that always causes the error for me. When I remove this line from my code, or just remove the flags, I just get a super large black screen. So I am not sure what I am doing wrong here but sadly it has not solved the issue. 

Thank you again for trying!

**Comment by Namitha-KS** [comment]
This error message typically pops in due to some compatibility issues with the os or versions of the libraries. To resolve the issue you may,
1. Try upgrading the pygame version
2. Ensure graphics driver is up-to-date
3. Try using different flags. In the above code, `.HIDDEN` means that the window will be hidden after creation. This is often used when you want to create a window off-screen, perform some operations, and then show it later.
4. Try different windowing system. may be `pygame.window.WindowMacOSX`
