### ISSUE TITLE
Test failures against NumPy 2.0.0rc2

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#4239]
When running the test suite against NumPy 2.0.0rc2, I'm getting the following test regressions (note that I've deliberately replaced all import-related skips with reraises, to detect uses of removed stuff):

```pytb
======================================================================
ERROR: test_map_array (test.pixelcopy_test.PixelCopyTestWithArrayNumpy.test_map_array)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygame/test/pixelcopy_test.py", line 537, in test_map_array
    from numpy import array, zeros, uint8, int32, alltrue
ImportError: cannot import name 'alltrue' from 'numpy' (/tmp/pygame/.venv/lib/python3.11/site-packages/numpy/__init__.py)

======================================================================
ERROR: sndarray_test (unittest.loader._FailedTest.sndarray_test)
----------------------------------------------------------------------
ImportError: Failed to import test module: sndarray_test
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pygame/test/sndarray_test.py", line 3, in <module>
    from numpy import int8, int16, uint8, uint16, float32, array, alltrue
ImportError: cannot import name 'alltrue' from 'numpy' (/tmp/pygame/.venv/lib/python3.11/site-packages/numpy/__init__.py)


======================================================================
ERROR: surfarray_test (unittest.loader._FailedTest.surfarray_test)
----------------------------------------------------------------------
ImportError: Failed to import test module: surfarray_test
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 162, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pygame/test/surfarray_test.py", line 4, in <module>
    from numpy import (
ImportError: cannot import name 'alltrue' from 'numpy' (/tmp/pygame/.venv/lib/python3.11/site-packages/numpy/__init__.py)
```

This is Python 3.11.9, Gentoo Linux amd64, git clone as of a780e206a1686acdee2dda159cafe9d34f68053a. I've created a venv, then did:

```
pip install cython numpy==2.0.0rc2
python setup.py build_ext
pip install -e .
python -m pygame.tests
```

**Comment by mgorny** [comment]
Once I replace all uses of `alltrue()` with `all()`, and skip the crashing test (bug #4049), I'm getting the following failures:

```pytb
======================================================================
ERROR: test_array (test.sndarray_test.SndarrayTest.test_array)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygame/test/sndarray_test.py", line 44, in test_array
    check_array(-8, 2, [[0, -0x80], [-0x64, 0x64], [0x25, -0x50], [0xFF, 0]])
  File "/tmp/pygame/test/sndarray_test.py", line 26, in check_array
    srcarr = array(test_data, self.array_dtypes[size])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer 255 out of bounds for int8

======================================================================
ERROR: test_make_sound (test.sndarray_test.SndarrayTest.test_make_sound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygame/test/sndarray_test.py", line 87, in test_make_sound
    check_sound(-8, 2, [[0, -0x80], [-0x64, 0x64], [0x25, -0x50], [0xFF, 0]])
  File "/tmp/pygame/test/sndarray_test.py", line 70, in check_sound
    srcarr = array(test_data, self.array_dtypes[size])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer 255 out of bounds for int8

======================================================================
ERROR: test_samples (test.sndarray_test.SndarrayTest.test_samples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygame/test/sndarray_test.py", line 126, in test_samples
    check_sample(-8, 2, [[0, -0x80], [-0x64, 0x64], [0x25, -0x50], [0xFF, 0]])
  File "/tmp/pygame/test/sndarray_test.py", line 110, in check_sample
    samples[...] = test_data
    ~~~~~~~^^^^^
OverflowError: Python integer 255 out of bounds for int8

======================================================================
ERROR: test_pixels2d (test.surfarray_test.SurfarrayModuleTest.test_pixels2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygame/test/surfarray_test.py", line 588, in test_pixels2d
    self._fill_array2d(arr, surf)
  File "/tmp/pygame/test/surfarray_test.py", line 116, in _fill_array2d
    arr[:5, :6] = surf.map_rgb(palette[1])
    ~~~^^^^^^^^
OverflowError: Python integer -16114116 out of bounds for uint32

----------------------------------------------------------------------
```

**Comment by illume** [comment]
Oh, numpy 2. Cool. Thanks for the report.
 
I see this migration guide…  https://numpy.org/devdocs/numpy_2_0_migration_guide.html

**Comment by illume** [comment]
@mattip I don't know for certain if "numpy.alltrue" missing is unexpected in numpy 2? Just a heads up.

**Comment by illume** [comment]
Thanks @mgorny I made a bug report to numpy about alltrue, and mentioned a few folks there. Good catch!

**Comment by mattip** [comment]
`np.alltrue` has been deprecated since NumPy 1.25 released June 2023. Are tests here running with deprecation warnings active?

**Comment by illume** [comment]
The issue with the array tests seems to be that numpy now raises an error if values are out of range, instead of interpreting them as values for that data type. In other words there is no implicit cast now.

numpy 1.x
```py
import
numpy.array(numpy.array([[0, -128], [-100, 100], [37, -80], [255, 0]], numpy.int8))
array([[   0, -128],
       [-100,  100],
       [  37,  -80],
       [  -1,    0]], dtype=int8)
```

numpy 2.x
```py
import
numpy.array(numpy.array([[0, -128], [-100, 100], [37, -80], [255, 0]], numpy.int8))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python integer 255 out of bounds for int8
```

This is also not mentioned in the numpy 2 Migration guide and such... so I made an issue here: https://github.com/numpy/numpy/issues/26596

**Comment by illume** [comment]
I tested with a number of external array using tools, and pygame examples and they all seem fine with np2.

**Comment by mgorny** [comment]
Thanks!
