### ISSUE TITLE
Issues running Pygame on my New MacBook Pro

### ISSUE THREAD

**Issue by H1tman1978** [pygame/pygame#4340]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (): macOS Sonoma 14.6.1 
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.11.10
- **SDL version** (e.g. SDL 2.0.12): 2.28.4
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.6.0
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): Apple M3 Pro chip

**Current behavior:**

I'm testing a new game that I am creating it crashed on running (see traceback below:)

Tested the code on a Windows machine and it runs fine so I'm thinking it might be an issue with my Mac environment and the traceback points to that as well. I also ran the test script below and it works just fine. The issue, I believe, lies in the window creation or somewhere right before.

**Expected behavior:**

I was hoping to have the game launch, but alas here we are. 

**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Using a MacBook with the specs above, create a pygame program
2. Try to test your program by running your 'main.py' file from the terminal
3. It crashes with the above traceback.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.init()
print("Hello, world")
```

Here's my main.py file (full code can be found on my [GitHub repository](https://github.com/H1tman1978/SuperMarcoBros)):

```python
"""
main.py
Entry point for Super Marco Bros game using PyGame.
"""

import pygame
import sys
from settings import WIDTH, HEIGHT, FPS, SKY_BLUE
from player import Player
from platform import Platform
from enemy import Enemy
from item import Item

# Initialize PyGame
pygame.init()

# Set up the game window
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Super Marco Bros")

# Set up the game clock
clock = pygame.time.Clock()

# Create player instance
player = Player()

# Create platforms
platforms = pygame.sprite.Group()
platform1 = Platform(100, HEIGHT - 100, 200, 20)
platform2 = Platform(400, HEIGHT - 200, 200, 20)
platform3 = Platform(600, HEIGHT - 150, 200, 20)
platforms.add(platform1, platform2, platform3)

# Create enemies
enemies = pygame.sprite.Group()
enemy1 = Enemy(200, HEIGHT - 100, 50, 50, 2)
enemy2 = Enemy(500, HEIGHT - 150, 50, 50, 2)
enemies.add(enemy1, enemy2)

# Create items (bad shroom)
items = pygame.sprite.Group()
bad_shroom = Item(300, HEIGHT - 300, 30, 30)
items.add(bad_shroom)

# Sprite group for easier management
all_sprites = pygame.sprite.Group()
all_sprites.add(player)
all_sprites.add(platforms)
all_sprites.add(enemies)
all_sprites.add(items)


def check_collisions():
    """Handle all collisions in the game."""
    # Player-platform collision
    platform_collisions = pygame.sprite.spritecollide(player, platforms, False)
    if platform_collisions:
        if player.velocity_y > 0:  # If the player is falling
            player.rect.bottom = platform_collisions[0].rect.top
            player.velocity_y = 0
            player.is_jumping = False

    # Player-enemy collision
    enemy_collision = pygame.sprite.spritecollide(player, enemies, False)
    if enemy_collision:
        if player.velocity_y > 0:  # Player is falling (jumping on enemy)
            enemy_collision[0].kill()  # Defeat enemy
        else:
            print("Player hit by enemy!")  # Placeholder for player damage

    # Player-item collision (bad shroom)
    item_collision = pygame.sprite.spritecollide(player, items, True)
    if item_collision:
        print("Bad shroom collected!")  # Placeholder for bad shroom effect
        player.reverse_controls()  # Reverse controls for the player


def main():
    """Main game loop."""
    running = True
    while running:
        # Event handling
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # Update game state (player, enemies, etc.)
        all_sprites.update()

        # Check for collisions
        check_collisions()

        # Drawing code
        screen.fill(SKY_BLUE)  # Fill the background with sky blue color

        # Draw all sprites (player, etc.)
        all_sprites.draw(screen)

        # Update the display
        pygame.display.flip()

        # Cap the frame rate
        clock.tick(FPS)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()

```

**Stack trace/error output/other error logs**

```bash
tonyrolfe@tonys-mbp SuperMarcoBros % python3 src/main.py 
Traceback (most recent call last):
  File "/Users/tonyrolfe/code/Python/SuperMarcoBros/src/main.py", line 6, in <module>
    import pygame
  File "/Users/tonyrolfe/.local/lib/python3.11/site-packages/pygame/__init__.py", line 291, in <module>
    import pygame.pkgdata
  File "/Users/tonyrolfe/.local/lib/python3.11/site-packages/pygame/pkgdata.py", line 25, in <module>
    from pkg_resources import resource_stream, resource_exists
  File "/Users/tonyrolfe/.pyenv/versions/3.11.10/lib/python3.11/site-packages/pkg_resources/__init__.py", line 969, in <module>
    class Environment:
  File "/Users/tonyrolfe/.pyenv/versions/3.11.10/lib/python3.11/site-packages/pkg_resources/__init__.py", line 973, in Environment
    self, search_path=None, platform=get_supported_platform(),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tonyrolfe/.pyenv/versions/3.11.10/lib/python3.11/site-packages/pkg_resources/__init__.py", line 191, in get_supported_platform
    plat = 'macosx-%s-%s' % ('.'.join(_macos_vers()[:2]), m.group(3))
                                      ^^^^^^^^^^^^^
  File "/Users/tonyrolfe/.pyenv/versions/3.11.10/lib/python3.11/site-packages/pkg_resources/__init__.py", line 366, in _macos_vers
    version = platform.mac_ver()[0]
              ^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'mac_ver'

```

Any help would be most appreciated. Also, if this isn't a simple "hey use Python v 3.x.x with pygame v 2.x.x" case, I'll take this on as my initial contribution to pygame and see if I can't find the bug and fix it. Just let me know...

**Comment by H1tman1978** [comment]
Thanks Gabe! Didn't even think of that. That worked!
