### ISSUE TITLE
installing pygame error (deprecated library)

### ISSUE THREAD

**Issue by myNameDoesntExist** [pygame/pygame#4375]
**Environment:**

- **Operating system**:Windows
- **Python version**: Pypy 3.10
- **SDL version**:idk
- **PyGame version**:havent installed yet
- **Relevant hardware**:self-built pc

**Current behavior:**

Can't install `setuptools._distutils.msvccompiler`

**Expected behavior:**

Pygame must install smoothly in Pypy with the instructions to compile Pygame for Windows (as instructed _very_ clearly)

**Screenshots**

![image](https://github.com/user-attachments/assets/46588f87-6085-4101-9672-15662bc96eb2)

![image](https://github.com/user-attachments/assets/5de1256c-8333-4b0e-a200-8bf2576748ba)

**Steps to reproduce:**

1.Use pypy
2.Compile pygame for windows
3.At the step `py -m buildconfig --download`, which I changed `py` to `pypy` to install it for pypy, it will break.

**Stack trace/error output/other error logs**

Still keeping the original `py` still breaks
```
py -m buildconfig --download
Using WINDOWS configuration...

WARNING:root:Using the SDL libraries in "prebuilt-x64".
Path for SDL: prebuilt-x64\SDL2-2.28.4
...Library directory for SDL: prebuilt-x64/SDL2-2.28.4/lib/x64
...Include directory for SDL: prebuilt-x64/SDL2-2.28.4/include
Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
Path for PORTMIDI: prebuilt-x64
...Library directory for PORTMIDI: prebuilt-x64/lib
...Include directory for PORTMIDI: prebuilt-x64/include
DLL for SDL2: prebuilt-x64/SDL2-2.28.4/lib/x64/SDL2.dll
DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
DLL for portmidi: prebuilt-x64/lib/portmidi.dll
Path for FREETYPE: prebuilt-x64
...Library directory for FREETYPE: prebuilt-x64/lib
...Include directory for FREETYPE: prebuilt-x64/include
Path for PNG not found.
...Found include dir but no library dir in prebuilt-x64.
Path for JPEG not found.
...Found include dir but no library dir in prebuilt-x64.
DLL for freetype: prebuilt-x64/lib/freetype.dll
DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll
Traceback (most recent call last):
  File "C:\Windows\System32\pygame\buildconfig\vstools.py", line 4, in <module>
    from distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'distutils.msvccompiler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 336, in configure
    from . import vstools
  File "C:\Windows\System32\pygame\buildconfig\vstools.py", line 6, in <module>
    from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Windows\System32\pygame\buildconfig\vstools.py", line 4, in <module>
    from distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'distutils.msvccompiler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Windows\System32\pygame\buildconfig\__main__.py", line 2, in <module>
    main()
    ~~~~^^
  File "C:\Windows\System32\pygame\buildconfig\config.py", line 234, in main
    deps = CFG.main(**kwds, auto_config=auto)
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 493, in main
    return setup_prebuilt_sdl2(prebuilt_dir)
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
    DEPS.configure()
    ~~~~~~~~~~~~~~^^
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 338, in configure
    from buildconfig import vstools
  File "C:\Windows\System32\pygame\buildconfig\vstools.py", line 6, in <module>
    from setuptools._distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'setuptools._distutils.msvccompiler'
```
For everyone to not ask if I did compile the first steps wrong, I installed Git and more things and it was successful
```
C:\Windows\System32>set DISTUTILS_USE_SDK=1

C:\Windows\System32>set MSSdk=1

C:\Windows\System32>git clone https://github.com/pygame/pygame.git
fatal: destination path 'pygame' already exists and is not an empty directory.

C:\Windows\System32>cd pygame

C:\Windows\System32\pygame>pypy -m pip install setuptools requests wheel numpy -U
Requirement already satisfied: setuptools in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (75.1.0)
Requirement already satisfied: requests in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (2.32.3)
Requirement already satisfied: wheel in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (0.44.0)
Requirement already satisfied: numpy in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\wandu\appdata\local\programs\pypy\pypy3107317\lib\site-packages (from requests) (2024.8.30)
```

**Comment by myNameDoesntExist** [comment]
maybe i installed as admin?? but if i dont git wont be happy about me getting pygame

**Comment by oloketuyimoyosi** [comment]
Did you fix it?

**Comment by cistuff** [comment]
I'm having the same error on Python 3.14.0. Did you find a solution?

**Comment by oloketuyimoyosi** [comment]
Yeah. I don't think they have uploaded a building wheel for python 3.14.0 but they have for 3.12 below I think. Make sure u clear everything u download (all the building wheels) so that it won't give you an error.
