### ISSUE TITLE
_sdl2.touch module crash

### ISSUE THREAD

**Issue by Gedili** [pygame/pygame#4406]
**Environment:**

- **Operating system**: Windows 10 Pro (22H2)
- **Python version**: 3.11.9
- **SDL version**: 2.28.4
- **PyGame version**: 2.6.1
- **Relevant hardware**: HP probook x360 435 G10 laptop with touchscreen

**Current behavior:**

get_num_fingers() fails after releasing touch from the touchscreen.

**Steps to reproduce:**

Run the following code (simplified version of https://github.com/pygame/pygame/blob/main/test/touch_test.py), touch the screen, then release your finger.

**Test code**

```python
import pygame
from pygame._sdl2 import touch

pygame.display.init()
screen = pygame.display.set_mode((800, 600))
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    num_devices = pygame._sdl2.touch.get_num_devices()
    if num_devices > 0:
        first_device = pygame._sdl2.touch.get_device(0)
        num_fingers = pygame._sdl2.touch.get_num_fingers(first_device)
        if num_fingers > 0:
            data = pygame._sdl2.touch.get_finger(first_device, 0)
            print(f"finger - {data}")
pygame.display.quit()
```

**Error output**

```
pygame 2.6.1 (SDL 2.28.4, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
finger - {'id': 75, 'x': 0.6150000095367432, 'y': 0.5049999952316284, 'pressure': 1.0}
...
finger - {'id': 75, 'x': 0.6150000095367432, 'y': 0.5049999952316284, 'pressure': 1.0}
finger - {'id': 75, 'x': 0.6150000095367432, 'y': 0.5049999952316284, 'pressure': 1.0}
Traceback (most recent call last):
  File "xxxxxxxxx\touchscreen.py", line 14, in <module>
    num_fingers = pygame._sdl2.touch.get_num_fingers(first_device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error
```

No info provided in the exception: 
```
Exception has occurred: error
exception: no description
  File "xxxxxxxxx\touchscreen.py", line 14, in <module>
    num_fingers = pygame._sdl2.touch.get_num_fingers(first_device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
When running the code from https://github.com/pygame/pygame/blob/main/test/touch_test.py, the following error is raised in the same conditions (after releasing the touch)
```
Exception has occurred: error
Surface doesn't have a colorkey
  File "xxxxxxxxx\touchscreen.py", line 124, in <module>
    num_fingers = pygame._sdl2.touch.get_num_fingers(first_device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pygame.error: Surface doesn't have a colorkey
```

**Comment by Osaidgit** [comment]
Why you use this

**Comment by Osaidgit** [comment]
![Screenshot_20241220_055718](https://github.com/user-attachments/assets/6bef8f08-7c05-4580-90f9-bc7a1df7af15)
![Screenshot_20241220_055723](https://github.com/user-attachments/assets/f6c77690-c416-4451-96a5-ce67fe70e20d)
![Screenshot_20241220_055737](https://github.com/user-attachments/assets/7b94a369-e866-48d7-8a67-8e9dd1b99f4a)
![Screenshot_20241220_055746](https://github.com/user-attachments/assets/3acef202-2f44-4d15-a6b7-5661571bd8ce)
![Screenshot_20241220_055755](https://github.com/user-attachments/assets/a5b5a9e1-01c5-4c64-a67f-4288608d54c9)
![Screenshot_20241220_055806](https://github.com/user-attachments/assets/1f40339e-4acc-4a35-8f98-f07753cdd791)

![Screenshot_20241220_055813](https://github.com/user-attachments/assets/18be8ce2-32b8-4c89-90aa-6c18d4b8ba58)
![Screenshot_20241220_055818](https://github.com/user-attachments/assets/1e35503d-a8ce-4c9f-b305-b40be73399f1)
![Screenshot_20241220_055838](https://github.com/user-attachments/assets/5e56e56a-cd14-4a09-b31e-4a6b52568ee5)
![Screenshot_20241220_055852](https://github.com/user-attachments/assets/58df6939-902c-4d6f-ba34-022c785a6c54)
![Screenshot_20241220_055859](https://github.com/user-attachments/assets/dca43d0e-370e-412e-9759-25d7e4e70124)
