### ISSUE TITLE
i was installing pygame in my command prompt(windows 32 bit) and it gave me this error C:\Users\ralph>py -m pip install -U pygame --user

### ISSUE THREAD

**Issue by oooobi** [pygame/pygame#452]
C:\Users\ralph>py -m pip install -U pygame --user
Traceback (most recent call last):
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\__init__.py", line 21, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_vendor\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\ralph\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_vendor\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ValueError: source code string cannot contain null bytes
 
This is the error I got when I was downloading the pygame in te command prompt(Windows 10 32-bit

**Comment by MyreMylar** [comment]
Using:

`py -m pip install -U pygame --user`

On windows works fine now. Just tried it again to be sure.

Recommend this is closed as it's two years old.

**Comment by MyreMylar** [comment]
Closing as above.
