### ISSUE TITLE
Broken Pygame install in Pypy 2.7/Windows 10

### ISSUE THREAD

**Issue by fbuchinger** [pygame/pygame#453]
Not sure whether to open this bug in the Pygame or PyPy project, but here is my console output:

Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\temp\pypy>pypy -V
Python 2.7.13 (ab0b9caf307d, Apr 24 2018, 17:52:36)
[PyPy 6.0.0 with MSC v.1500 32 bit]

C:\temp\pypy>pypy -m ensurepip
Requirement already satisfied: setuptools in c:\temp\pypy\site-packages
Requirement already satisfied: pip in c:\temp\pypy\site-packages

C:\temp\pypy>pypy.exe -m pip install pygame --pre
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/ba/96/82495010a3daf94f579c6fc60a2466212057a3db38ce7927f01f32941968/pygame-1.9.4.dev0.tar.gz (4.9MB)
    100% |################################| 4.9MB 146kB/s
    Complete output from command python setup.py egg_info:

    WARNING, No "Setup" File Exists, Running "config.py"
    Using WINDOWS configuration...

    Path for SDL not found.
    Too bad that is a requirement! Hand-fix the "Setup"
    Path for FONT not found.
    Path for IMAGE not found.
    Path for MIXER not found.
    Path for PNG not found.
    Path for JPEG not found.
    Path for PORTMIDI not found.
    Path for COPYLIB_tiff not found.
    Path for COPYLIB_z not found.
    Path for COPYLIB_vorbis not found.
    Path for COPYLIB_ogg not found.

    If you get compiler errors during install, doublecheck
    the compiler flags in the "Setup" file.

    Continuing With "setup.py"
    Error with the "Setup" file,
    perhaps make a clean copy from "Setup.in".
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "c:\users\fbuchi~1\appdata\local\temp\pip-build-kt83dc\pygame\setup.py", line 165, in <module>
        extensions = read_setup_file('Setup')
      File "C:\temp\pypy\lib-python\2.7\distutils\extension.py", line 168, in read_setup_file
        line = expand_makefile_vars(line, vars)
      File "C:\temp\pypy\lib-python\2.7\distutils\sysconfig_cpython.py", line 387, in expand_makefile_vars
        s = s[0:beg] + vars.get(m.group(1)) + s[end:]
    TypeError: unsupported operand type(s) for +: 'str' and 'NoneType'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\fbuchi~1\appdata\local\temp\pip-build-kt83dc\pygame\
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Note: This bug was also opened on the [pypy issue tracker](https://bitbucket.org/pypy/pypy/issues/2835/broken-pygame-install-in-pypy-27-windows)

**Comment by DevDorian** [comment]
Having the same issue. Console Output ...

Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\frank>python -V
Python 3.7.0

C:\Users\frank>python -m ensurepip
Looking in links: C:\Users\frank\AppData\Local\Temp\tmp4ktjtar_
Requirement already satisfied: setuptools in c:\users\frank\appdata\local\programs\python\python37\lib\site-packages (39.0.1)
Requirement already satisfied: pip in c:\users\frank\appdata\local\programs\python\python37\lib\site-packages (10.0.1)

C:\Users\frank>python -m pip install pygame --user
Collecting pygame
  Using cached https://files.pythonhosted.org/packages/61/06/3c25051549c252cc6fde01c8aeae90b96831370884504fe428a623316def/pygame-1.9.3.tar.gz
    Complete output from command python setup.py egg_info:


    WARNING, No "Setup" File Exists, Running "config.py"
    Using WINDOWS configuration...

    Path for SDL not found.
    Too bad that is a requirement! Hand-fix the "Setup"
    Path for FONT not found.
    Path for IMAGE not found.
    Path for MIXER not found.
    Path for PNG not found.
    Path for JPEG not found.
    Path for PORTMIDI not found.
    Path for COPYLIB_tiff not found.
    Path for COPYLIB_z not found.
    Path for COPYLIB_vorbis not found.
    Path for COPYLIB_ogg not found.

    If you get compiler errors during install, doublecheck
    the compiler flags in the "Setup" file.


    Continuing With "setup.py"
    Error with the "Setup" file,
    perhaps make a clean copy from "Setup.in".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\frank\AppData\Local\Temp\pip-install-krdbelxu\pygame\setup.py", line 165, in <module>
        extensions = read_setup_file('Setup')
      File "C:\users\frank\appdata\local\programs\python\python37\lib\distutils\extension.py", line 171, in read_setup_file
        line = expand_makefile_vars(line, vars)
      File "C:\users\frank\appdata\local\programs\python\python37\lib\distutils\sysconfig.py", line 407, in expand_makefile_vars
        s = s[0:beg] + vars.get(m.group(1)) + s[end:]
    TypeError: can only concatenate str (not "NoneType") to str

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\frank\AppData\Local\Temp\pip-install-krdbelxu\pygame\

**Comment by illume** [comment]
I think this is related to the `DEBUG =` in Setup. In older distutils that worked. Adding a space at the end of it should fix it I guess.

Once we have binary wheels for windows pypy, this should work ok.

**Comment by dlon** [comment]
This could probably be fixed now, as FreeType has been added back. Doesn't work for SDL2, though.

#663
