### ISSUE TITLE
FreeBSD build issue

### ISSUE THREAD

**Issue by ndowens** [pygame/pygame#473]
Using UNIX configuration...

Hunting dependencies...
SDL     : found 1.2.15
FONT    : found
IMAGE   : found
MIXER   : found
PNG     : found
JPEG    : found
SCRAP   : found
Traceback (most recent call last):
  File "config.py", line 173, in <module>
    if __name__ == '__main__': main()
  File "config.py", line 161, in main
    deps = CFG.main()
  File "/wrkdirs/usr/ports/devel/py-pygame/work-py36/pygame-1.9.4/config_unix.py", line 232, in main
    d.configure(incdirs, libdirs)
AttributeError: 'NoneType' object has no attribute 'configure'
*** Error code 1

Stop.

**Comment by illume** [comment]
Thanks for the report!

Sorry, I didn't get a chance to try 1.9.4 with freebsd before the release. We don't have a freebsd maintainer anymore. Also we don't have any build robots checking things in Continuous integration for freebsd (Travis CI and Appveyor don't support it).

cheers,

**Comment by ndowens** [comment]
Any idea how to fix it?  What I could change to make a patch for it. I’m not a programmer so I’m not sure how to fix issue

**Comment by ndowens** [comment]
All I know is that someone value of None is being returned

**Comment by ndowens** [comment]
I believe this to be a possible issue on other platforms than just FreeBSD. For some reason configure seems to be returning None or d is returning/receieving None

**Comment by ndowens** [comment]
I have fixed it. Will link to patches. Though in summary it’s about the code to check if portaudio is portmidi part

**Comment by ndowens** [comment]
https://pastebin.com/PwFBbeT7 
https://pastebin.com/UJzFGetL

**Comment by ndowens** [comment]
I was thinking, maybe you could add if os=freebsd skip that section I had to delete?

**Comment by illume** [comment]
Thanks for that :) Ah, it seems that portmidi does not exist for freebsd (from my limited searching). I've made a patch. Can you please try that?

**Comment by ndowens** [comment]
Oh another I had to fix was I think in config where it says if linux import extra file that contains camera because it has import <linux dir/file.h>

**Comment by ndowens** [comment]
**src/_camera.c:213:36: error: use of undeclared identifier 'V4L2_CID_HFLIP'
    if (v4l2_get_control(self->fd, V4L2_CID_HFLIP, &value))
                                   ^
src/_camera.c:216:36: error: use of undeclared identifier 'V4L2_CID_VFLIP'
    if (v4l2_get_control(self->fd, V4L2_CID_VFLIP, &value))
                                   ^
src/_camera.c:219:36: error: use of undeclared identifier 'V4L2_CID_BRIGHTNESS'
    if (v4l2_get_control(self->fd, V4L2_CID_BRIGHTNESS, &value))
                                   ^
src/_camera.c:244:36: error: use of undeclared identifier 'V4L2_CID_HFLIP'
    if (v4l2_set_control(self->fd, V4L2_CID_HFLIP, hflip))
                                   ^
src/_camera.c:247:36: error: use of undeclared identifier 'V4L2_CID_VFLIP'
    if (v4l2_set_control(self->fd, V4L2_CID_VFLIP, vflip))
                                   ^
src/_camera.c:250:36: error: use of undeclared identifier 'V4L2_CID_BRIGHTNESS'
    if (v4l2_set_control(self->fd, V4L2_CID_BRIGHTNESS, brightness))
                                   ^
6 errors `generated.**

The camera patch doesn't work

**Comment by illume** [comment]
Oops. So, I will have to set up a FreeBSD box to test with.

Thanks for trying it out.

**Comment by ndowens** [comment]
The other one works fine just not camera patch

**Comment by illume** [comment]
I set up a freebsd box... 

Then I had some issues with `DEBUG = ` needing an extra space, and the pypm trying to be compiled. 
```
sudo pkg install devel/sdl12 git python36 py36-numpy-1.14.3,1 v4l_compat-1.6.3_1
```

I had to install this package for the camera module to compile.
`sudo pkg install v4l_compat-1.6.3_1`

So, the config should detect the linux video header, and also it should detect portmidi not being there and not compile the pypm file if it's not there.

**Comment by ndowens** [comment]
Yup seems to work :) :+1:

**Comment by illume** [comment]
I'm glad it's working :)

Reopening the issue, because I'm still planning on patching pygame so it works out of the box on FreeBSD.
