### ISSUE TITLE
Cleanup / wiki / dev-documentation ?

### ISSUE THREAD

**Issue by e1000** [pygame/pygame#494]
Hello,

I wanted to get involved in Pygame development process, but found it not so easy : 
 
* I could find nowhere which Python and SDL versions are supported
* A lot of code (eg in `src/*c` and `src/_pygame.h`) refers to Python < 2.7 or SDL < 1.2.4
*  It is refered to  unittest of Python3 in [lets-write-unit-test](http://renesd.blogspot.com/2018/07/draft-of-lets-write-unit-test.html) , which could be misleading if we support *Python2.7* (a lot of new stuff has been introduced since then)
* It seems to me, it would be nice to note somewhere why we don't use *ctypes*, *Cython* or *CFFI* ? 
* Isn't there somewhere a numpy dependency ? which version ?
* Maybe we could move some old stuff in the https://www.pygame.org/wiki/
  (Py3 migration, 2010 ..., etc) in a subfolder *Archive* ? 

* more code cleanup ? (specially the `test/` folder and files need some attention it seems to me ; eg  `test/util/svn_log_to_whatsnew.py` , also what is the meaning of `test/util/build_page/index.php`) 
* SDL2 is in a single ticket #174, can it really be done in  one step, or should we split it in several tickets ?
* Maybe be can drop Python2 support for Pygame2? 
* I tried to run the tests, but get two crashes (ok I should run `setup.py` I guess, but then I'm confused, what's the meaning of `installed pygame.tests` referred in the [wiki/Hacking](https://www.pygame.org/wiki/Hacking))
```bash
$ python3 -m pygame.tests
/usr/bin/python3: Error while finding module specification for 'pygame.tests' (ImportError: No module named 'pygame')

# and the other way : 

$ python3 test/__main__.py 
Traceback (most recent call last):
  File "test/__main__.py", line 32, in <module>
    from test.test_utils.run_tests import run_and_exit
  File "/home/eea/src/pygame/test/__init__.py", line 40, in <module>
    from test.test_utils.run_tests import run
  File "/home/eea/src/pygame/test/test_utils/__init__.py", line 5, in <module>
    import tempfile, sys, pygame, time, os
ImportError: No module named 'pygame'
```
* Oh yes, and I found many very old open branches in github, maybe we can close them ?
 
Feel free to close this ticket though, if you think it's inappropriate or obsolete...

**Comment by illume** [comment]
Thanks for this list. It's very valuable to address each of these things in a way that will also be helpful for others later.

For example we could improve the test runner so that if it gets an ImportError there, we could leave a message which says 'Please install pygame first before running the tests'.


But to answer a few things now.
- there is a soft dependency on numpy, it's not required. Not sure what versions we support exactly... but 'several years old' to current version is the answer.
- SDL 1.2.15 and SDL 2 (partial) are the SDL versions.
- there are ports of pygame to cffi, ctypes, and cython. In short the reasons are: cffi is (mostly) faster on pypy, but slower on cpython. ctypes is slower everywhere. ctypes and cffi do not work on platforms like iOS. CPython API didn't used to work on pypy, but now it does(which was one of the major benefits for using cffi or ctypes).  pygame includes other C code than just SDL. You generally need to know how C code works to use ctypes and cffi. Knowledge of C is far more common than knowledge of ctypes, cffi, or cython. You need to compile various C libraries anyway.
- Yeah, the SDL2 issue needs to be cleaned up and planned with various other smaller issues linked from that issue. There is also a '2' milestone. One thing to get going here is to find the various places in the source code with `#warning`s about SDL2 implementation missing and create issues for them. Another thing would be to make issues for various failing tests, and for where apps fail when run with SDL2.
- python 2 support is still important at this time. Probably by 2020 we could remove support for it when cpython does. But we will see how that goes.
- yeah, most of the old branches could be closed.

**Comment by illume** [comment]
I removed all the branches except the default one. Also, added some tasks at the top of this issue. 

The pygame 2 issue has been update with a task to create issues for all SDL2 things. https://github.com/pygame/pygame/issues/174

**Comment by e1000** [comment]
Thank you for this feedback and the checklist.
 
What's the situation for support of **Python < 2.7** ? If it's not supported anymore, then we can add a point to the check list or a ticket, doing the cleanup in the code. 

Same for **SDL_mixer** which does not have the same version numbers as SDL it seems (cf old SDL_mixer versions in `scr/mixer.c`)

**Comment by illume** [comment]
Good ideas about the wiki and dependencies :)

**Comment by e1000** [comment]
also, we could maybe remove the obsolete tags in github `1.9.x`, x < 5 ?

**Comment by marespiaut** [comment]
Hello,

I'm not sure if this is the right place to comment about this issue, but after a quick reading of the pygame.org website, I thought a *lot* of text should be either *removed* or *rewritten in a very simplified way*.

I would like to make some pull request, but I'm not sure everything is centralized on this repository.

Also, I'm in support for a radical and heavy cleaning of the source code for Pygame 2. The website still mentions platforms that are completely outdated and of no appeal for end users, such as Maemo, gp2x, BeOS, etc.

Dropping support for Python 2.x is, in my humble opinion, a very good idea ; Pygame should aim at the least common denominator of Python 3 for Ubuntu (the most popular GNU/Linux distribution, and *de facto* standard) — because the latest version of Python 3 is easy to install on both Windows and macOS, but GNU/Linux distributions are “stuck” with the version available in the packages unless they make extra effort to upgrade it.

**Comment by e1000** [comment]
Hello, I think we can wait for *Python3* some more 16 months ;) Meanwhile, we have enough to do with SDL and other stuff. Btw, we haven't even yet decided / documented that we can drop Python2.2 (yes, `scr_c/_pygame.h` l 811 ), yet alone *Python < 2.7* ...

Here one more checklist that I would like to be solved : 

- [ ] Decide to drop  *Python < 2.7* and document it
- [ ] Document supported *SDL_mixer* version
- [ ] add wiki page for Debian https://www.pygame.org/wiki/CompileDebian and add a link in https://www.pygame.org/wiki/Compilation
- [ ] Add some help to compile into cwd, not into `/usr/local/lib/python2.7/dist-packages/`

Indeed, I don't want to or can't unistall my Debian-stable version of *Pygame*  . And both following ideas  
do not work (at least at first try) : 
```
$ python setup.py install --prefix  ~/src/pygame/pygame
$ python setup.py install --install-dir ~/src/pygame/pygame
```

**Comment by illume** [comment]
Hi.

some quick replies...

- anything on the website under /wiki is edited through the web, and the stuff under /docs is edited in the pygame repository (in the docs directory) with git.
- Python 2 support is not going to be dropped right now. There's too many people who need this (including me), and I think it makes most sense to revisit the issue again when CPython drops support for it.
- you can install into a virtual env, or into user packages with pip and `--user`. If those other install options don't work, it might be worth making a separate issue for those.
