### ISSUE TITLE
Erorr installing pygame through Pipenv

### ISSUE THREAD

**Issue by emilmirzayev** [pygame/pygame#586]
Windows 10, python 3.6.5, pipenv 2018.13.10
Hi. When trying install pygame I get the following error:
```
Installing pygame…
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/ea/00/c8c0432a84fce4061fc9799747ea205805e247c559db1b71ac9f768e38e0/pygame-1.9.4.post1.tar.gz (3.0MB)
    Complete output from command python setup.py egg_info:


    WARNING, No "Setup" File Exists, Running "config.py"
    Using WINDOWS configuration...

    Path for SDL not found.
    Too bad that is a requirement! Hand-fix the "Setup"
    Path for FONT not found.
    Path for IMAGE not found.
    Path for MIXER not found.
    Path for PNG not found.
    Path for JPEG not found.
    Path for PORTMIDI not found.
    Path for COPYLIB_tiff not found.
    Path for COPYLIB_z not found.
    Path for COPYLIB_vorbis not found.
    Path for COPYLIB_ogg not found.

    If you get compiler errors during install, doublecheck
    the compiler flags in the "Setup" file.


    Continuing With "setup.py"
    Error with the "Setup" file,
    perhaps make a clean copy from "Setup.in".
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Emil\AppData\Local\Temp\pip-install-16h53mlx\pygame\setup.py", line 203, in <module>
        extensions = read_setup_file('Setup')
      File "c:\users\emil\appdata\local\programs\python\python36\Lib\distutils\extension.py", line 171, in read_setup_file
        line = expand_makefile_vars(line, vars)
      File "c:\users\emil\appdata\local\programs\python\python36\Lib\distutils\sysconfig.py", line 407, in expand_makefile_vars
        s = s[0:beg] + vars.get(m.group(1)) + s[end:]
    TypeError: must be str, not NoneType

    ----------------------------------------

Error:  An error occurred while installing pygame!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Emil\AppData\Local\Temp\pip-install-16h53mlx\pygame\

This is likely caused by a bug in pygame. Report this to its maintainers.
```
Any info on what is the problem here?

**Comment by illume** [comment]
Hello,

thanks for reporting this.

Can you please try to install `pygame==1.9.4`?

There is a pygame 1.9.4.post1 (released today), which has source only. pip gets the 1.9.4 wheels, but Pipenv doesn't apparently.

**Comment by emilmirzayev** [comment]
Thank you. Changing the version seemed to help and it is installed successfully now.

**Comment by illume** [comment]
I'm trying to track down an issue related to this...
if you have a few moments... I wonder what version of pip you are using?
`py -m pip --version`
