### ISSUE TITLE
SDL2 surface tests fail

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#600]
```
loading test.surface_test
FE.E.....E...........F...................s.......s.F..............
======================================================================
ERROR: test_blit_blend (test.surface_test.SurfaceBlendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 1940, in test_blit_blend
    [masks[1], masks[2], masks[0], masks[3]])
ValueError: Invalid mask values

======================================================================
ERROR: test_blit_blend_rgba (test.surface_test.SurfaceBlendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 2031, in test_blit_blend_rgba
    (masks[1], masks[2], masks[3], masks[0]))
ValueError: Invalid mask values

======================================================================
ERROR: test_array_interface_masks (test.surface_test.SurfaceGetBufferTest)
Test non-default color byte orders on 3D views
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 1518, in test_array_interface_masks
    pygame.Surface(sz, 0, 24, masks).get_view, '3')
ValueError: Invalid mask values

======================================================================
FAIL: test_GET_PIXELVALS (test.surface_test.SurfaceBlendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 2098, in test_GET_PIXELVALS
    self.assertEqual(dst.get_at((0, 0)), (0, 0, 0, 255))
AssertionError: (0, 0, 0, 128) != (0, 0, 0, 255)

======================================================================
FAIL: test_overlap_check (test.surface_test.SurfaceSelfBlitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 2241, in test_overlap_check
    self.assertEqual(surf.get_at(test_posn), rectc_right)
AssertionError: (128, 64, 32, 255) != (255, 255, 255, 255)

======================================================================
FAIL: test_image_convert_bug_131 (test.surface_test.SurfaceTypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 674, in test_image_convert_bug_131
    self.assertRaises(pygame.error, im2.convert, 8)
AssertionError: error not raised by convert

----------------------------------------------------------------------
Ran 66 tests in 5.537s

FAILED (failures=3, errors=3)
```

**Comment by dlon** [comment]
`test_blanket_alpha` fails again:

```
======================================================================
FAIL: test_blanket_alpha (test.surface_test.SurfaceSelfBlitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 2323, in test_blanket_alpha
    self._assert_same(surf, comp)
  File "C:\Users\David\Documents\dev\pygame\test\surface_test.py", line 2243, in _assert_same
    a.get_bitsize())))
AssertionError: (255, 0, 0, 255) != (85, 146, 0, 255) : (255, 0, 0, 255) != (85, 146, 0, 255), bpp: 8
```

**Comment by dlon** [comment]
In SDL2, `set_alpha()` works even if the surface has an alpha channel. Should that behavior should be kept even if it isn't backward-compatible?
