### ISSUE TITLE
PyPy: Rect test failures

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#669]
With pypy:

```
======================================================================
ERROR: test_clamp (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 750, in test_clamp
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_clip (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 757, in test_clip
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_copy (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 729, in test_copy
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_fit (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 778, in test_fit
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_inflate (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 743, in test_inflate
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_move (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 736, in test_move
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_union (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 764, in test_union
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
ERROR: test_unionall (test.rect_test.SubclassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 771, in test_unionall
    self.assertTrue(mr1.an_attribute)
AttributeError: 'pygame.Rect' object has no attribute 'an_attribute'

======================================================================
FAIL: testEquals (test.rect_test.RectTypeTest)
check to see how the rect uses __eq__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\rect_test.py", line 513, in testEquals
    self.assertEqual(r6, r2)
AssertionError: <rect(0, 0, 0, 0)> != <rect(10, 20, 30, 40)>
```

**Related Docs:** https://www.pygame.org/docs/ref/rect.html

**Comment by illume** [comment]
@dr0id ran into these and similar rect failures on pypy with a new pr.

We need to ask for help from pypy, and report a big there.

**Comment by illume** [comment]
The pypy issue tracker is here now: https://foss.heptapod.net/pypy/pypy/-/issues

**Comment by dr0id** [comment]
I wonder if this has to do with the freelist implementation in rect.c for pypy, see: [rect.c](https://github.com/pygame/pygame/blob/2056b6deb277dd818aba2016edf5741bb0fa02ba/src_c/rect.c#L169)

**Comment by Starbuck5** [comment]
It's 100% the freelist implementation. When I use the freelist implementation on CPython, I get the same test failures.
