### ISSUE TITLE
joystick.get_name() can give an exception "invalid utf-8 character"

### ISSUE THREAD

**Issue by TonyWhitley** [pygame/pygame#674]
Happens with "Logitech® G27 Shifter" and others that have ® in the name.  Sample code:
```
    pygame.init()
    self.num_controllers = pygame.joystick.get_count()
    for j in range(self.num_controllers):
      _j = pygame.joystick.Joystick(j)
      _j.get_name()
```
Gives UnicodeError

pygame 1.9.4  Python 3.6 on Windows 10 64bit

**Comment by TonyWhitley** [comment]
Apologies for slow reply, this doesn't occur for me because all of my controllers have simple text names so I have to ask my users to test it.  Anyway, with that change my program outputs

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Logitech® G27 Shifter
Logitech® G27 Shifter
Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1705, in __call__
File "Configurer.py", line 85, in change_dropdown
File "wheel.py", line 64, in selectController
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 8: invalid start byte
Logitech® G27 Shifter

wheel.py line 64 is where my function get_name returns.  For completeness, here is the function

  def get_name(self, controller):
    """
    pygame's get_name() can give an exception "invalid utf-8 character"
    """
    _name = "Error getting controller name"
    try:
      _name = controller.get_name()
    except UnicodeError as e:
      print(e.object.decode(locale.getdefaultlocale()[1]))
      _name = "Unicode error getting controller name"
    except:
      _name = "Other error getting controller name"
      print("Unexpected error:", sys.exc_info()[0])
    return _name

that's called from

  def __init__(self):
    pygame.init()

    self.num_controllers = pygame.joystick.get_count()
    if self.num_controllers < 1:
        self.error_string = "No Controllers"
        self.error = True
        return

    self.controllerNames = []
    for j in range(self.num_controllers):
      _j = pygame.joystick.Joystick(j)
      self.controllerNames.append(self.get_name(_j))

(Markdown styling is doing odd things.)

I tried poking "Logitech® G27 Shifter" in my program as a return value and everything is happy so I'm fairly confident that get_name() is the culprit.
