### ISSUE TITLE
Drawing with draw_aaline() in draw_py.py can cause an error

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#801]
Some lines drawn with `draw_aaline()` in `draw_py.py` can cause an `IndexError` or a `TypeError`.

Running this code will produce an `IndexError`.
```
# File: aaline_draw_py_test1.py
import pygame
from pygame.draw_py import draw_aaline as aaline

pygame.init()
WIDTH, HEIGHT = 100, 100
screen = pygame.display.set_mode((WIDTH, HEIGHT))
aaline(screen, (255, 0, 0), (0, 0), (0, HEIGHT - 1), 1)
pygame.quit()
```

The above code gives the following output.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "aaline_draw_py_test1.py", line 8, in <module>
    aaline(screen, (255, 0, 0), (0, 0), (0, HEIGHT - 1), 1)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 389, in draw_aaline
    _draw_aaline(surf, color, line[0], line[1], line[2], line[3], blend)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 331, in _draw_aaline
    draw_two_pixel(S_x, S_y, rest)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 311, in draw_two_pixel
    draw_pixel(surf, x, y, color, factor * inv_frac(float_x), blend)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 37, in draw_pixel
    other_col = surf.get_at((x, y)) if blend else (0, 0, 0, 0)
IndexError: pixel index out of range
```

Running this code will produce an `TypeError`.
```
# File: aaline_draw_py_test2.py
import pygame
from pygame.draw_py import draw_aaline as aaline

pygame.init()
WIDTH, HEIGHT = 100, 100
screen = pygame.display.set_mode((WIDTH, HEIGHT))
aaline(screen, (255, 0, 0), (0, HEIGHT - 1), (WIDTH, HEIGHT), 1)
pygame.quit()
```

The above code gives the following output.
```
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "aaline_draw_py_test2.py", line 8, in <module>
    aaline(screen, (255, 0, 0), (0, HEIGHT - 1), (WIDTH, HEIGHT), 1)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 389, in draw_aaline
    _draw_aaline(surf, color, line[0], line[1], line[2], line[3], blend)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 253, in _draw_aaline
    set_at(surf, from_x, to_x, color)
  File "C:\Program Files\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\draw_py.py", line 33, in set_at
    surf.set_at((x, y), color)
TypeError: integer argument expected, got float
```

System details:
* os: windows 10 (64bit)
* python: 3.7.2 (64bit)
* pygame: 1.9.5.dev0 (SDL: 1.2.15) at ae1226c11ce61d3ea368047e7173e93b6cb8807b

**Comment by charlesej** [comment]
These errors were resolved by PR #683.
