### ISSUE TITLE
SDL2: freetype test failures

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#859]
```
..............F...F.........F..............
======================================================================
FAIL: test_freetype_Font_render_mono (test.freetype_test.FreeTypeFontTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 744, in test_freetype_Font_render_mono
    self.assertEqual(surf.get_alpha(), translucent_color.a)
AssertionError: None != 55

======================================================================
FAIL: test_freetype_Font_render_to_mono (test.freetype_test.FreeTypeFontTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 804, in test_freetype_Font_render_to_mono
    self.assertEqual(surf.get_at(bottomright), r_fg_color)
AssertionError: (30, 23, 50, 255) != (30, 22, 49, 253)

======================================================================
FAIL: test_issue_144 (test.freetype_test.FreeTypeFontTest)
Issue #144: unable to render text
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 1273, in test_issue_144
    self.assertRaises(pygame.error, font.render, s, (0, 0, 0))
AssertionError: error not raised by render

----------------------------------------------------------------------
Ran 43 tests in 3.325s

FAILED (failures=3)
```

**Related Docs:** 

https://www.pygame.org/docs/ref/freetype.html
https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit

**Comment by dlon** [comment]
The issues are fixed but one test is still skipped due to #864.

**Comment by illume** [comment]
@zoldalma999 removed a skip in #2351 because it now passes the test.

> Since Freetype tests dont run on CI

So probably they need to get added to CI.

These are the current failing test/freetype_test.py tests for me...
```
$ python test/freetype_test.py
pygame 2.0.1.dev1 (SDL 2.0.12, python 2.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
.....................s.......E.Fs...............
======================================================================
ERROR: test_freetype_SysFont_name (__main__.FreeTypeFontTest)
that SysFont accepts names of various types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/freetype_test.py", line 1715, in test_freetype_SysFont_name
    fonts_b = [f.encode() for f in fonts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)

======================================================================
FAIL: test_garbage_collection (__main__.FreeTypeFontTest)
Check reference counting on returned new references
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/freetype_test.py", line 1654, in test_garbage_collection
    self.assertEqual(getrefcount(item), 2, "refcount fail for item %d" % i)
AssertionError: refcount fail for item 0

----------------------------------------------------------------------
```

**Comment by illume** [comment]
Now I just have this one failing.
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/freetype_test.py", line 1655, in test_garbage_collection
    self.assertEqual(getrefcount(item), 2, "refcount fail for item %d" % i)
AssertionError: 4 != 2 : refcount fail for item 0
```

**Comment by illume** [comment]
Seems like a pylint cleanup caused it in 077c4daca90c028c4aa202c446755971ca83d5e1 

I'll put up a PR.

**Comment by ankith26** [comment]
And the one failing test is also fixed, thanks to illume.
So closing this issue
